// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;

namespace Content.Client.Lua.RoundEnd;

[GenerateTypedNameReferences]
public sealed partial class EvacuationTimerPanel : PanelContainer
{
    private bool _collapsed;
    private int _lastRemainingSeconds = -1;

    public bool Dragging;
    public Vector2 DragOffset;

    public EvacuationTimerPanel()
    {
        RobustXamlLoader.Load(this);
        CollapseButton.OnPressed += _ => ToggleCollapse();

        DragHeader.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            Dragging = true;
            DragOffset = args.PointerLocation.Position / UIScale - Position;
            args.Handle();
        };

        DragHeader.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                Dragging = false;
        };
    }

    private void ToggleCollapse()
    {
        _collapsed = !_collapsed;
        ContentContainer.Visible = !_collapsed;
        CollapseButton.Text = _collapsed ? "+" : "-";
    }

    public void UpdateTimer(TimeSpan remaining)
    {
        var remainingSeconds = Math.Max(0, (int)Math.Ceiling(remaining.TotalSeconds));
        if (remainingSeconds == _lastRemainingSeconds)
            return;

        _lastRemainingSeconds = remainingSeconds;

        var minutes = remainingSeconds / 60;
        var seconds = remainingSeconds % 60;
        TimeLabel.Text = $"{minutes:00}:{seconds:00}";

        StatusLabel.Text = remainingSeconds < 60
            ? Loc.GetString("evacuation-timer-panel-status-imminent")
            : Loc.GetString("evacuation-timer-panel-status-called");

        TimeLabel.FontColorOverride = remainingSeconds < 60
            ? Robust.Shared.Maths.Color.FromHex("#FF5555")
            : Robust.Shared.Maths.Color.FromHex("#FFDD44");
    }
}
