using Content.Client.Options.UI;
using Content.Lua.Shared.CCVar;
using Content.Lua.UIKit.Options;
using Content.Shared._RMC14.Announce;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);
        Control.AddOptionCheckBox(LuaCCVars.AnnouncementMirrorChat, AnnouncementMirrorChatCheckBox);
        Control.AddOptionDropDown(
            LuaCCVars.AnnouncementStyle,
            AnnouncementStyleDropDown,
            new[]
            {
                new OptionDropDownCVar<AnnouncementDisplayPreference>.ValueOption(
                    AnnouncementDisplayPreference.Stylized,
                    Loc.GetString("rmc-ui-options-announcements-style-stylized")),
                new OptionDropDownCVar<AnnouncementDisplayPreference>.ValueOption(
                    AnnouncementDisplayPreference.Default,
                    Loc.GetString("rmc-ui-options-announcements-style-default")),
                new OptionDropDownCVar<AnnouncementDisplayPreference>.ValueOption(
                    AnnouncementDisplayPreference.Simplified,
                    Loc.GetString("rmc-ui-options-announcements-style-simplified")),
                new OptionDropDownCVar<AnnouncementDisplayPreference>.ValueOption(
                    AnnouncementDisplayPreference.Disabled,
                    Loc.GetString("rmc-ui-options-announcements-style-disabled")),
            });

        if (IoCManager.Instance!.TryResolveType<IAccessibilityAnnouncementOptionsConfigurator>(out var announcements))
        {
            announcements.Configure(
                Control,
                _cfg,
                AnnouncementMaxVisibleSlider,
                AnnouncementPresetOverridesLabel,
                AnnouncementPresetOverridesContainer,
                AnnouncementLayoutEditorButton,
                AnnouncementLayoutResetButton,
                AnnouncementLayoutSummaryLabel);
        }

        Control.Initialize();
    }
}
