// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Lua.UIKit.Machines;
using Content.Lua.UIKit.Styles;
using Content.Client._NF.Research.UI;
using Content.Client.Parallax;
using Content.Client.Research;
using Content.Shared._NF.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class LunaResearchConsoleMenu : LunaWindow, ILunaResearchConsoleMenu
{
    public BaseWindow Window => this;
    private const float CardSize = 64f;
    private const float GridSize = 90f;
    private const float RankGap = 140f;
    private const float NodeGap = 88f;
    private const float GraphPad = 48f;
    private const float MinZoom = 0.25f;
    private const float MaxZoom = 2.0f;
    private const float ZoomStep = 1.1f;
    private const float PreferredWidth = 1200f;
    private const float PreferredHeight = 740f;
    private const float TopH = 108f;
    private const float LeftW = 180f;
    private const float BottomH = 28f;
    private const float InfoW = 310f;
    private const float InfoInset = 8f;
    private const float SectorsTopInset = 6f;
    private const float HubCenterBiasY = -34f;

    public Action<string>? OnTechnologyCardPressed { get; set; }
    public Action<string>? OnProjectCancelPressed { get; set; }
    public Action? OnServerButtonPressed { get; set; }

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    public EntityUid Entity;
    public ProtoId<TechnologyPrototype>? CurrentTech;
    public Dictionary<string, ResearchAvailability> List { get; set; } = new();
    public int Points;

    private readonly Dictionary<string, FancyResearchConsoleItem> _items = new();
    private readonly Dictionary<string, Vector2> _positions = new();
    private readonly HashSet<string> _visible = new();
    private List<ResearchProjectUiState> _active = new();
    private List<ResearchProjectUiState> _queued = new();
    private Dictionary<string, int> _technologyProgress = new();

    private ProtoId<RndFactionPrototype>? _faction;
    private string? _sectorId;
    private string _searchQuery = string.Empty;
    private Vector2 _offset;
    private float _zoom = 1f;
    private Vector2 _worldMin = Vector2.Zero;
    private Vector2 _worldMax = new(CardSize, CardSize);
    private bool _dragging;
    private bool _pendingRecenter = true;

    public LunaResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();

        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        ApplyChrome();
        HookEvents();
        OnOpen += OnWindowOpen;
    }

    private void ApplyChrome()
    {
        TopBar.PanelOverride = LunaWindowStyle.Panel();
        SectorsPanel.PanelOverride = LunaWindowStyle.Panel();
        InfoPanel.PanelOverride = LunaWindowStyle.Box(
            LunaWindowStyle.PanelBg.WithAlpha(0xC8 / 255f),
            LunaWindowStyle.PanelBorder.WithAlpha(0xEC / 255f));
        FooterBar.PanelOverride = LunaWindowStyle.Panel();
        ResearchesContainer.PanelOverride = LunaWindowStyle.Box(LunaWindowStyle.ContentBg, LunaWindowStyle.PanelBorder);

        LunaWindowStyle.StyleFooter(HintLabel);
        LunaWindowStyle.StyleFooter(VersionLabel);

        var parallax = new ParallaxControl
        {
            ParallaxPrototype = "Asteroids",
            HorizontalExpand = true,
            VerticalExpand = true,
            SpeedX = 0.15f,
            SpeedY = 0.15f,
            ScaleX = 2.5f,
            ScaleY = 2.5f,
            MouseFilter = MouseFilterMode.Ignore,
        };
        ResearchesContainer.AddChild(parallax);
        parallax.SetPositionInParent(0);
    }

    private void HookEvents()
    {
        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        RecenterButton.OnPressed += _ => Recenter();
        SearchEdit.OnTextChanged += args =>
        {
            _searchQuery = args.Text.Trim();
            ApplySearchFilter();
        };
        DragContainer.OnKeyBindDown += OnKeyDown;
        DragContainer.OnKeyBindUp += OnKeyUp;
        DragContainer.MouseMoved += OnGraphMouseMove;
        DragContainer.WheelMoved += OnWheel;
        TechViewport.OnResized += RelayoutCamera;
        OnResized += OnWindowResized;
    }

    private void OnWindowOpen()
    {
        ClampToScreen();
        ApplyShellLayout();
        ApplyCamera();
    }

    private void OnWindowResized()
    {
        ApplyShellLayout();
        RelayoutCamera();
    }

    private void ClampToScreen()
    {
        if (Parent == null)
            return;

        var screen = Parent.Size;
        if (screen.X < 64f || screen.Y < 64f)
            return;

        SetSize = new Vector2(Math.Min(PreferredWidth, screen.X), Math.Min(PreferredHeight, screen.Y));
    }

    private void ApplyShellLayout()
    {
        LayoutContainer.SetAnchorPreset(ResearchesContainer, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetMarginLeft(ResearchesContainer, LeftW);
        LayoutContainer.SetMarginTop(ResearchesContainer, TopH);
        LayoutContainer.SetMarginRight(ResearchesContainer, 0f);
        LayoutContainer.SetMarginBottom(ResearchesContainer, BottomH);

        LayoutContainer.SetAnchorPreset(SectorsPanel, LayoutContainer.LayoutPreset.LeftWide);
        LayoutContainer.SetMarginLeft(SectorsPanel, 0f);
        LayoutContainer.SetMarginTop(SectorsPanel, TopH + SectorsTopInset);
        LayoutContainer.SetMarginRight(SectorsPanel, LeftW);
        LayoutContainer.SetMarginBottom(SectorsPanel, BottomH);

        LayoutContainer.SetAnchorPreset(InfoPanel, LayoutContainer.LayoutPreset.RightWide);
        LayoutContainer.SetMarginLeft(InfoPanel, -(InfoW + InfoInset));
        LayoutContainer.SetMarginTop(InfoPanel, TopH + InfoInset);
        LayoutContainer.SetMarginRight(InfoPanel, InfoInset);
        LayoutContainer.SetMarginBottom(InfoPanel, BottomH + InfoInset);

        LayoutContainer.SetAnchorPreset(TopBar, LayoutContainer.LayoutPreset.TopWide);
        LayoutContainer.SetMarginLeft(TopBar, 0f);
        LayoutContainer.SetMarginTop(TopBar, 0f);
        LayoutContainer.SetMarginRight(TopBar, 0f);
        LayoutContainer.SetMarginBottom(TopBar, TopH);

        LayoutContainer.SetAnchorPreset(FooterBar, LayoutContainer.LayoutPreset.BottomWide);
        LayoutContainer.SetMarginLeft(FooterBar, 0f);
        LayoutContainer.SetMarginTop(FooterBar, -BottomH);
        LayoutContainer.SetMarginRight(FooterBar, 0f);
        LayoutContainer.SetMarginBottom(FooterBar, 0f);
    }

    public void SetEntity(EntityUid entity) => Entity = entity;

    public void SetResearchFaction(string? faction)
    {
        ProtoId<RndFactionPrototype>? next = faction != null ? faction : null;
        if (next == _faction)
            return;

        _faction = next;
        _sectorId = null;
        RebuildSectors();
    }

    public void UpdateQueue(
        List<ResearchProjectUiState> active,
        List<ResearchProjectUiState> queued,
        int _,
        Dictionary<string, int>? technologyProgress = null)
    {
        _active = active;
        _queued = queued;
        _technologyProgress = technologyProgress ?? new Dictionary<string, int>();
        RebuildQueue();
    }

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        List = dict;
        EnsureSector();
        RebuildGraph();
    }

    public void SyncProjectVisuals()
    {
        foreach (var (id, item) in _items)
        {
            var project = FindProject(id);
            if (project is { Cost: > 0 })
                item.SetProjectProgress(project.Progress / (float) project.Cost);
            else
                item.SetProjectProgress(null);
        }

        if (CurrentTech == null || InfoContainer.ChildCount == 0)
            return;

        if (InfoContainer.GetChild(0) is not FancyTechnologyInfoPanel panel)
            return;

        List.TryGetValue(CurrentTech.Value, out var availability);
        panel.SyncProject(FindProject(CurrentTech.Value), availability);
    }

    public void UpdateInformationPanel(int points, bool rebuildTiers = true)
    {
        Points = points;
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text", ("points", points)));
        ResearchAmountLabel.SetMessage(msg);

        if (!rebuildTiers)
            return;

        TierDisplayContainer.RemoveAllChildren();

        _entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database);

        IEnumerable<ProtoId<TechDisciplinePrototype>> disciplineIds =
            database is { SupportedDisciplines.Count: > 0 }
                ? database.SupportedDisciplines
                : new ProtoId<TechDisciplinePrototype>[]
                {
                    "NFEngineering", "NFMedical", "NFArsenal", "NFSalvage", "NFScience", "NFService", "Shiparmory",
                };

        foreach (var disciplineId in disciplineIds)
        {
            if (!_prototype.TryIndex(disciplineId, out TechDisciplinePrototype? discipline))
                continue;
            if (!_research.IsDisciplineFactionAllowed(Entity, discipline))
                continue;

            var completion = database != null
                ? _research.GetTierCompletionPercentage(Entity, database, discipline, _prototype)
                : 0;

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                MinSize = new Vector2(16, 16),
                SetSize = new Vector2(16, 16),
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepCentered,
                Texture = _sprite.Frame0(discipline.Icon),
            };
            var label = new RichTextLabel();
            label.SetMessage(Loc.GetString("research-console-discipline-percentage", ("perc", completion)));

            TierDisplayContainer.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 2,
                Children = { texture, label },
            });
        }

        var available = 0;
        var researched = 0;
        foreach (var (id, avail) in List)
        {
            if (!_visible.Contains(id))
                continue;
            available += 1;
            if (avail == ResearchAvailability.Researched)
                researched += 1;
        }

        ResearchedAmountLabel.Text = $"{researched}/{available}";
    }

    public override void Close()
    {
        base.Close();
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }

    #region Input

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        TryPan(args.Relative);
    }

    private void OnGraphMouseMove(GUIMouseMoveEventArgs args) => TryPan(args.Relative);

    private void TryPan(Vector2 relative)
    {
        if (!_dragging || relative == Vector2.Zero)
            return;

        _offset += relative;
        SoftClampOffset();
        ApplyCamera();
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args) => ZoomWheel(args);

    private void OnWheel(GUIMouseWheelEventArgs args) => ZoomWheel(args);

    private void ZoomWheel(GUIMouseWheelEventArgs args)
    {
        if (args.Handled || args.Delta.Y == 0f)
            return;

        var viewportLocal = (args.RelativePixelPosition - PixelSize / 2f) / Math.Max(UIScale, 0.01f);
        var oldZoom = _zoom;
        _zoom = Math.Clamp(_zoom * MathF.Pow(ZoomStep, args.Delta.Y), MinZoom, MaxZoom);
        if (Math.Abs(_zoom - oldZoom) < 0.0001f)
            return;

        var worldBefore = (viewportLocal - _offset) / oldZoom;
        _offset = viewportLocal - worldBefore * _zoom;
        SoftClampOffset();
        ApplyCamera();
        args.Handle();
    }

    private void OnKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = true;
    }

    private void OnKeyUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _dragging ? DragMode.None : base.GetDragModeFor(relativeMousePos);

    public void Recenter()
    {
        var view = ViewportSize();
        if (view.X < 8f || view.Y < 8f)
        {
            _pendingRecenter = true;
            return;
        }

        _zoom = 1f;
        ApplyHubRecenter(view);
        _pendingRecenter = false;
        ApplyCamera();
    }

    private void ApplyHubRecenter(Vector2 view)
    {
        var hubWorld = Vector2.Zero;
        if (!string.IsNullOrEmpty(_sectorId) && _positions.TryGetValue(_sectorId, out var hubPos))
            hubWorld = hubPos;

        var hubH = CardSize * _zoom;
        _offset = new Vector2(
            GraphPad - hubWorld.X * _zoom,
            view.Y * 0.5f - hubH * 0.5f - hubWorld.Y * _zoom + HubCenterBiasY);
    }

    #endregion

    #region Graph

    private void RebuildGraph()
    {
        DragContainer.RemoveAllChildren();
        _items.Clear();
        _positions.Clear();
        _visible.Clear();

        foreach (var id in CollectVisible())
            _visible.Add(id);

        LayoutGraph(_visible);

        foreach (var id in _visible)
        {
            if (!List.TryGetValue(id, out var availability))
                continue;
            if (!_prototype.TryIndex<TechnologyPrototype>(id, out var proto))
                continue;

            var item = new FancyResearchConsoleItem(
                proto,
                _research.GetTechnologyPrerequisites(_faction, proto),
                _sprite,
                availability);
            item.SetGraphCaptionVisible(false);
            item.ToolTip = Loc.GetString(proto.Name);
            item.SelectAction += SelectTech;
            item.IsSelected = id == CurrentTech;

            var project = FindProject(id);
            if (project is { Cost: > 0 })
                item.SetProjectProgress(project.Progress / (float) project.Cost);

            DragContainer.AddChild(item);
            _items[id] = item;
        }

        ApplySearchFilter();

        ApplyShellLayout();
        if (_pendingRecenter)
            Recenter();
        else
            ApplyCamera();

        if (CurrentTech != null &&
            _visible.Contains(CurrentTech.Value) &&
            _prototype.TryIndex(CurrentTech.Value, out var selected) &&
            List.TryGetValue(CurrentTech.Value, out var selectedAvail))
        {
            ApplyTechSelection(selected, selectedAvail, rightClick: false, allowToggleOff: false);
        }
    }

    private void ApplySearchFilter()
    {
        var query = _searchQuery;
        string? firstMatch = null;

        foreach (var (id, item) in _items)
        {
            var match = string.IsNullOrEmpty(query) || TechMatchesSearch(id, query);
            item.Visible = match;

            if (match && firstMatch == null && !string.IsNullOrEmpty(query))
                firstMatch = id;
        }

        if (firstMatch != null &&
            _positions.TryGetValue(firstMatch, out var pos) &&
            TechViewport.Size.X > 1f &&
            TechViewport.Size.Y > 1f)
        {
            var view = TechViewport.Size;
            _offset = new Vector2(
                view.X * 0.35f - pos.X * _zoom - CardSize * _zoom * 0.5f,
                view.Y * 0.45f - pos.Y * _zoom - CardSize * _zoom * 0.5f);
            ApplyCamera();
        }
    }

    private bool TechMatchesSearch(string id, string query)
    {
        if (!_prototype.TryIndex<TechnologyPrototype>(id, out var proto))
            return false;

        var name = Loc.GetString(proto.Name);
        if (name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        if (proto.ID.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        return false;
    }

    private void LayoutGraph(HashSet<string> visible)
    {
        _positions.Clear();
        _worldMin = Vector2.Zero;
        _worldMax = new Vector2(CardSize, CardSize);
        if (visible.Count == 0)
            return;

        var needsAuto = new HashSet<string>();
        foreach (var id in visible)
        {
            if (!_prototype.TryIndex<TechnologyPrototype>(id, out var proto))
                continue;

            if (TryGetYamlPosition(proto, out var yamlPos))
                _positions[id] = yamlPos * GridSize;
            else
                needsAuto.Add(id);
        }

        if (needsAuto.Count > 0)
            LayoutAutoRanks(needsAuto, visible);

        _worldMin = new Vector2(float.MaxValue, float.MaxValue);
        _worldMax = new Vector2(float.MinValue, float.MinValue);
        foreach (var pos in _positions.Values)
        {
            _worldMin = Vector2.Min(_worldMin, pos);
            _worldMax = Vector2.Max(_worldMax, pos + new Vector2(CardSize, CardSize));
        }

        if (_positions.Count == 0)
        {
            _worldMin = Vector2.Zero;
            _worldMax = new Vector2(CardSize, CardSize);
        }
    }

    private bool TryGetYamlPosition(TechnologyPrototype proto, out Vector2 position)
    {
        if (_faction != null &&
            proto.FactionOverrides.TryGetValue(_faction.Value, out var ov) &&
            ov.Position is { } factionPos)
        {
            position = factionPos;
            return true;
        }

        if (proto.Position is { } pos)
        {
            position = pos;
            return true;
        }

        position = default;
        return false;
    }

    private void LayoutAutoRanks(HashSet<string> needsAuto, HashSet<string> visible)
    {
        var ranks = new Dictionary<string, int>();
        foreach (var id in needsAuto)
            ranks[id] = 0;

        for (var pass = 0; pass < needsAuto.Count + 2; pass++)
        {
            var changed = false;
            foreach (var id in needsAuto)
            {
                var next = 0;
                if (_prototype.TryIndex<TechnologyPrototype>(id, out var proto))
                {
                    var maxParent = 0;
                    var any = false;
                    foreach (var prereq in _research.GetTechnologyPrerequisites(_faction, proto))
                    {
                        if (!visible.Contains(prereq))
                            continue;

                        var parentRank = 0;
                        if (ranks.TryGetValue(prereq, out var r))
                            parentRank = r;
                        else if (_positions.TryGetValue(prereq, out var parentPos))
                            parentRank = Math.Max(0, (int) MathF.Round(parentPos.X / RankGap));

                        any = true;
                        maxParent = Math.Max(maxParent, parentRank);
                    }

                    if (any)
                        next = maxParent + 1;
                }

                if (ranks[id] == next)
                    continue;
                ranks[id] = next;
                changed = true;
            }

            if (!changed)
                break;
        }

        var maxRank = 0;
        foreach (var r in ranks.Values)
            maxRank = Math.Max(maxRank, r);

        for (var rank = 0; rank <= maxRank; rank++)
        {
            var ids = new List<string>();
            foreach (var (id, value) in ranks)
            {
                if (value == rank)
                    ids.Add(id);
            }

            ids.Sort((a, b) =>
            {
                var na = _prototype.TryIndex<TechnologyPrototype>(a, out var pa) ? Loc.GetString(pa.Name) : a;
                var nb = _prototype.TryIndex<TechnologyPrototype>(b, out var pb) ? Loc.GetString(pb.Name) : b;
                return string.Compare(na, nb, StringComparison.CurrentCulture);
            });

            if (rank == 1 && _sectorId != null && ids.Remove(_sectorId))
                ids.Insert(Math.Max(0, ids.Count / 2), _sectorId);

            if (ids.Count == 0)
                continue;

            var x = rank * RankGap;
            for (var i = 0; i < ids.Count; i++)
            {
                var y = (i - (ids.Count - 1) * 0.5f) * NodeGap;
                _positions[ids[i]] = new Vector2(x, y);
            }
        }
    }

    private Vector2 ViewportSize()
    {
        var w = TechViewport.Width;
        var h = TechViewport.Height;
        var scale = Math.Max(UIScale, 0.01f);
        if (w < 8f && TechViewport.PixelWidth > 0)
            w = TechViewport.PixelWidth / scale;
        if (h < 8f && TechViewport.PixelHeight > 0)
            h = TechViewport.PixelHeight / scale;
        return new Vector2(w, h);
    }

    private void SoftClampOffset()
    {
        if (_offset.X > GraphPad)
            _offset.X = GraphPad;
    }

    private void ApplyCamera()
    {
        if (_pendingRecenter)
        {
            var ready = ViewportSize();
            if (ready.X >= 8f && ready.Y >= 8f)
            {
                ApplyHubRecenter(ready);
                _pendingRecenter = false;
            }
        }

        SoftClampOffset();

        DragContainer.HorizontalAlignment = HAlignment.Left;
        DragContainer.VerticalAlignment = VAlignment.Top;
        LayoutContainer.SetPosition(DragContainer, Vector2.Zero);

        foreach (var (id, item) in _items)
        {
            if (!_positions.TryGetValue(id, out var pos))
                continue;
            LayoutContainer.SetPosition(item, pos * _zoom + _offset);
            item.SetScale(_zoom);
            item.SetGraphCaptionVisible(false);
        }

        var view = ViewportSize();
        var maxX = Math.Max(_worldMax.X * _zoom, CardSize * _zoom);
        var maxY = Math.Max(_worldMax.Y * _zoom, CardSize * _zoom);
        var minY = Math.Min(_worldMin.Y * _zoom, 0f);
        DragContainer.SetWidth = Math.Max(maxX + view.X + GraphPad, Math.Max(view.X, 1f));
        DragContainer.SetHeight = Math.Max(maxY - minY + view.Y + GraphPad, Math.Max(view.Y, 1f));
    }

    private void RelayoutCamera()
    {
        ApplyShellLayout();
        if (_visible.Count == 0)
            return;
        LayoutGraph(_visible);
        if (_pendingRecenter)
            Recenter();
        else
            ApplyCamera();
    }

    #endregion

    #region Selection / sectors / queue

    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability, bool rightClick)
    {
        ApplyTechSelection(proto, availability, rightClick, allowToggleOff: true);
    }

    private void ApplyTechSelection(
        TechnologyPrototype proto,
        ResearchAvailability availability,
        bool rightClick,
        bool allowToggleOff)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        if (allowToggleOff && !rightClick && CurrentTech == proto.ID)
        {
            CurrentTech = null;
            foreach (var item in _items.Values)
                item.IsSelected = false;
            DragContainer.SetFocusTech(null);
            return;
        }

        CurrentTech = proto.ID;
        foreach (var item in _items.Values)
            item.IsSelected = item.Prototype.ID == CurrentTech;
        DragContainer.SetFocusTech(proto.ID);

        var hasAccess = _accessReader.IsAllowed(_player.LocalEntity.Value, Entity);
        var panel = new FancyTechnologyInfoPanel(proto, _faction, hasAccess, availability, _sprite, FindProject(proto.ID));
        panel.HorizontalExpand = true;
        panel.VerticalExpand = true;
        panel.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        panel.CancelAction += args => OnProjectCancelPressed?.Invoke(args.ID);
        LunaWindowStyle.ApplyCompactStyle(panel);
        InfoContainer.AddChild(panel);

        if (rightClick && panel.CanResearch && !panel.IsCancel)
            OnTechnologyCardPressed?.Invoke(proto.ID);
    }

    private void EnsureSector()
    {
        if (_sectorId != null &&
            _prototype.TryIndex<TechnologyPrototype>(_sectorId, out var selected) &&
            _research.IsTechnologyFactionAllowed(_faction, selected))
            return;

        _sectorId = null;
    }

    private void RebuildSectors()
    {
        EnsureSector();
        SectorsContainer.RemoveAllChildren();
    }

    private void RebuildQueue()
    {
        QueueContainer.RemoveAllChildren();
        if (_active.Count == 0 && _queued.Count == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("research-console-auto-research-empty"),
                ClipText = true,
                HorizontalExpand = true,
            };
            LunaWindowStyle.StyleMuted(empty);
            QueueContainer.AddChild(empty);
            return;
        }

        foreach (var project in _active)
            QueueContainer.AddChild(MakeChip(project, Loc.GetString("research-console-auto-research-active"), true));
        foreach (var project in _queued)
            QueueContainer.AddChild(MakeChip(project, Loc.GetString("research-console-auto-research-waiting"), false));
    }

    private Control MakeChip(ResearchProjectUiState project, string status, bool progress)
    {
        var panel = new PanelContainer
        {
            MinWidth = 168,
            MinHeight = progress ? 48 : 36,
            PanelOverride = LunaWindowStyle.Panel(),
        };
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8, 4, 8, 4),
            SeparationOverride = 2,
        };
        var title = new Label { Text = project.Name, ClipText = true };
        LunaWindowStyle.StyleSecondary(title);
        box.AddChild(title);
        var subText = progress
            ? (project.Started
                ? Loc.GetString("research-console-auto-research-active-time",
                    ("done", project.PathDone), ("total", project.PathTotal), ("seconds", project.RemainingSeconds))
                : Loc.GetString("research-console-auto-research-waiting-points",
                    ("done", project.PathDone), ("total", project.PathTotal)))
            : Loc.GetString("research-console-auto-research-queued",
                ("done", project.PathDone), ("total", project.PathTotal));
        var sub = new Label { Text = $"{status} {subText}", ClipText = true };
        LunaWindowStyle.StyleMuted(sub);
        box.AddChild(sub);
        if (progress && project.Cost > 0)
        {
            var bar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = 1,
                Value = Math.Clamp(project.Progress / (float) Math.Max(1, project.Cost), 0f, 1f),
                MinWidth = 148,
                SetHeight = 5,
                Margin = new Thickness(0, 2, 0, 0),
            };
            LunaWindowStyle.StyleProgressGood(bar, 5f);
            box.AddChild(bar);
        }

        panel.AddChild(box);
        return panel;
    }

    private ResearchProjectUiState? FindProject(string id)
    {
        foreach (var p in _active)
        {
            if (p.Id == id)
            {
                if (p.CurrentStepId == id && p.StepCost > 0)
                    return StepProgressProxy(p);
                return p;
            }

            if (p.CurrentStepId == id && p.StepCost > 0)
                return StepProgressProxy(p);
        }

        foreach (var p in _queued)
        {
            if (p.Id == id)
            {
                if (p.CurrentStepId == id && p.StepCost > 0)
                    return StepProgressProxy(p);
                return p;
            }

            if (p.CurrentStepId == id && p.StepCost > 0)
                return StepProgressProxy(p);
        }

        if (_technologyProgress.TryGetValue(id, out var invested) &&
            invested > 0 &&
            _prototype.TryIndex<TechnologyPrototype>(id, out var proto))
        {
            return new ResearchProjectUiState
            {
                Id = id,
                Name = Loc.GetString(proto.Name),
                Progress = invested,
                Cost = proto.Cost,
                Started = false,
                RemainingSeconds = (int) Math.Ceiling(Math.Max(0, proto.Cost - invested) / 100.0),
                CurrentStepId = id,
                StepProgress = invested,
                StepCost = proto.Cost,
                CanCancel = false,
            };
        }

        return null;
    }

    private static ResearchProjectUiState StepProgressProxy(ResearchProjectUiState focus)
    {
        return new ResearchProjectUiState
        {
            Id = focus.CurrentStepId,
            Name = focus.Name,
            Progress = focus.StepProgress,
            Cost = focus.StepCost,
            Started = focus.Started,
            RemainingSeconds = focus.RemainingSeconds,
            CurrentStepId = focus.CurrentStepId,
            StepProgress = focus.StepProgress,
            StepCost = focus.StepCost,
            PathDone = focus.PathDone,
            PathTotal = focus.PathTotal,
            CanCancel = true,
        };
    }

    private HashSet<string> CollectVisible()
    {
        var allowed = new HashSet<string>();
        foreach (var (id, _) in List)
        {
            if (!_prototype.TryIndex<TechnologyPrototype>(id, out var proto) || proto.Hidden)
                continue;
            if (!_research.IsTechnologyFactionAllowed(_faction, proto))
                continue;
            allowed.Add(id);
        }

        EnsureSector();
        if (_sectorId == null)
            return allowed;

        if (!_prototype.TryIndex<TechnologyPrototype>(_sectorId, out var sectorHub))
            return allowed;

        var visible = new HashSet<string>();
        if (allowed.Contains(_sectorId))
            visible.Add(_sectorId);

        foreach (var id in allowed)
        {
            if (visible.Contains(id))
                continue;
            if (BelongsToSector(id, sectorHub.Discipline))
                visible.Add(id);
        }

        return visible;
    }

    private bool BelongsToSector(string id, ProtoId<TechDisciplinePrototype> hubDiscipline)
    {
        var visited = new HashSet<string>();
        var stack = new Stack<string>();
        stack.Push(id);
        var hitSelected = false;

        while (stack.Count > 0)
        {
            var current = stack.Pop();
            if (!visited.Add(current))
                continue;

            if (current == _sectorId)
            {
                hitSelected = true;
                continue;
            }

            if (!_prototype.TryIndex<TechnologyPrototype>(current, out var proto))
                continue;

            foreach (var prereq in _research.GetTechnologyPrerequisites(_faction, proto))
                stack.Push(prereq);
        }

        if (hitSelected)
            return true;
        return _prototype.TryIndex<TechnologyPrototype>(id, out var tech) && tech.HasDiscipline(hubDiscipline);
    }

    #endregion
}
