using System.Numerics;
using System.Text;
using Content.Client.Stylesheets;
using Content.Lua.Shared.Expedition;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Expedition.UI;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionMissionCard : PanelContainer
{
    public const float CardWidth = 225f;
    private const float TextMaxWidth = 205f;
    private static readonly Color CardBg = Color.FromHex("#0E1218");
    private static readonly Color CardBorder = Color.FromHex("#2A3344");
    private static readonly Color CardBorderClaimed = Color.FromHex("#8B5A2B");
    private static readonly Color PlanetColor = Color.FromHex("#C5CEDB");
    private static readonly Color MutedColor = Color.FromHex("#7E8BA0");
    private static readonly Color AccentColor = Color.FromHex("#5EC8E8");
    private static readonly Color ValueColor = Color.FromHex("#F0C674");
    [Dependency] private readonly IResourceCache _cache = default!;
    private Font _navFont = default!;
    private ExpeditionPlanetPreview? _planetPreview;
    private bool _claimed;
    private bool _tabActive;
    private ushort? _missionIndex;
    public event Action? ClaimPressed;

    public ushort? MissionIndex => _missionIndex;

    public ExpeditionMissionCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PanelOverride = MakeCardStyle(CardBorder);
        Divider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1C2433"),
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1,
        };
        Divider.SetHeight = 1;
        _navFont = _cache.NotoStack(size: 10);
        ApplyNavFont(BiomeKeyLabel);
        ApplyNavFont(BiomeValueLabel);
        ApplyNavFont(PlanetKeyLabel);
        ApplyNavFont(PlanetValueLabel);
        ApplyNavFont(AirKeyLabel);
        ApplyNavFont(AirValueLabel);
        ApplyNavFont(WeatherKeyLabel);
        ApplyNavFont(WeatherValueLabel);
        ApplyNavFont(RewardKeyLabel);
        ApplyNavFont(DurationKeyLabel);
        ApplyNavFont(RewardValueLabel);
        ApplyNavFont(DurationValueLabel);
        BiomeKeyLabel.FontColorOverride = MutedColor;
        PlanetKeyLabel.FontColorOverride = MutedColor;
        AirKeyLabel.FontColorOverride = MutedColor;
        WeatherKeyLabel.FontColorOverride = MutedColor;
        RewardKeyLabel.FontColorOverride = MutedColor;
        DurationKeyLabel.FontColorOverride = MutedColor;
        BiomeValueLabel.FontColorOverride = AccentColor;
        PlanetValueLabel.FontColorOverride = PlanetColor;
        AirValueLabel.FontColorOverride = PlanetColor;
        WeatherValueLabel.FontColorOverride = PlanetColor;
        RewardValueLabel.FontColorOverride = ValueColor;
        DurationValueLabel.FontColorOverride = ValueColor;
        ClaimButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        ClaimButton.OnPressed += _ => ClaimPressed?.Invoke();
    }

    public void SetMission(ExpeditionOfferListing mission, bool blocked, bool claimed, bool tabActive)
    {
        _missionIndex = mission.Index;
        BiomeValueLabel.Text = WrapText(GetBiomeText(mission.BiomeId));
        var planetName = mission.PlanetName?.Trim();
        PlanetValueLabel.Text = WrapText(string.IsNullOrWhiteSpace(planetName) ? Loc.GetString("expedition-planet-unknown") : planetName);
        AirValueLabel.Text = WrapText(string.IsNullOrWhiteSpace(mission.AirDescription) ? Loc.GetString("expedition-air-unknown") : mission.AirDescription);
        WeatherValueLabel.Text = WrapText(string.IsNullOrWhiteSpace(mission.WeatherDescription) ? Loc.GetString("expedition-weather-none") : mission.WeatherDescription);
        RewardValueLabel.Text = Loc.GetString("expedition-window-credits", ("amount", mission.Reward));
        DurationValueLabel.Text = mission.Duration.ToString(@"mm\:ss");
        EnsurePreview(mission.BiomeId);
        _tabActive = tabActive;
        _planetPreview?.SetActive(tabActive);
        Claimed = claimed;
        ClaimButton.Disabled = blocked;
        InvalidateMeasure();
        InvalidateArrange();
    }

    public float MeasureCardHeight()
    {
        Measure(new Vector2(CardWidth, float.PositiveInfinity));
        return DesiredSize.Y;
    }

    public void SetUniformHeight(float height)
    { MinHeight = height; }

    public void SetTabActive(bool active)
    {
        if (_tabActive == active) return;
        _tabActive = active;
        _planetPreview?.SetActive(active);
    }

    public bool Claimed
    {
        get => _claimed;
        set
        {
            _claimed = value;
            PanelOverride = MakeCardStyle(value ? CardBorderClaimed : CardBorder);
            if (_claimed)
            {
                ClaimButton.AddStyleClass(StyleBase.ButtonCaution);
                ClaimButton.Text = Loc.GetString("offering-window-claimed");
            }
            else
            {
                ClaimButton.RemoveStyleClass(StyleBase.ButtonCaution);
                ClaimButton.Text = Loc.GetString("offering-window-claim");
            }
        }
    }

    private void EnsurePreview(string biomeId)
    {
        if (_planetPreview == null)
        {
            _planetPreview = new ExpeditionPlanetPreview();
            PlanetPreviewHost.AddChild(_planetPreview);
        }
        _planetPreview.SetBiome(biomeId);
    }

    private void ApplyNavFont(Label label)
    {
        label.FontOverride = _navFont;
        label.VerticalAlignment = VAlignment.Top;
        label.AddStyleClass(StyleNano.StyleClassLabelSmall);
    }

    private string WrapText(string text)
    {
        if (string.IsNullOrEmpty(text)) return text;
        var maxWidth = TextMaxWidth;
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0) return text;
        var sb = new StringBuilder();
        var line = new StringBuilder();
        foreach (var word in words)
        {
            var candidate = line.Length == 0 ? word : $"{line} {word}";
            if (MeasureWidth(candidate) <= maxWidth)
            {
                if (line.Length > 0) line.Append(' ');
                line.Append(word);
                continue;
            }
            if (line.Length > 0)
            {
                if (sb.Length > 0) sb.Append('\n');
                sb.Append(line);
                line.Clear();
            }
            if (MeasureWidth(word) <= maxWidth)
            {
                line.Append(word);
                continue;
            }
            foreach (var chunk in ChunkByWidth(word, maxWidth))
            {
                if (sb.Length > 0) sb.Append('\n');
                sb.Append(chunk);
            }
        }
        if (line.Length > 0)
        {
            if (sb.Length > 0) sb.Append('\n');
            sb.Append(line);
        }
        return sb.ToString();
    }

    private IEnumerable<string> ChunkByWidth(string text, float maxWidth)
    {
        var chunk = new StringBuilder();
        foreach (var rune in text.EnumerateRunes())
        {
            var next = chunk.ToString() + rune.ToString();
            if (chunk.Length > 0 && MeasureWidth(next) > maxWidth)
            {
                yield return chunk.ToString();
                chunk.Clear();
            }
            chunk.Append(rune);
        }
        if (chunk.Length > 0) yield return chunk.ToString();
    }

    private float MeasureWidth(string text)
    {
        var width = 0f;
        foreach (var rune in text.EnumerateRunes())
        {
            var metrics = _navFont.GetCharMetrics(rune, 1f);
            if (metrics != null) width += metrics.Value.Advance;
        }
        return width;
    }

    private static StyleBoxFlat MakeCardStyle(Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = CardBg,
            BorderColor = border,
            BorderThickness = new Thickness(1),
        };
    }

    private static string GetBiomeText(string biomeId)
    { return Loc.TryGetString(biomeId, out var localized) ? localized : biomeId; }
}
