using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Lua.UIKit.Styles;
using Content.Lua.Shared.Expedition;
using Content.Lua.UIKit.Shuttles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Timing;

namespace Content.Client.Lua.Expedition.UI;

[GenerateTypedNameReferences]
public sealed partial class ExpScreen : BoxContainer, IExpConsoleScreen
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public Control Control => this;

    public event Action<ushort, int>? OnClaim;
    public event Action? OnConfirm;
    public event Action? OnCancel;
    public event Action? OnFinish;
    private bool _claimed;
    private bool _queued;
    private bool _tabActive;
    private bool _generating;
    private bool _hasLandingCoords;
    private float _generationProgress;
    private string _landingCoordCode = string.Empty;
    private string _planetName = string.Empty;
    private float _coordScrambleTimer;
    private readonly Random _coordRandom = new();
    private static readonly char[] CoordAlphabet = "0123456789ABCDEFGHJKLMNPQRSTUVWXYZ".ToCharArray();
    private TimeSpan _nextOffer;
    private TimeSpan _cooldown;
    private TimeSpan? _confirmDeadlineEnd;
    private bool _cancelArmed;
    private readonly List<ExpeditionMissionCard> _missionCards = [];
    private readonly List<(ushort Index, int Seed)> _missionSignature = [];
    private bool _cardHeightSyncQueued;
    private static readonly TimeSpan ConfirmTotalTime = TimeSpan.FromMinutes(3);
    private static readonly Color Muted = Color.FromHex("#8A96A8");
    private static readonly Color Accent = Color.FromHex("#5EC8E8");
    private static readonly Color CoordAccent = Color.FromHex("#7DDBA3");

    public ExpScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LunaWindowStyle.StyleProgressCooldown(NextOfferBar);
        LunaWindowStyle.StyleProgressConfirm(ConfirmBar);
        LunaWindowStyle.StyleProgressGood(CoordBar);
        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0B0F14"),
            BorderColor = Color.FromHex("#243041"),
            BorderThickness = new Thickness(1),
        };
        StatusLabel.FontColorOverride = Color.FromHex("#E07070");
        NextOfferLabel.FontColorOverride = Muted;
        NextOfferText.FontColorOverride = Accent;
        ActiveCountLabel.FontColorOverride = Muted;
        ActiveCountValue.FontColorOverride = Accent;
        QueueCountLabel.FontColorOverride = Muted;
        QueueCountValue.FontColorOverride = Accent;
        ConfirmText.FontColorOverride = Color.FromHex("#E8A43A");
        CoordTitleLabel.FontColorOverride = CoordAccent;
        CoordValueLabel.FontColorOverride = Accent;
        CoordProgressText.FontColorOverride = Muted;
        FinishButton.OnPressed += _ => OnFinish?.Invoke();
        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
        CancelButton.OnPressed += _ =>
        {
            if (!_cancelArmed)
            {
                _cancelArmed = true;
                if (!CancelButton.StyleClasses.Contains("Danger")) CancelButton.StyleClasses.Add("Danger");
                return;
            }
            _cancelArmed = false;
            CancelButton.StyleClasses.Remove("Danger");
            OnCancel?.Invoke();
        };
    }

    public void SetTabActive(bool active)
    {
        if (_tabActive == active) return;
        _tabActive = active;
        foreach (var card in _missionCards) card.SetTabActive(active);
    }

    public void UpdateState(ExpeditionConsoleState? state)
    {
        if (state == null)
        {
            StatusLabel.Visible = false;
            CoordBox.Visible = false;
            ClearMissionCards();
            ConfirmButton.Disabled = true;
            CancelButton.Disabled = true;
            FinishButton.Disabled = true;
            ConfirmBox.Visible = false;
            _confirmDeadlineEnd = null;
            _generating = false;
            _hasLandingCoords = false;
            _landingCoordCode = string.Empty;
            _planetName = string.Empty;
            return;
        }
        if (!string.IsNullOrEmpty(state.BlockReason))
        {
            StatusLabel.Text = state.BlockReason;
            StatusLabel.Visible = true;
        }
        else { StatusLabel.Visible = false; }
        _nextOffer = state.NextOffer;
        _cooldown = state.CooldownTime;
        _claimed = state.Claimed;
        _queued = state.IsQueued;
        _generating = state.Generating;
        _generationProgress = state.GenerationProgress;
        _hasLandingCoords = state.HasLandingCoords;
        _landingCoordCode = state.LandingCoordCode ?? string.Empty;
        _planetName = string.Empty;
        foreach (var mission in state.Missions)
        {
            if (mission.Index != state.ActiveMission) continue;
            _planetName = mission.PlanetName;
            break;
        }
        UpdateCoordinatePanel();
        ConfirmButton.Disabled = !state.IsOurTurnToConfirm;
        SetCancelDisabled(!(state.IsQueued || state.IsOurTurnToConfirm));
        FinishButton.Disabled = !state.CanFinish;
        ActiveCountValue.Text = state.ActiveExpeditionCount.ToString();
        QueueCountValue.Text = state.IsQueued ? $"{state.QueuePosition}/{state.QueueTotal}" : "-";
        if (state.HasConfirmDeadline)
        {
            _confirmDeadlineEnd = _timing.CurTime + state.ConfirmDeadline;
            ConfirmBox.Visible = true;
        }
        else
        {
            _confirmDeadlineEnd = null;
            ConfirmBox.Visible = false;
        }
        var blocked = state.InCombat || !state.MassAllowed || !state.Enabled || !string.IsNullOrEmpty(state.BlockReason) || state.Claimed || state.Cooldown || state.IsQueued || state.Generating;
        SyncMissionCards(state, blocked);
        QueueCardHeightSync();
    }

    private void UpdateCoordinatePanel()
    {
        if (_generating)
        {
            CoordBox.Visible = true;
            CoordTitleLabel.Text = Loc.GetString("expedition-window-establishing-coords");
            CoordTitleLabel.FontColorOverride = CoordAccent;
            CoordBar.Value = Math.Clamp(_generationProgress, 0f, 1f);
            CoordProgressText.Text = $"{(int) (Math.Clamp(_generationProgress, 0f, 1f) * 100f)}%";
            return;
        }
        if (_hasLandingCoords)
        {
            CoordBox.Visible = true;
            CoordTitleLabel.Text = Loc.GetString("expedition-window-coords-locked");
            CoordTitleLabel.FontColorOverride = Accent;
            CoordValueLabel.Text = Loc.GetString("expedition-window-coords-format", ("code", string.IsNullOrEmpty(_landingCoordCode) ? "--------" : _landingCoordCode));
            CoordBar.Value = 1f;
            CoordProgressText.Text = "100%";
            return;
        }
        CoordBox.Visible = false;
    }

    private string ScrambleCoordCode()
    {
        var buf = new char[8];
        for (var i = 0; i < buf.Length; i++) buf[i] = CoordAlphabet[_coordRandom.Next(CoordAlphabet.Length)];
        var planet = string.IsNullOrEmpty(_planetName) ? Loc.GetString("expedition-planet-unknown") : _planetName;
        return $"{new string(buf)}-{planet}";
    }

    private void QueueCardHeightSync()
    { _cardHeightSyncQueued = true; }
    private void SyncCardHeights()
    {
        if (_missionCards.Count == 0) return;
        var maxHeight = 0f;
        foreach (var card in _missionCards) maxHeight = Math.Max(maxHeight, card.MeasureCardHeight());
        foreach (var card in _missionCards) card.SetUniformHeight(maxHeight);
    }

    private void SyncMissionCards(ExpeditionConsoleState state, bool blocked)
    {
        var signature = new List<(ushort Index, int Seed)>(state.Missions.Count);
        foreach (var mission in state.Missions) signature.Add((mission.Index, mission.Seed));
        var sameMissions = signature.Count == _missionSignature.Count;
        if (sameMissions)
        {
            for (var i = 0; i < signature.Count; i++)
            {
                if (signature[i] != _missionSignature[i])
                {
                    sameMissions = false;
                    break;
                }
            }
        }
        if (!sameMissions)
        {
            RebuildMissionCards(state, blocked);
            _missionSignature.Clear();
            _missionSignature.AddRange(signature);
            return;
        }
        for (var i = 0; i < _missionCards.Count && i < state.Missions.Count; i++)
        {
            var mission = state.Missions[i];
            var card = _missionCards[i];
            card.SetMission(mission, blocked, state.ActiveMission == mission.Index, _tabActive);
        }
    }

    private void RebuildMissionCards(ExpeditionConsoleState state, bool blocked)
    {
        ClearMissionCards();
        foreach (var mission in state.Missions)
        {
            var card = new ExpeditionMissionCard();
            card.SetMission(mission, blocked, state.ActiveMission == mission.Index, _tabActive);
            var index = mission.Index;
            var seed = mission.Seed;
            card.ClaimPressed += () => OnClaim?.Invoke(index, seed);
            MissionsContainer.AddChild(card);
            _missionCards.Add(card);
        }
    }

    private void ClearMissionCards()
    {
        foreach (var card in _missionCards) card.SetTabActive(false);
        _missionCards.Clear();
        _missionSignature.Clear();
        MissionsContainer.DisposeAllChildren();
    }

    private void SetCancelDisabled(bool disabled)
    {
        CancelButton.Disabled = disabled;
        if (disabled)
        {
            _cancelArmed = false;
            CancelButton.StyleClasses.Remove("Danger");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_cardHeightSyncQueued)
        {
            _cardHeightSyncQueued = false;
            SyncCardHeights();
        }
        if (_generating)
        {
            _coordScrambleTimer += args.DeltaSeconds;
            if (_coordScrambleTimer >= 0.08f)
            {
                _coordScrambleTimer = 0f;
                CoordValueLabel.Text = Loc.GetString("expedition-window-coords-scanning", ("code", ScrambleCoordCode()));
            }
            CoordBar.Value = Math.Clamp(_generationProgress, 0f, 1f);
            CoordProgressText.Text = $"{(int) (Math.Clamp(_generationProgress, 0f, 1f) * 100f)}%";
        }
        if (_confirmDeadlineEnd != null)
        {
            var remaining = _confirmDeadlineEnd.Value - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
            {
                ConfirmBar.Value = 1f;
                ConfirmText.Text = "00:00";
            }
            else
            {
                var ratio = (float) (remaining / ConfirmTotalTime);
                ConfirmBar.Value = 1f - Math.Clamp(ratio, 0f, 1f);
                ConfirmText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }
        if (_claimed || _queued || _generating)
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
        else if (_cooldown > TimeSpan.Zero)
        {
            var remaining = _nextOffer - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
            {
                NextOfferBar.Value = 1f;
                NextOfferText.Text = "00:00";
            }
            else
            {
                NextOfferBar.Value = 1f - (float) (remaining / _cooldown);
                NextOfferText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }
        else
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
    }
}
