// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.
using Content.Lua.Shared.DonateShop;
using Content.Lua.Shared.SponsorLoadout;
using Content.Shared._NF.Bank;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
using System.Linq;

namespace Content.Client.Lua.DonateShop.UI;

[GenerateTypedNameReferences]
public sealed partial class DonateShopWindow : BaseWindow
{
    private const int DragHeaderHeight = 180;
    private const string TierCategoryPrefix = "UplinkVipTier";
    private static readonly Color ShareholderColor = Color.FromHex("#F05C29");
    private static readonly Color GodColor = Color.FromHex("#00FF4A");
    private static readonly Color BoostColor = Color.FromHex("#FF4CF1");
    private static readonly Color Rank1To3Color = Color.FromHex("#F80000");
    private static readonly Color Rank4Color = Color.FromHex("#E84848");
    private static readonly Color Rank5To6Color = Color.FromHex("#D028E0");
    private static readonly Color Rank7To8Color = Color.FromHex("#8840F8");
    private static readonly Color Rank9To10Color = Color.FromHex("#3E7BD9");
    private static readonly StyleBoxFlat ButtonStyle = new()
    {
        BackgroundColor = Color.FromHex("#6E5127"),
        BorderColor = Color.FromHex("#A8823D"),
        BorderThickness = new Thickness(1f),
    };
    private static readonly StyleBoxFlat SelectedButtonStyle = new()
    {
        BackgroundColor = Color.FromHex("#8A6736"),
        BorderColor = Color.FromHex("#DDBA7A"),
        BorderThickness = new Thickness(1f),
    };

    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;
    public event Action<string>? OnBuyPressed;
    private Control _noSubOverlay = default!;
    private bool _canAccess;
    private Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> _balance = [];
    private List<ListingDataWithCostModifiers> _listings = [];
    private string _currentTierTab = string.Empty;
    private string _currentCategory = string.Empty;
    private int _bankBalance;
    private bool _hasBankBalance;
    private HashSet<string> _rawTierNames = [];
    public DonateShopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Resizable = false;
        WindowTitle.Text = Loc.GetString("donate-shop-menu-title");
        DonateCloseButton.OnPressed += _ => Close();
        LayoutContainer.SetAnchorPreset(ItemsScroll, LayoutContainer.LayoutPreset.Wide);
        _noSubOverlay = BuildNoSubOverlay();
        ItemsAreaContainer.AddChild(_noSubOverlay);
        LayoutContainer.SetAnchorPreset(_noSubOverlay, LayoutContainer.LayoutPreset.Wide);
    }

    private Control BuildNoSubOverlay()
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#140F0ACC") },
            MouseFilter = MouseFilterMode.Stop,
            Visible = false,
        };
        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 12,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        vbox.AddChild(new Label
        {
            Text = "У ВАС НЕТ ПОДПИСКИ =(",
            FontColorOverride = Color.FromHex("#F3D8A2"),
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "LabelBig" },
        });
        vbox.AddChild(new Label
        {
            Text = "ИСПРАВЬТЕ ЭТО!",
            FontColorOverride = Color.FromHex("#CCCCCC"),
            HorizontalAlignment = HAlignment.Center,
        });
        var btn = new Button
        {
            Text = "КУПИТЬ ПОДПИСКУ",
            HorizontalAlignment = HAlignment.Center,
            MinWidth = 220,
            StyleBoxOverride = ButtonStyle,
        };
        btn.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://boosty.to/luaworld"));
        vbox.AddChild(btn);
        panel.AddChild(vbox);
        return panel;
    }

    public void UpdateState(DonateShopStateMessage state)
    {
        string roleMarkup;
        var headerTokens = DonorGroups.GetShopHeaderTokens(state.ActiveTierNames);
        if (headerTokens.Count > 0)
        {
            var parts = new List<string>();
            foreach (var token in headerTokens)
            {
                var color = GetHeaderTokenColor(token);
                parts.Add($"[color={color.ToHex()}]{GetTierDisplayName(token)}[/color]");
            }
            roleMarkup = string.Join(", ", parts);
        }
        else
        {
            var fallback = state.TierName;
            var fallbackColor = GetTierColor(fallback);
            roleMarkup = $"[color={fallbackColor.ToHex()}]{GetTierDisplayName(fallback)}[/color]";
        }
        RoleLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("donate-shop-role-label", ("role", roleMarkup))));
        StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("donate-shop-status-label", ("status", state.SubscriptionStatus))));
        string bankAmount;
        if (state.HasBankBalance)
            bankAmount = BankSystemExtensions.ToSpesoString(state.BankBalance);
        else if (state.Balance.TryGetValue("Speso", out var speso))
            bankAmount = BankSystemExtensions.ToSpesoString((int) speso);
        else
            bankAmount = "0 $";

        var lunaAmount = FormatLunaAmount(state.LunaCoinBalance);

        BalanceLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("donate-shop-balance-label", ("balance", bankAmount), ("luna", lunaAmount))));
        LunaCoinLabel.Visible = false;
        LunaCoinLabel.SetMessage(FormattedMessage.Empty);
        if (!string.IsNullOrWhiteSpace(state.ErrorLocKey))
        {
            ErrorLabel.Visible = true;
            ErrorLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString(state.ErrorLocKey)));
        }
        else
        {
            ErrorLabel.Visible = false;
            ErrorLabel.SetMessage(FormattedMessage.Empty);
        }
        _canAccess = state.CanAccess;
        _balance = state.Balance;
        _bankBalance = state.BankBalance;
        _hasBankBalance = state.HasBankBalance;
        _rawTierNames = state.ActiveTierNames.ToHashSet(StringComparer.OrdinalIgnoreCase);
        _listings = state.Listings
            .OrderBy(listing => listing.Priority)
            .ThenBy(listing => listing.Cost.Values.Sum())
            .ToList();
        PopulateTierTabs();
        PopulateItemCategories();
        RebuildItemList();
        UpdateOverlayVisibility();
    }

    private void UpdateOverlayVisibility()
    {
        _noSubOverlay.Visible = !OwnsCurrentTab();
    }

    private bool OwnsCurrentTab()
    {
        if (_currentTierTab == "UplinkVipTierShareholder")
            return OwnsRaw(DonorGroups.Shareholder) || OwnsRaw(DonorGroups.ShareholderLua);
        if (TryGetTierNameForCategory(_currentTierTab, out var tabTier))
            return OwnsRaw(tabTier);
        return false;
    }

    private bool OwnsRaw(string canonical)
    {
        foreach (var roleName in _rawTierNames)
        {
            if (DonorGroups.TryResolveTier(roleName, out var tier) &&
                string.Equals(tier, canonical, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    private bool IsTierCategory(string categoryId) => categoryId.StartsWith(TierCategoryPrefix, StringComparison.Ordinal);

    private static bool IsRankShopTab(string tabId) =>
        TryGetTierNameForCategory(tabId, out var tier) &&
        DonorGroups.RankShopCategoryOrder.Contains(tier);
    private static readonly Dictionary<string, string> TierNameToCategoryId = new(StringComparer.OrdinalIgnoreCase)
    {
        [DonorGroups.Shareholder] = "UplinkVipTierShareholder",
        [DonorGroups.ShareholderLua] = "UplinkVipTierShareholderLua",
        [DonorGroups.God] = "UplinkVipTierGod",
        [DonorGroups.Boost] = "UplinkVipTierBoost",
        [DonorGroups.Rank1] = "UplinkVipTierRank1",
        [DonorGroups.Rank2] = "UplinkVipTierRank2",
        [DonorGroups.Rank3] = "UplinkVipTierRank3",
        [DonorGroups.Rank4] = "UplinkVipTierRank4",
        [DonorGroups.Rank5] = "UplinkVipTierRank5",
        [DonorGroups.Rank6] = "UplinkVipTierRank6",
        [DonorGroups.Rank7] = "UplinkVipTierRank7",
        [DonorGroups.Rank8] = "UplinkVipTierRank8",
        [DonorGroups.Rank9] = "UplinkVipTierRank9",
        [DonorGroups.Rank10] = "UplinkVipTierRank10",
    };

    private static bool TryGetTierNameForCategory(string categoryId, out string tierName)
    {
        foreach (var (tier, category) in TierNameToCategoryId)
        {
            if (!string.Equals(category, categoryId, StringComparison.Ordinal))
                continue;
            tierName = tier;
            return true;
        }

        tierName = string.Empty;
        return false;
    }
    private HashSet<string> GetVisibleTierCategories()
    {
        if (string.IsNullOrEmpty(_currentTierTab))
            return [];

        var visible = new HashSet<string>(StringComparer.Ordinal);
        if (_currentTierTab == "UplinkVipTierShareholder")
        {
            if (OwnsRaw(DonorGroups.Shareholder) || !OwnsRaw(DonorGroups.ShareholderLua))
                visible.Add("UplinkVipTierShareholder");
            if (OwnsRaw(DonorGroups.ShareholderLua))
                visible.Add("UplinkVipTierShareholderLua");
            return visible;
        }

        if (!TryGetTierNameForCategory(_currentTierTab, out var tabTier))
            return new HashSet<string>(StringComparer.Ordinal) { _currentTierTab };

        foreach (var tier in DonorGroups.GetEffectiveTiers([tabTier]))
        {
            if (TierNameToCategoryId.TryGetValue(tier, out var categoryId))
                visible.Add(categoryId);
        }

        if (visible.Count == 0)
            visible.Add(_currentTierTab);
        return visible;
    }

    private void PopulateTierTabs()
    {
        TierTabContainer.RemoveAllChildren();
        var tabs = new List<(string Id, string LocKey)>
        {
            ("UplinkVipTierShareholder", "store-vip-tier-shareholder"),
        };
        if (OwnsRaw(DonorGroups.God))
            tabs.Add(("UplinkVipTierGod", "store-vip-tier-god"));
        foreach (var rank in DonorGroups.RankShopCategoryOrder)
        {
            if (!OwnsRaw(rank) || !TierNameToCategoryId.TryGetValue(rank, out var tabId))
                continue;
            tabs.Add((tabId, $"store-vip-tier-{rank.ToLowerInvariant()}"));
        }
        if (OwnsRaw(DonorGroups.Boost))
            tabs.Add(("UplinkVipTierBoost", "store-vip-tier-boost"));

        if (tabs.All(t => t.Id != _currentTierTab))
            _currentTierTab = tabs[0].Id;
        var group = new ButtonGroup();
        foreach (var (id, locKey) in tabs)
            AddTierTabButton(group, id, Loc.GetString(locKey));
    }

    private void AddTierTabButton(ButtonGroup group, string tierId, string text)
    {
        var button = new DonateCategoryButton
        {
            CategoryId = tierId,
            Text = text,
            Group = group,
            ToggleMode = true,
            Pressed = tierId == _currentTierTab,
            StyleClasses = { "OpenBoth" },
            MinWidth = 80,
        };
        button.Label.FontColorOverride = GetTabColor(tierId);
        button.OnPressed += _ =>
        {
            _currentTierTab = button.CategoryId;
            _currentCategory = string.Empty;
            RefreshTierTabStyles();
            PopulateItemCategories();
            RebuildItemList();
            UpdateOverlayVisibility();
        };
        button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        TierTabContainer.AddChild(button);
    }

    private void RefreshTierTabStyles()
    {
        foreach (var child in TierTabContainer.Children)
        {
            if (child is not DonateCategoryButton button) continue;
            button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        }
    }
    private void PopulateItemCategories()
    {
        CategoryListContainer.RemoveAllChildren();
        var visibleTierCategories = GetVisibleTierCategories();
        var tierListings = _listings
            .Where(l => l.Categories.Any(c => visibleTierCategories.Contains(c.ToString())))
            .ToList();
        var itemCategories = new List<(string Id, string Name, Color? Color)>();
        if (IsRankShopTab(_currentTierTab))
        {
            foreach (var rank in DonorGroups.RankShopCategoryOrder)
            {
                if (!TierNameToCategoryId.TryGetValue(rank, out var categoryId))
                    continue;
                if (!visibleTierCategories.Contains(categoryId))
                    continue;
                if (!tierListings.Any(l => l.Categories.Any(c => c.ToString() == categoryId)))
                    continue;
                if (!_prototype.TryIndex<StoreCategoryPrototype>(categoryId, out var proto))
                    continue;
                itemCategories.Add((proto.ID, Loc.GetString(proto.Name), GetTierColor(rank)));
            }
        }
        else
        {
            foreach (var listing in tierListings)
            {
                foreach (var cat in listing.Categories)
                {
                    var id = cat.ToString();
                    if (IsTierCategory(id))
                        continue;
                    if (!_prototype.TryIndex(cat, out StoreCategoryPrototype? proto))
                        continue;
                    if (itemCategories.Any(x => x.Id == proto.ID))
                        continue;
                    itemCategories.Add((proto.ID, Loc.GetString(proto.Name), null));
                }
            }

            itemCategories = itemCategories
                .OrderBy(c => _prototype.TryIndex<StoreCategoryPrototype>(c.Id, out var proto) ? proto.Priority : 0)
                .ToList();
        }

        CategoryPanel.Visible = itemCategories.Count > 0;
        if (itemCategories.Count == 0 || itemCategories.All(c => c.Id != _currentCategory))
            _currentCategory = itemCategories.Count > 0 ? itemCategories[0].Id : string.Empty;
        var group = new ButtonGroup();
        foreach (var cat in itemCategories)
            AddCategoryButton(group, cat.Id, cat.Name, cat.Color);
    }

    private void AddCategoryButton(ButtonGroup group, string categoryId, string text, Color? textColor = null)
    {
        var button = new DonateCategoryButton
        {
            CategoryId = categoryId,
            Text = text,
            Group = group,
            ToggleMode = true,
            Pressed = categoryId == _currentCategory,
            StyleClasses = { "OpenBoth" },
        };
        if (textColor is { } color)
            button.Label.FontColorOverride = color;
        button.OnPressed += _ =>
        {
            _currentCategory = button.CategoryId;
            RefreshCategoryButtonStyles();
            RebuildItemList();
        };
        button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        CategoryListContainer.AddChild(button);
    }

    private void RefreshCategoryButtonStyles()
    {
        foreach (var child in CategoryListContainer.Children)
        {
            if (child is not DonateCategoryButton button) continue;
            button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        }
    }

    private void RebuildItemList()
    {
        ItemsContainer.RemoveAllChildren();
        var filtered = _listings
            .Where(ShouldShow)
            .ToList();
        foreach (var listing in filtered) AddItemEntry(listing, _canAccess, CanBuyListing(listing));
        if (filtered.Count == 0)
        {
            ItemsContainer.AddChild(new Label
            { Text = Loc.GetString("donate-shop-no-items"), });
        }
    }

    private bool ShouldShow(ListingDataWithCostModifiers listing)
    {
        var visibleTierCategories = GetVisibleTierCategories();
        if (visibleTierCategories.Count > 0 &&
            !listing.Categories.Any(c => visibleTierCategories.Contains(c.ToString())))
            return false;
        if (!string.IsNullOrEmpty(_currentCategory)) return listing.Categories.Any(c => c.ToString() == _currentCategory);
        return true;
    }

    private void AddItemEntry(ListingDataWithCostModifiers listing, bool canAccess, bool canBuy)
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(listing, _prototype);
        var desc = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(listing, _prototype);
        var iconTexture = GetListingIconTexture(listing);
        var wrapper = new PanelContainer();
        wrapper.PanelOverride = new StyleBoxFlat
        {
            BorderColor = Color.FromHex("#5D4631"),
            BorderThickness = new Thickness(1f),
            BackgroundColor = Color.FromHex("#1B1510")
        };
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(8f)
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        if (iconTexture != null)
        {
            content.AddChild(new TextureRect
            {
                Texture = iconTexture,
                MinSize = new Vector2(48f, 48f),
                MaxSize = new Vector2(48f, 48f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            });
        }
        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        header.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
        });
        var description = new RichTextLabel { HorizontalExpand = true };
        description.SetMessage(FormattedMessage.FromMarkupPermissive(desc));
        var actionRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        var costLabel = new Label
        {
            FontColorOverride = Color.FromHex("#DDBA7A"),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        var stockInfo = GetStockInfo(listing);
        costLabel.Text = stockInfo.HasValue ? $"{GetCostString(listing.Cost)}  [{listing.PurchaseAmount}/{stockInfo.Value}]" : GetCostString(listing.Cost);
        if (stockInfo.HasValue && listing.PurchaseAmount >= stockInfo.Value) costLabel.FontColorOverride = Color.FromHex("#888888");
        actionRow.AddChild(costLabel);
        var buyButton = new Button
        {
            Text = Loc.GetString("donate-shop-buy"),
            HorizontalAlignment = HAlignment.Right,
            Disabled = !canAccess || !canBuy,
            StyleBoxOverride = ButtonStyle,
            MinWidth = 104,
        };
        buyButton.OnPressed += _ => OnBuyPressed?.Invoke(listing.ID);
        actionRow.AddChild(buyButton);
        textColumn.AddChild(header);
        textColumn.AddChild(description);
        textColumn.AddChild(actionRow);
        content.AddChild(textColumn);
        root.AddChild(content);
        wrapper.AddChild(root);
        ItemsContainer.AddChild(wrapper);
    }

    private bool CanBuyListing(ListingDataWithCostModifiers listing)
    {
        if (!_hasBankBalance) return listing.CanBuyWith(_balance);
        foreach (var (currency, amount) in listing.Cost)
        {
            if (currency == "Speso")
            {
                if (_bankBalance < (int) amount) return false;
                continue;
            }
            if (!_balance.TryGetValue(currency, out var balance) || balance < amount) return false;
        }
        return true;
    }

    private Texture? GetListingIconTexture(ListingDataWithCostModifiers listing)
    {
        var sprite = _entity.System<SpriteSystem>();
        if (listing.Icon != null) return sprite.Frame0(listing.Icon);
        if (listing.ProductEntity != null) return sprite.GetPrototypeIcon(listing.ProductEntity).Default;
        return null;
    }

    private static int? GetStockInfo(ListingDataWithCostModifiers listing) => listing.Stock is > 0 ? listing.Stock : null;

    private string GetCostString(IReadOnlyDictionary<ProtoId<CurrencyPrototype>, FixedPoint2> cost)
    {
        if (cost.Count == 0) return Loc.GetString("store-currency-free");
        return string.Join(" + ", cost.Select(entry => entry.Key.Id switch
        {
            "Speso" => BankSystemExtensions.ToSpesoString((int) entry.Value),
            "LunaCoin" => $"⏾{BankSystemExtensions.ToIndependentString((int) entry.Value)}",
            _ => BankSystemExtensions.ToIndependentString((int) entry.Value)
        }));
    }

    private static string FormatLunaAmount(long amount)
    {
        if (amount <= 0)
            return BankSystemExtensions.ToIndependentString(0);

        var clamped = amount > int.MaxValue ? int.MaxValue : (int) amount;
        return BankSystemExtensions.ToIndependentString(clamped);
    }

    private static Color GetHeaderTokenColor(string token) => GetTierColor(token);

    private static Color GetTabColor(string tabId)
    {
        if (tabId == "UplinkVipTierShareholder")
            return ShareholderColor;
        if (TryGetTierNameForCategory(tabId, out var tier))
            return GetTierColor(tier);
        return Color.White;
    }

    private static Color GetTierColor(string tierName)
    {
        if (!DonorGroups.TryResolveTier(tierName, out var tier))
            return Rank1To3Color;

        return tier switch
        {
            DonorGroups.Shareholder or DonorGroups.ShareholderLua => ShareholderColor,
            DonorGroups.God => GodColor,
            DonorGroups.Boost => BoostColor,
            DonorGroups.Rank1 or DonorGroups.Rank2 or DonorGroups.Rank3 => Rank1To3Color,
            DonorGroups.Rank4 => Rank4Color,
            DonorGroups.Rank5 or DonorGroups.Rank6 => Rank5To6Color,
            DonorGroups.Rank7 or DonorGroups.Rank8 => Rank7To8Color,
            DonorGroups.Rank9 or DonorGroups.Rank10 => Rank9To10Color,
            _ => Rank1To3Color,
        };
    }

    private string GetTierDisplayName(string tierName)
    {
        if (!DonorGroups.TryResolveTier(tierName, out var tier))
            return tierName;

        var locKey = tier switch
        {
            DonorGroups.Shareholder => "store-vip-tier-shareholder",
            DonorGroups.ShareholderLua => "store-vip-tier-shareholderlua",
            DonorGroups.God => "store-vip-tier-god",
            DonorGroups.Boost => "store-vip-tier-boost",
            DonorGroups.Rank1 => "store-vip-tier-rank1",
            DonorGroups.Rank2 => "store-vip-tier-rank2",
            DonorGroups.Rank3 => "store-vip-tier-rank3",
            DonorGroups.Rank4 => "store-vip-tier-rank4",
            DonorGroups.Rank5 => "store-vip-tier-rank5",
            DonorGroups.Rank6 => "store-vip-tier-rank6",
            DonorGroups.Rank7 => "store-vip-tier-rank7",
            DonorGroups.Rank8 => "store-vip-tier-rank8",
            DonorGroups.Rank9 => "store-vip-tier-rank9",
            DonorGroups.Rank10 => "store-vip-tier-rank10",
            _ => null,
        };
        return locKey is null ? tierName : Loc.GetString(locKey);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => relativeMousePos.Y <= DragHeaderHeight ? DragMode.Move : DragMode.None;

    private sealed class DonateCategoryButton : Button
    { public string CategoryId = string.Empty; }
}
