// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.Info;

[GenerateTypedNameReferences]
public sealed partial class PublicOfferWindow : LunaWindow
{
    private bool _allowClose;

    public event Action? OnAcceptPressed;
    public event Action? OnDeclinePressed;

    public PublicOfferWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyLunaChrome();
        ApplyLunaInterior();

        Resizable = false;
        CloseButton.Visible = false;

        AcceptButton.OnPressed += _ => OnAcceptPressed?.Invoke();
        DeclineButton.OnPressed += _ => OnDeclinePressed?.Invoke();
    }

    public void CloseAllowed()
    {
        _allowClose = true;
        Close();
        _allowClose = false;
    }

    public override void Close()
    {
        if (!_allowClose)
            return;

        base.Close();
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        LunaWindowStyle.StyleDivider(Divider);

        AcceptButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        if (AcceptButton.Label != null)
        {
            AcceptButton.Label.FontOverride = LunaWindowStyle.FontSmall;
            AcceptButton.Label.FontColorOverride = LunaWindowStyle.AccentGood;
        }

        DeclineButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        if (DeclineButton.Label != null)
        {
            DeclineButton.Label.FontOverride = LunaWindowStyle.FontSmall;
            DeclineButton.Label.FontColorOverride = LunaWindowStyle.AccentBad;
        }
    }
}
