// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Content.Client.Guidebook;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lua.Info;

[GenerateTypedNameReferences]
public sealed partial class PublicOfferControl : BoxContainer
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

    public PublicOfferControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        LoadOffer();
    }

    private void LoadOffer()
    {
        Scroll.SetScrollValue(default);
        OfferContainer.Children.Clear();
        _parsingMan.TryAddMarkup(OfferContainer, new ProtoId<GuideEntryPrototype>("LuaPublicOffer"));
    }
}
