// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Lua.Research;
using Content.Lua.UIKit.Styles;
using Content.Client._NF.Lathe.UI;
using Content.Client.Lathe;
using Content.Client.Lathe.UI;
using Content.Client.Materials;
using Content.Client.Weapons.Ranged.Systems;
using Content.Lua.Shared.Lathe;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Content.Shared.Weapons.Ranged.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class AmmoTechFabMenu : LunaWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;
    private readonly GunSystem _guns;
    private readonly SharedContainerSystem _containers;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;
    public event Action<bool>? OnLoopCheckboxPressed;
    public event Action<bool>? OnSkipCheckboxPressed;
    public event Action<NetEntity>? AutoloaderEjectAction;
    public event Action? AutoloaderEjectAllAction;
    public event Action<NetEntity, string>? AutoloaderSelectAction;

    public List<ProtoId<LatheRecipePrototype>> Recipes = new();

    public EntityUid Entity;

    private List<ProtoId<LatheCategoryPrototype>> _calibers = new();
    private ProtoId<LatheCategoryPrototype>? _currentCaliber;
    private ProtoId<LatheCategoryPrototype>? _currentKind;
    private string? _currentDiscipline;
    private List<string>? _disciplines;
    private Dictionary<string, string>? _recipeDisciplineMap;

    private TimeSpan? _productionStartedAt;
    private TimeSpan? _productionLength;
    private string _autoloaderStructureKey = string.Empty;
    private readonly Dictionary<EntityUid, AutoloaderRow> _autoloaderRows = new();
    private readonly List<AutoloaderGroup> _autoloaderGroups = new();
    private readonly List<EntProtoId> _choiceScratch = new();

    public AmmoTechFabMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<LatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();
        _guns = _entityManager.System<GunSystem>();
        _containers = _entityManager.System<SharedContainerSystem>();

        ApplyLunaInterior();
        RebuildKindTabs();

        SearchBar.OnTextChanged += _ => PopulateRecipes();
        AmountLineEdit.OnTextChanged += _ => PopulateRecipes();
        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();
        DeleteFabricating.AddStyleClass("OpenLeft");
        LoopCheckbox.OnPressed += _ => OnLoopCheckboxPressed?.Invoke(LoopCheckbox.Pressed);
        SkipCheckbox.OnPressed += _ => OnSkipCheckboxPressed?.Invoke(SkipCheckbox.Pressed);
        AutoloaderEjectAllButton.OnPressed += _ => AutoloaderEjectAllAction?.Invoke();
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        CaliberPanel.PanelOverride = LunaWindowStyle.Panel();
        RecipePanel.PanelOverride = LunaWindowStyle.Box(LunaWindowStyle.ContentBg, LunaWindowStyle.PanelBorder);
        QueuePanel.PanelOverride = LunaWindowStyle.Panel();
        MaterialsPanel.PanelOverride = LunaWindowStyle.Panel();
        AutoloaderPanel.PanelOverride = LunaWindowStyle.Panel();
        FabricatingContainer.PanelOverride = LunaWindowStyle.Box(
            Color.FromHex("#122018"),
            LunaWindowStyle.AccentGood);

        LunaWindowStyle.StyleDivider(HeaderDivider);
        LunaWindowStyle.StyleDivider(BodyDivider);
        LunaWindowStyle.StyleHeading(HeaderTitle);
        LunaWindowStyle.StyleSecondary(CaliberHeader);
        LunaWindowStyle.StyleSecondary(QueueHeader);
        LunaWindowStyle.StyleSecondary(MaterialsHeader);
        LunaWindowStyle.StyleSecondary(AutoloaderHeader);
        LunaWindowStyle.StyleMuted(AutoloaderStatus);
        LunaWindowStyle.StyleSecondary(AmountLabel);
        LunaWindowStyle.StyleSecondary(NameLabel);
        LunaWindowStyle.StyleMuted(RecipeCount);
        LunaWindowStyle.StyleProgressGood(ProductionProgress, 8f);

        LunaWindowStyle.ApplyCompactStyle(Shell);
        LunaWindowStyle.StyleHeading(HeaderTitle);

        if (LoopCheckbox.Label != null)
            LoopCheckbox.Label.FontOverride = LunaWindowStyle.FontSmall;
        if (SkipCheckbox.Label != null)
            SkipCheckbox.Label.FontOverride = LunaWindowStyle.FontSmall;
        ResearchServerStatusDot.StyleSelectButton(ServerListButton);
        if (AutoloaderEjectAllButton.Label != null)
            AutoloaderEjectAllButton.Label.FontOverride = LunaWindowStyle.FontSmall;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProductionProgress();
        UpdateAutoloader();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        ServerListButton.Visible = _entityManager.HasComponent<ResearchClientComponent>(Entity);
        ResearchServerStatusDot.Set(ServerStatusDot, false);

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComponent))
            AmountLineEdit.SetText(latheComponent.DefaultProductionAmount.ToString());

        MaterialsList.SetOwner(Entity);
    }

    public void SetResearchServerConnected(bool connected)
    {
        ResearchServerStatusDot.Set(ServerStatusDot, connected);
    }

    public void Refresh()
    {
        RebuildCalibers();
        UpdateDisciplines();
    }

    private void RebuildKindTabs()
    {
        KindTabs.RemoveAllChildren();

        AddKindButton(null, Loc.GetString("lathe-menu-category-all"));
        foreach (var kind in LatheAmmoCategories.KindFilters)
        {
            var name = _prototypeManager.TryIndex(kind, out LatheCategoryPrototype? proto)
                ? Loc.GetString(proto.Name)
                : kind.Id;
            AddKindButton(kind, name);
        }

        RefreshKindPressed();
        LunaWindowStyle.ApplyCompactStyle(KindTabs);
    }

    private void AddKindButton(ProtoId<LatheCategoryPrototype>? kind, string text)
    {
        var button = new Button
        {
            Text = text,
            ToggleMode = true,
            MinHeight = 28,
            StyleClasses = { "ButtonSquare" },
        };
        button.OnPressed += _ =>
        {
            _currentKind = kind;
            RefreshKindPressed();
            PopulateRecipes();
        };
        button.Name = kind?.Id ?? string.Empty;
        KindTabs.AddChild(button);
    }

    private void RefreshKindPressed()
    {
        var selected = _currentKind?.Id ?? string.Empty;
        foreach (var child in KindTabs.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == selected;
        }
    }

    private void RebuildCalibers()
    {
        var present = new HashSet<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipeId in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipeId, out var recipe))
                continue;

            foreach (var category in recipe.Categories)
            {
                if (LatheAmmoCategories.IsCaliber(category))
                    present.Add(category);
            }
        }

        var sorted = present
            .OrderBy(c => _prototypeManager.TryIndex(c, out LatheCategoryPrototype? p)
                ? Loc.GetString(p.Name)
                : c.Id)
            .ToList();

        var same = _calibers.Count == sorted.Count && _calibers.SequenceEqual(sorted);
        if (!same)
        {
            _calibers = sorted;
            CaliberList.RemoveAllChildren();

            foreach (var caliber in _calibers)
            {
                var label = _prototypeManager.TryIndex(caliber, out LatheCategoryPrototype? proto)
                    ? Loc.GetString(proto.Name)
                    : caliber.Id;

                var button = new Button
                {
                    Text = label,
                    ToggleMode = true,
                    HorizontalExpand = true,
                    MinHeight = 28,
                    StyleClasses = { "ButtonSquare" },
                    Name = caliber.Id,
                };
                var captured = caliber;
                button.OnPressed += _ =>
                {
                    _currentCaliber = captured;
                    RefreshCaliberPressed();
                    PopulateRecipes();
                };
                CaliberList.AddChild(button);
            }

            LunaWindowStyle.ApplyCompactStyle(CaliberList);
        }

        if (_calibers.Count == 0)
        {
            _currentCaliber = null;
            return;
        }

        if (_currentCaliber is not { } current || !_calibers.Contains(current))
            _currentCaliber = _calibers[0];

        RefreshCaliberPressed();
    }

    private void RefreshCaliberPressed()
    {
        var selected = _currentCaliber?.Id;
        foreach (var child in CaliberList.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == selected;
        }
    }

    private void UpdateDisciplines()
    {
        EnsureDisciplineMap();
        if (_recipeDisciplineMap == null)
        {
            PopulateRecipes();
            return;
        }

        var present = new HashSet<string>();
        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipe, out var proto))
                continue;
            present.Add(LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, proto.ID));
        }

        var sorted = present
            .OrderBy(id => id == LatheRecipeDiscipline.Basic ? 0 : 1)
            .ThenBy(GetDisciplineDisplayName)
            .ToList();

        var sameTabs = _disciplines != null
            && _disciplines.Count == sorted.Count
            && _disciplines.SequenceEqual(sorted);

        if (!sameTabs)
        {
            _disciplines = sorted;
            RebuildDisciplineTabs();
        }

        if (sorted.Count == 0)
        {
            _currentDiscipline = null;
            PopulateRecipes();
            return;
        }

        if (_currentDiscipline == null || !_disciplines!.Contains(_currentDiscipline))
        {
            _currentDiscipline = _disciplines!.Contains(LatheRecipeDiscipline.Basic)
                ? LatheRecipeDiscipline.Basic
                : _disciplines[0];
        }

        RefreshDisciplineTabPressed();
        PopulateRecipes();
    }

    private void RebuildDisciplineTabs()
    {
        DisciplineTabs.RemoveAllChildren();
        DisciplineTabs.Visible = _disciplines is { Count: > 0 };
        if (_disciplines == null)
            return;

        foreach (var id in _disciplines)
        {
            var button = new Button
            {
                Name = id,
                ToggleMode = true,
                MinSize = new Vector2(28, 28),
                MaxSize = new Vector2(28, 28),
                ToolTip = GetDisciplineDisplayName(id),
                StyleClasses = { "ButtonSquare" },
            };

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2f, 2f),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepCentered,
                SetSize = new Vector2(16, 16),
            };

            if (TryGetDisciplineIcon(id, out var icon))
                texture.Texture = _spriteSystem.Frame0(icon);

            button.AddChild(texture);
            var captured = id;
            button.OnPressed += _ =>
            {
                _currentDiscipline = captured;
                RefreshDisciplineTabPressed();
                PopulateRecipes();
            };
            DisciplineTabs.AddChild(button);
        }

        LunaWindowStyle.ApplyCompactStyle(DisciplineTabs);
    }

    private void RefreshDisciplineTabPressed()
    {
        foreach (var child in DisciplineTabs.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == _currentDiscipline;
        }
    }

    private bool TryGetDisciplineIcon(string id, out SpriteSpecifier icon)
    {
        if (id != LatheRecipeDiscipline.Basic &&
            _prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
        {
            icon = proto.Icon;
            return true;
        }

        icon = new SpriteSpecifier.Rsi(new ResPath("_Lua/Interface/Misc/research_disciplines.rsi"), "all");
        return true;
    }

    private void EnsureDisciplineMap()
    {
        _recipeDisciplineMap ??= LatheRecipeDiscipline.BuildMap(_prototypeManager);
    }

    private string GetDisciplineDisplayName(string id)
    {
        if (id == LatheRecipeDiscipline.Basic)
            return Loc.GetString("lathe-menu-discipline-basic");

        if (_prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
            return Loc.GetString(proto.Name);

        return id;
    }

    public void PopulateRecipes()
    {
        EnsureDisciplineMap();
        var recipesToShow = new List<LatheRecipePrototype>();
        var search = SearchBar.Text.Trim();

        foreach (var recipeId in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipeId, out var proto))
                continue;

            if (_currentDiscipline != null && _recipeDisciplineMap != null)
            {
                var disc = LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, proto.ID);
                if (disc != _currentDiscipline)
                    continue;
            }

            if (_currentCaliber is { } caliber &&
                !proto.Categories.Any(c => c == caliber))
                continue;

            if (_currentKind is { } kind &&
                !LatheAmmoCategories.MatchesKind(proto, kind))
                continue;

            if (search.Length > 0 &&
                !_lathe.GetRecipeName(recipeId).Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            recipesToShow.Add(proto);
        }

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeCount.Text = Loc.GetString("lathe-menu-recipe-count", ("count", recipesToShow.Count));
        RecipeList.Children.Clear();
        _entityManager.TryGetComponent(Entity, out LatheComponent? lathe);

        foreach (var prototype in recipesToShow.OrderBy(_lathe.GetRecipeName))
        {
            var canProduce = _lathe.CanProduce(Entity, prototype, quantity, component: lathe);
            var control = new RecipeControl(_lathe, prototype, () => GenerateTooltipText(prototype), canProduce,
                GetRecipeDisplayControl(prototype));
            control.OnButtonPressed += id =>
            {
                if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
                    amount = 1;
                RecipeQueueAction?.Invoke(id, amount);
            };
            RecipeList.AddChild(control);
        }

        LunaWindowStyle.ApplyCompactStyle(RecipeList);
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype)
    {
        var sb = new StringBuilder();
        var multiplier = _entityManager.GetComponent<LatheComponent>(Entity).FinalMaterialUseMultiplier;

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        foreach (var (id, amount) in prototype.Materials)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.MaterialDiscountScale, multiplier) * quantity;
            var sheetVolume = _materialStorage.GetSheetVolume(proto);
            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float) sheetVolume;
            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;
            var name = Loc.GetString(proto.Name);

            if (missingSheets > 0)
            {
                sb.AppendLine(Loc.GetString("lathe-menu-material-amount-missing",
                    ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name)));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                sb.AppendLine(Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText)));
            }
        }

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void PopulateQueueList(List<LatheRecipeBatch> queue)
    {
        QueueList.DisposeAllChildren();

        var idx = 1;
        foreach (var batch in queue)
        {
            string displayText;
            if (batch.ItemsRequested > 1)
                displayText = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)} ({batch.ItemsPrinted}/{batch.ItemsRequested})";
            else
                displayText = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)}";

            var queued = new QueuedRecipeControl(displayText, idx - 1,
                GetRecipeDisplayControl(_prototypeManager.Index(batch.Recipe)));
            queued.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
            queued.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
            queued.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);
            QueueList.AddChild(queued);
            idx++;
        }

        LunaWindowStyle.ApplyCompactStyle(QueueList);
    }

    public void SetQueueInfo(
        ProtoId<LatheRecipePrototype>? recipeProto,
        TimeSpan? productionStartedAt = null,
        TimeSpan? productionLength = null)
    {
        _productionStartedAt = productionStartedAt;
        _productionLength = productionLength;

        if (recipeProto is not { } recipeId)
        {
            FabricatingContainer.Visible = false;
            ProductionProgress.Value = 0;
            return;
        }

        FabricatingContainer.Visible = true;
        var recipe = _prototypeManager.Index(recipeId);
        FabricatingDisplayContainer.Children.Clear();
        FabricatingDisplayContainer.AddChild(GetRecipeDisplayControl(recipe));
        NameLabel.Text = _lathe.GetRecipeName(recipe);
        UpdateProductionProgress();
    }

    private void UpdateProductionProgress()
    {
        if (_productionStartedAt is not { } started ||
            _productionLength is not { } length ||
            length <= TimeSpan.Zero)
        {
            ProductionProgress.Value = 0f;
            return;
        }

        var elapsed = _timing.CurTime - started;
        ProductionProgress.Value = Math.Clamp((float) (elapsed / length), 0f, 1f);
    }

    public void SetLooping(bool loop) => LoopCheckbox.Pressed = loop;
    public void SetSkipping(bool skip) => SkipCheckbox.Pressed = skip;

    private Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
            return new TextureRect { Texture = _spriteSystem.Frame0(recipe.Icon) };

        if (recipe.Result is { } result)
        {
            var view = new EntityPrototypeView();
            view.SetPrototype(result);
            return view;
        }

        return new Control();
    }

    private void UpdateAutoloader()
    {
        if (!_entityManager.TryGetComponent(Entity, out AmmoTechFabAutoloaderComponent? loader))
        {
            AutoloaderPanel.Visible = false;
            return;
        }

        AutoloaderPanel.Visible = true;

        IReadOnlyList<EntityUid> magazines = Array.Empty<EntityUid>();
        if (_containers.TryGetContainer(Entity, loader.Container, out var container))
            magazines = container.ContainedEntities;

        UpdateAutoloaderStatus(magazines.Count, loader.Starved);

        var structureKey = BuildAutoloaderStructureKey(magazines);
        if (structureKey != _autoloaderStructureKey)
        {
            _autoloaderStructureKey = structureKey;
            RebuildAutoloaderGroups(magazines);
        }

        UpdateAutoloaderLive(magazines);
    }

    private void UpdateAutoloaderStatus(int count, bool starved)
    {
        AutoloaderEjectAllButton.Visible = count > 0;
        if (starved)
        {
            AutoloaderStatus.Text = Loc.GetString("ammo-techfab-autoloader-starved");
            AutoloaderStatus.FontColorOverride = LunaWindowStyle.AccentWarn;
        }
        else
        {
            AutoloaderStatus.Text = Loc.GetString("ammo-techfab-autoloader-count-magazines", ("count", count));
            AutoloaderStatus.FontColorOverride = LunaWindowStyle.TextMuted;
        }
    }

    private string BuildAutoloaderStructureKey(IReadOnlyList<EntityUid> magazines)
    {
        var sb = new StringBuilder(magazines.Count * 24);
        foreach (var uid in magazines)
            sb.Append(uid).Append(':').Append(GetClientGroupKey(uid)).Append('|');
        return sb.ToString();
    }

    private string GetClientGroupKey(EntityUid magazine)
    {
        if (_entityManager.TryGetComponent(magazine, out AmmoTechFabAutoloadComponent? order) &&
            !string.IsNullOrEmpty(order.Group))
            return order.Group;

        return _entityManager.GetComponent<MetaDataComponent>(magazine).EntityPrototype?.ID ?? magazine.ToString();
    }

    private void RebuildAutoloaderGroups(IReadOnlyList<EntityUid> magazines)
    {
        AutoloaderList.RemoveAllChildren();
        _autoloaderRows.Clear();
        _autoloaderGroups.Clear();

        var groups = new List<(string Key, List<EntityUid> Magazines)>();
        var index = new Dictionary<string, int>();

        foreach (var uid in magazines)
        {
            var key = GetClientGroupKey(uid);
            if (!index.TryGetValue(key, out var i))
            {
                i = groups.Count;
                index[key] = i;
                groups.Add((key, new List<EntityUid>()));
            }

            groups[i].Magazines.Add(uid);
        }

        foreach (var (groupKey, groupMags) in groups)
        {
            var group = BuildGroupHeader(groupKey, groupMags);
            _autoloaderGroups.Add(group);
            AutoloaderList.AddChild(group.Root);

            foreach (var uid in groupMags)
            {
                var row = BuildAutoloaderRow(uid);
                _autoloaderRows.Add(uid, row);
                AutoloaderList.AddChild(row.Root);
            }
        }

        LunaWindowStyle.ApplyCompactStyle(AutoloaderList);
    }

    private void UpdateAutoloaderLive(IReadOnlyList<EntityUid> magazines)
    {
        var byGroup = new Dictionary<string, List<EntityUid>>();
        foreach (var uid in magazines)
        {
            var key = GetClientGroupKey(uid);
            if (!byGroup.TryGetValue(key, out var list))
            {
                list = new List<EntityUid>();
                byGroup[key] = list;
            }

            list.Add(uid);
        }

        foreach (var group in _autoloaderGroups)
        {
            if (!byGroup.TryGetValue(group.Key, out var groupMags))
                continue;

            UpdateGroupHeader(group, groupMags);
        }

        foreach (var (uid, row) in _autoloaderRows)
        {
            _entityManager.TryGetComponent(uid, out AmmoTechFabAutoloadComponent? order);
            if (!_guns.TryGetBallisticInfo(uid, out var info) || info.Capacity <= 0)
            {
                row.Count.Text = string.Empty;
                row.Progress.Value = 0f;
                row.Status.Visible = false;
                continue;
            }

            row.Count.Text = Loc.GetString("ammo-techfab-autoloader-rounds",
                ("count", info.Count),
                ("capacity", info.Capacity));
            row.Progress.Value = Math.Clamp(info.Count / (float) info.Capacity, 0f, 1f);

            var status = DescribeAutoloaderStatus(order, info);
            if (status == null)
            {
                row.Status.Visible = false;
                continue;
            }

            row.Status.Visible = true;
            row.Status.Text = status;
            row.Status.FontColorOverride =
                order is { CanLoad: false } || order is { WaitingMaterials: true } ||
                status == Loc.GetString("ammo-techfab-autoloader-mismatch")
                    ? LunaWindowStyle.AccentWarn
                    : LunaWindowStyle.TextMuted;
        }
    }

    private AutoloaderGroup BuildGroupHeader(string groupKey, IReadOnlyList<EntityUid> magazines)
    {
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2,
            Margin = new Thickness(0, 2, 0, 0),
        };

        var title = new Label
        {
            HorizontalExpand = true,
            ClipText = true,
        };
        LunaWindowStyle.StyleSecondary(title);
        root.AddChild(title);

        var select = new OptionButton
        {
            HorizontalExpand = true,
            Filterable = true,
        };
        root.AddChild(select);

        var group = new AutoloaderGroup(groupKey, root, title, select);
        select.OnItemSelected += args =>
        {
            if (args.Id < 0 || args.Id >= group.Choices.Count)
                return;

            select.SelectId(args.Id);
            AutoloaderSelectAction?.Invoke(group.Sample, group.Choices[args.Id].Id);
        };

        UpdateGroupHeader(group, magazines);
        return group;
    }

    private void UpdateGroupHeader(AutoloaderGroup group, IReadOnlyList<EntityUid> magazines)
    {
        ResolveGroupSample(magazines, out var sample, out var order);
        group.Sample = _entityManager.GetNetEntity(sample);

        var name = _entityManager.GetComponent<MetaDataComponent>(sample).EntityName;
        group.Title.Text = Loc.GetString("ammo-techfab-autoloader-group", ("name", name), ("count", magazines.Count));

        var locked = true;
        foreach (var mag in magazines)
        {
            if (_guns.TryGetBallisticInfo(mag, out var info) && info.Count == 0)
            {
                locked = false;
                break;
            }
        }

        group.Select.Disabled = locked || order == null || order.Choices.Count == 0;
        SyncGroupChoices(group, order);

        if (order is { Selected: true, Cartridge: { } selected })
        {
            var index = group.Choices.IndexOf(selected);
            if (index >= 0)
            {
                if (group.Select.SelectedId != index)
                    group.Select.SelectId(index);
                return;
            }
        }

        if (order is not { Selected: true })
            SetOptionPlaceholder(group.Select, Loc.GetString("ammo-techfab-autoloader-pick"));
    }

    private void SyncGroupChoices(AutoloaderGroup group, AmmoTechFabAutoloadComponent? order)
    {
        _choiceScratch.Clear();
        if (order != null)
            _choiceScratch.AddRange(order.Choices);

        var key = string.Join('\0', _choiceScratch);
        if (key == group.ChoicesKey)
            return;
        if (group.Choices.Count > 0 && _choiceScratch.Count < group.Choices.Count)
            return;

        group.ChoicesKey = key;
        group.Choices.Clear();
        group.Choices.AddRange(_choiceScratch);
        group.Select.Clear();

        for (var i = 0; i < group.Choices.Count; i++)
            group.Select.AddItem(PrototypeName(group.Choices[i]), i);
    }

    private void ResolveGroupSample(
        IReadOnlyList<EntityUid> magazines,
        out EntityUid sample,
        out AmmoTechFabAutoloadComponent? order)
    {
        sample = magazines[0];
        order = null;
        foreach (var mag in magazines)
        {
            if (!_entityManager.TryGetComponent(mag, out AmmoTechFabAutoloadComponent? candidate))
                continue;

            if (order == null ||
                candidate.Choices.Count > order.Choices.Count ||
                candidate.Choices.Count == order.Choices.Count && candidate.Selected && !order.Selected)
            {
                sample = mag;
                order = candidate;
            }
        }
    }

    private AutoloaderRow BuildAutoloaderRow(EntityUid uid)
    {
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
            MinHeight = 32,
            Margin = new Thickness(4, 0, 0, 0),
        };

        var icon = new SpriteView
        {
            SetSize = new Vector2(24, 24),
            MouseFilter = MouseFilterMode.Ignore,
            VerticalAlignment = VAlignment.Center,
        };
        icon.SetEntity(uid);
        root.AddChild(icon);

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        var name = new Label
        {
            Text = _entityManager.GetComponent<MetaDataComponent>(uid).EntityName,
            HorizontalExpand = true,
            ClipText = true,
        };
        LunaWindowStyle.StyleValue(name);
        text.AddChild(name);

        var status = new Label { HorizontalExpand = true, Visible = false };
        LunaWindowStyle.StyleMuted(status);
        text.AddChild(status);

        var count = new Label { HorizontalExpand = true };
        LunaWindowStyle.StyleMuted(count);
        text.AddChild(count);

        var progress = new ProgressBar
        {
            MinValue = 0,
            MaxValue = 1,
            HorizontalExpand = true,
            MinHeight = 6,
            MaxHeight = 6,
        };
        LunaWindowStyle.StyleProgressGood(progress, 6f);
        text.AddChild(progress);
        root.AddChild(text);

        var eject = new Button
        {
            Text = Loc.GetString("ammo-techfab-autoloader-eject"),
            MinWidth = 64,
            VerticalAlignment = VAlignment.Center,
        };
        var ejectNet = _entityManager.GetNetEntity(uid);
        eject.OnPressed += _ => AutoloaderEjectAction?.Invoke(ejectNet);
        root.AddChild(eject);

        return new AutoloaderRow(root, status, count, progress);
    }

    private string? DescribeAutoloaderStatus(AmmoTechFabAutoloadComponent? order, BallisticAmmoInfo info)
    {
        if (order == null || !order.Selected || order.Cartridge is not { } cartridge)
            return null;

        if (info.Count > 0 && info.Proto != cartridge)
            return Loc.GetString("ammo-techfab-autoloader-mismatch");

        if (order.WaitingMaterials && info.Count < info.Capacity)
            return Loc.GetString("ammo-techfab-autoloader-waiting");

        if (!order.CanLoad && info.Count < info.Capacity)
            return Loc.GetString("ammo-techfab-autoloader-no-recipe");

        return null;
    }

    private string PrototypeName(EntProtoId id)
    {
        return _prototypeManager.TryIndex(id, out EntityPrototype? proto) ? proto.Name : id.Id;
    }

    private static void SetOptionPlaceholder(OptionButton button, string text)
    {
        if (button.Children.FirstOrDefault() is not BoxContainer box)
            return;

        foreach (var child in box.Children)
        {
            if (child is not Label label)
                continue;

            label.Text = text;
            return;
        }
    }

    private sealed class AutoloaderGroup
    {
        public string Key;
        public Control Root;
        public Label Title;
        public OptionButton Select;
        public NetEntity Sample;
        public string ChoicesKey = string.Empty;
        public readonly List<EntProtoId> Choices = new();

        public AutoloaderGroup(string key, Control root, Label title, OptionButton select)
        {
            Key = key;
            Root = root;
            Title = title;
            Select = select;
        }
    }

    private sealed class AutoloaderRow
    {
        public Control Root;
        public Label Status;
        public Label Count;
        public ProgressBar Progress;

        public AutoloaderRow(Control root, Label status, Label count, ProgressBar progress)
        {
            Root = root;
            Status = status;
            Count = count;
            Progress = progress;
        }
    }
}
