// LuaCorp - This file is licensed under AGPLv3
using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Lua.Research;
using Content.Lua.UIKit.Styles;
using Content.Client._NF.Lathe;
using Content.Client._NF.Lathe.UI;
using Content.Client.Materials;
using Content.Shared._NF.Lathe;
using Content.Shared._NF.Research.Prototypes;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

using Content.Lua.UIKit.Machines;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.Lua.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class LunaBlueprintLatheMenu : LunaWindow, ILunaBlueprintLatheMenu
{
    public BaseWindow Window => this;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly BlueprintLatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<ProtoId<BlueprintPrototype>, int[], int>? RecipeQueueAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;

    public Dictionary<ProtoId<BlueprintPrototype>, int[]> RecipesByBlueprintType { get; set; } = new();

    public EntityUid Entity;

    private List<ProtoId<LatheCategoryPrototype>> _categories = new();
    private ProtoId<LatheCategoryPrototype>? _currentCategory;
    private string? _currentDiscipline;
    private List<string>? _disciplines;
    private Dictionary<string, string>? _recipeDisciplineMap;

    public LunaBlueprintLatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<BlueprintLatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        ApplyLunaInterior();

        SearchBar.OnTextChanged += _ => PopulateRecipes();
        AmountLineEdit.OnTextChanged += _ => PopulateRecipes();
        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();
        DeleteFabricating.AddStyleClass("OpenLeft");
        AllButton.OnPressed += _ => SetAllRecipesPressed(true);
        ClearButton.OnPressed += _ => SetAllRecipesPressed(false);
        PrintButton.OnPressed += _ => QueueBlueprint();
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        CategoryPanel.PanelOverride = LunaWindowStyle.Panel();
        RecipePanel.PanelOverride = LunaWindowStyle.Box(LunaWindowStyle.ContentBg, LunaWindowStyle.PanelBorder);
        QueuePanel.PanelOverride = LunaWindowStyle.Panel();
        MaterialsPanel.PanelOverride = LunaWindowStyle.Panel();
        FabricatingContainer.PanelOverride = LunaWindowStyle.Box(
            Color.FromHex("#122018"),
            LunaWindowStyle.AccentGood);

        LunaWindowStyle.StyleDivider(HeaderDivider);
        LunaWindowStyle.StyleDivider(BodyDivider);
        LunaWindowStyle.StyleHeading(HeaderTitle);
        LunaWindowStyle.StyleSecondary(CategoryHeader);
        LunaWindowStyle.StyleSecondary(QueueHeader);
        LunaWindowStyle.StyleSecondary(MaterialsHeader);
        LunaWindowStyle.StyleSecondary(AmountLabel);
        LunaWindowStyle.StyleSecondary(NameLabel);
        LunaWindowStyle.StyleMuted(RecipeCount);
        LunaWindowStyle.ApplyCompactStyle(Shell);
        LunaWindowStyle.StyleHeading(HeaderTitle);

        ResearchServerStatusDot.StyleSelectButton(ServerListButton);
        if (AllButton.Label != null)
            AllButton.Label.FontOverride = LunaWindowStyle.FontSmall;
        if (ClearButton.Label != null)
            ClearButton.Label.FontOverride = LunaWindowStyle.FontSmall;
        if (PrintButton.Label != null)
            PrintButton.Label.FontOverride = LunaWindowStyle.FontSmall;
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        ServerListButton.Visible = _entityManager.HasComponent<ResearchClientComponent>(Entity);
        ResearchServerStatusDot.Set(ServerStatusDot, false);
        MaterialsList.SetOwner(Entity);
    }

    public void SetResearchServerConnected(bool connected)
    {
        ResearchServerStatusDot.Set(ServerStatusDot, connected);
    }

    protected override void Opened()
    {
        base.Opened();

        if (_entityManager.TryGetComponent<BlueprintLatheComponent>(Entity, out var latheComp))
            AmountLineEdit.SetText(latheComp.DefaultProductionAmount.ToString());
    }

    public void PopulateRecipes()
    {
        RecipeList.Children.Clear();
        EnsureDisciplineMap();
        EnsureBlueprintType();

        if (!_entityManager.TryGetComponent<BlueprintLatheClientStateComponent>(Entity, out var clientLathe))
            return;

        if (clientLathe.CurrentBlueprintType == null
            || !RecipesByBlueprintType.TryGetValue(clientLathe.CurrentBlueprintType.Value, out var recipeBitset)
            || !_lathe.PrintableRecipesByType.TryGetValue(clientLathe.CurrentBlueprintType.Value, out var recipeList))
        {
            RecipeCount.Text = Loc.GetString("lathe-menu-recipe-count", ("count", 0));
            return;
        }

        if (clientLathe.CurrentRecipes == null || clientLathe.CurrentRecipes.Length != recipeBitset.Length)
            clientLathe.CurrentRecipes = new int[recipeBitset.Length];

        var recipesToShow = new List<(LatheRecipePrototype recipe, int index)>();
        var search = SearchBar.Text.Trim();

        for (var i = 0; i < recipeBitset.Length; i++)
        {
            for (var j = 0; j < 32; j++)
            {
                var index = 32 * i + j;
                if (index >= recipeList.Count)
                    break;

                if ((recipeBitset[i] & (1 << j)) == 0
                    || !_prototypeManager.TryIndex(recipeList[index], out var recipe))
                    continue;

                if (_currentDiscipline != null
                    && _currentDiscipline != LatheRecipeDiscipline.Basic
                    && _recipeDisciplineMap != null)
                {
                    var disc = LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, recipe.ID);
                    if (disc != _currentDiscipline)
                        continue;
                }

                if (_currentCategory is { } category)
                {
                    if (recipe.Categories.Count <= 0 || !recipe.Categories.Any(c => c == category))
                        continue;
                }

                if (search.Length != 0 &&
                    !_lathe.GetRecipeName(recipe).Contains(search, StringComparison.OrdinalIgnoreCase))
                    continue;

                recipesToShow.Add((recipe, index));
            }
        }

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeCount.Text = Loc.GetString("lathe-menu-recipe-count", ("count", recipesToShow.Count));

        if (!_entityManager.TryGetComponent(Entity, out BlueprintLatheComponent? lathe))
            return;

        foreach (var item in recipesToShow.OrderBy(x => _lathe.GetRecipeName(x.recipe)))
        {
            var canProduce = _lathe.CanProduceRecipe(Entity, clientLathe.CurrentBlueprintType.Value, item.recipe, quantity, component: lathe);
            var control = new BlueprintRecipeControl(_lathe, item.recipe, () => GenerateTooltipText(item.recipe, lathe), canProduce,
                GetRecipeDisplayControl(item.recipe), item.index);

            var idx = item.index / 32;
            var val = 1 << (item.index % 32);
            if (clientLathe.CurrentRecipes != null
                && clientLathe.CurrentRecipes.Length > idx
                && (clientLathe.CurrentRecipes[idx] & val) != 0)
            {
                control.SetSelected(true);
            }

            control.OnSelectedAction += selected => SetRecipeSelected(item.index, selected);
            RecipeList.AddChild(control);
        }

        LunaWindowStyle.ApplyCompactStyle(RecipeList);
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype, BlueprintLatheComponent component)
    {
        var sb = new StringBuilder();

        foreach (var (id, amount) in component.BlueprintPrintMaterials)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.MaterialDiscountScale, component.FinalMaterialUseMultiplier);
            var sheetVolume = _materialStorage.GetSheetVolume(proto);
            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float) sheetVolume;
            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;
            var name = Loc.GetString(proto.Name);

            if (missingSheets > 0)
            {
                sb.AppendLine(Loc.GetString("lathe-menu-material-amount-missing",
                    ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name)));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                sb.AppendLine(Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText)));
            }
        }

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void UpdateCategories()
    {
        EnsureDisciplineMap();
        RebuildCategoryList();
        UpdateDisciplines();
    }

    private void RebuildCategoryList()
    {
        var present = new HashSet<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipe in EnumerateAvailableRecipes())
        {
            foreach (var category in recipe.Categories)
                present.Add(category);
        }

        var sorted = present
            .OrderBy(p => _prototypeManager.TryIndex(p, out LatheCategoryPrototype? proto)
                ? Loc.GetString(proto.Name)
                : p.Id)
            .ToList();

        var same = _categories.Count == sorted.Count && _categories.SequenceEqual(sorted);
        if (!same)
        {
            _categories = sorted;
            CategoryList.RemoveAllChildren();
            AddCategoryButton(null, Loc.GetString("lathe-menu-category-all"));
            foreach (var category in _categories)
            {
                var label = _prototypeManager.TryIndex(category, out LatheCategoryPrototype? proto)
                    ? Loc.GetString(proto.Name)
                    : category.Id;
                AddCategoryButton(category, label);
            }

            LunaWindowStyle.ApplyCompactStyle(CategoryList);
        }

        if (_currentCategory is { } selected && !_categories.Contains(selected))
            _currentCategory = null;

        RefreshCategoryPressed();
    }

    private void AddCategoryButton(ProtoId<LatheCategoryPrototype>? category, string text)
    {
        var button = new Button
        {
            Text = text,
            ToggleMode = true,
            HorizontalExpand = true,
            MinHeight = 28,
            StyleClasses = { "ButtonSquare" },
            Name = category?.Id ?? string.Empty,
        };
        var captured = category;
        button.OnPressed += _ =>
        {
            _currentCategory = captured;
            RefreshCategoryPressed();
            PopulateRecipes();
        };
        CategoryList.AddChild(button);
    }

    private void RefreshCategoryPressed()
    {
        var selected = _currentCategory?.Id ?? string.Empty;
        foreach (var child in CategoryList.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == selected;
        }
    }

    private void EnsureBlueprintType()
    {
        if (!_entityManager.TryGetComponent<BlueprintLatheClientStateComponent>(Entity, out var clientLathe))
            return;

        ProtoId<BlueprintPrototype>? preferred = null;
        if (_currentDiscipline is { } disc &&
            disc != LatheRecipeDiscipline.Basic &&
            RecipesByBlueprintType.ContainsKey(disc))
        {
            preferred = disc;
        }

        if (preferred == null)
        {
            const string allId = "NFAllResearchable";
            if (RecipesByBlueprintType.ContainsKey(allId))
                preferred = allId;
            else
            {
                foreach (var key in RecipesByBlueprintType.Keys)
                {
                    if (key.Id.Contains("All", StringComparison.OrdinalIgnoreCase))
                    {
                        preferred = key;
                        break;
                    }
                }
            }
        }

        preferred ??= RecipesByBlueprintType.Keys.FirstOrNull();

        if (clientLathe.CurrentBlueprintType == preferred)
            return;

        clientLathe.CurrentBlueprintType = preferred;
        if (preferred is { } type && RecipesByBlueprintType.TryGetValue(type, out var recipes))
            clientLathe.CurrentRecipes = new int[recipes.Length];
        else
            clientLathe.CurrentRecipes = null;
    }

    private IEnumerable<LatheRecipePrototype> EnumerateAvailableRecipes()
    {
        foreach (var (type, bitset) in RecipesByBlueprintType)
        {
            if (!_lathe.PrintableRecipesByType.TryGetValue(type, out var recipeList))
                continue;

            for (var i = 0; i < bitset.Length; i++)
            {
                for (var j = 0; j < 32; j++)
                {
                    var index = 32 * i + j;
                    if (index >= recipeList.Count)
                        break;

                    if ((bitset[i] & (1 << j)) == 0 || !_prototypeManager.TryIndex(recipeList[index], out var recipe))
                        continue;

                    yield return recipe;
                }
            }
        }
    }

    private void UpdateDisciplines()
    {
        EnsureDisciplineMap();
        if (_recipeDisciplineMap == null)
        {
            PopulateRecipes();
            return;
        }

        var present = new HashSet<string>();
        var hasAny = false;
        foreach (var (type, bitset) in RecipesByBlueprintType)
        {
            if (!_lathe.PrintableRecipesByType.TryGetValue(type, out var recipeList))
                continue;

            for (var i = 0; i < bitset.Length; i++)
            {
                for (var j = 0; j < 32; j++)
                {
                    var index = 32 * i + j;
                    if (index >= recipeList.Count)
                        break;

                    if ((bitset[i] & (1 << j)) == 0 || !_prototypeManager.TryIndex(recipeList[index], out var recipe))
                        continue;

                    hasAny = true;
                    present.Add(LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, recipe.ID));
                }
            }
        }
        if (hasAny)
            present.Add(LatheRecipeDiscipline.Basic);

        var sorted = present
            .OrderBy(id => id == LatheRecipeDiscipline.Basic ? 0 : 1)
            .ThenBy(GetDisciplineDisplayName)
            .ToList();

        var sameTabs = _disciplines != null
            && _disciplines.Count == sorted.Count
            && _disciplines.SequenceEqual(sorted);

        if (!sameTabs)
        {
            _disciplines = sorted;
            RebuildDisciplineTabs();
        }

        if (sorted.Count == 0)
        {
            _currentDiscipline = null;
            PopulateRecipes();
            return;
        }

        if (_currentDiscipline == null || !_disciplines!.Contains(_currentDiscipline))
            _currentDiscipline = LatheRecipeDiscipline.Basic;

        RefreshDisciplineTabPressed();
        EnsureBlueprintType();
        PopulateRecipes();
    }

    private void RebuildDisciplineTabs()
    {
        DisciplineTabs.RemoveAllChildren();
        DisciplineTabs.Visible = _disciplines is { Count: > 0 };
        if (_disciplines == null)
            return;

        foreach (var id in _disciplines)
        {
            var button = new Button
            {
                Name = id,
                ToggleMode = true,
                MinSize = new Vector2(28, 28),
                MaxSize = new Vector2(28, 28),
                ToolTip = GetDisciplineDisplayName(id),
                StyleClasses = { "ButtonSquare" },
            };

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2f, 2f),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepCentered,
                SetSize = new Vector2(16, 16),
            };

            if (TryGetDisciplineIcon(id, out var icon))
                texture.Texture = _spriteSystem.Frame0(icon);

            button.AddChild(texture);
            var captured = id;
            button.OnPressed += _ =>
            {
                _currentDiscipline = captured;
                RefreshDisciplineTabPressed();
                EnsureBlueprintType();
                PopulateRecipes();
            };
            DisciplineTabs.AddChild(button);
        }

        LunaWindowStyle.ApplyCompactStyle(DisciplineTabs);
    }

    private void RefreshDisciplineTabPressed()
    {
        foreach (var child in DisciplineTabs.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == _currentDiscipline;
        }
    }

    private bool TryGetDisciplineIcon(string id, out SpriteSpecifier icon)
    {
        if (id != LatheRecipeDiscipline.Basic &&
            _prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
        {
            icon = proto.Icon;
            return true;
        }

        icon = new SpriteSpecifier.Rsi(new ResPath("_Lua/Interface/Misc/research_disciplines.rsi"), "all");
        return true;
    }

    private void EnsureDisciplineMap()
    {
        _recipeDisciplineMap ??= LatheRecipeDiscipline.BuildMap(_prototypeManager);
    }

    private string GetDisciplineDisplayName(string id)
    {
        if (id == LatheRecipeDiscipline.Basic)
            return Loc.GetString("lathe-menu-discipline-basic");

        if (_prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
            return Loc.GetString(proto.Name);

        return id;
    }

    public void PopulateQueueList(List<BlueprintLatheRecipeBatch> queue)
    {
        QueueList.DisposeAllChildren();

        var idx = 1;
        foreach (var batch in queue)
        {
            string displayText;
            if (batch.ItemsRequested > 1)
                displayText = $"{idx}. {GetBlueprintName(batch.BlueprintType)} ({batch.ItemsPrinted}/{batch.ItemsRequested})";
            else
                displayText = $"{idx}. {GetBlueprintName(batch.BlueprintType)}";

            var queued = new QueuedRecipeControl(displayText, idx - 1, GetBlueprintDisplayControl(batch.BlueprintType));
            queued.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
            queued.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
            queued.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);
            QueueList.AddChild(queued);
            idx++;
        }

        LunaWindowStyle.ApplyCompactStyle(QueueList);
    }

    public void SetQueueInfo(ProtoId<BlueprintPrototype>? recipe)
    {
        FabricatingContainer.Visible = recipe != null;
        if (recipe == null)
            return;

        FabricatingDisplayContainer.Children.Clear();
        FabricatingDisplayContainer.AddChild(GetBlueprintDisplayControl(recipe.Value));
        NameLabel.Text = GetBlueprintName(recipe);
    }

    private Control GetBlueprintDisplayControl(ProtoId<BlueprintPrototype> recipe)
    {
        if (_prototypeManager.TryIndex(recipe, out var blueprintPrototype))
        {
            var view = new EntityPrototypeView();
            view.SetPrototype(blueprintPrototype.Blueprint);
            return view;
        }

        return new Control();
    }

    private Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
            return new TextureRect { Texture = _spriteSystem.Frame0(recipe.Icon) };

        if (recipe.Result is { } result)
        {
            var view = new EntityPrototypeView();
            view.SetPrototype(result);
            return view;
        }

        return new Control();
    }

    private string GetBlueprintName(ProtoId<BlueprintPrototype>? recipe)
    {
        if (recipe != null
            && _prototypeManager.TryIndex(recipe, out var blueprintPrototype)
            && _prototypeManager.TryIndex(blueprintPrototype.Blueprint, out var entityPrototype))
            return entityPrototype.Name;

        return Loc.GetString("blueprint-lathe-menu-default-blueprint-name");
    }

    private void QueueBlueprint()
    {
        if (!_entityManager.TryGetComponent<BlueprintLatheClientStateComponent>(Entity, out var clientLathe))
            return;

        if (clientLathe.CurrentBlueprintType == null || clientLathe.CurrentRecipes == null)
            return;

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeQueueAction?.Invoke(clientLathe.CurrentBlueprintType.Value, clientLathe.CurrentRecipes, quantity);
    }

    private void SetAllRecipesPressed(bool pressed)
    {
        foreach (var child in RecipeList.Children)
        {
            if (child is not BlueprintRecipeControl blueprint)
                continue;

            blueprint.SetSelected(pressed);
        }
    }

    private void SetRecipeSelected(int index, bool selected)
    {
        if (!_entityManager.TryGetComponent<BlueprintLatheClientStateComponent>(Entity, out var clientLathe))
            return;

        var intIndex = index / 32;
        var val = 1 << (index % 32);
        if (clientLathe.CurrentRecipes != null && intIndex < clientLathe.CurrentRecipes.Length)
        {
            if (selected)
                clientLathe.CurrentRecipes[intIndex] |= val;
            else
                clientLathe.CurrentRecipes[intIndex] &= ~val;
        }
    }
}
