// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Lua.Research;
using Content.Lua.UIKit.Machines;
using Content.Lua.UIKit.Styles;
using Content.Client._NF.Lathe.UI;
using Content.Client.Lathe;
using Content.Client.Lathe.UI;
using Content.Client.Materials;
using Content.Client.Storage.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class LunaLatheMenu : LunaWindow, ILunaLatheMenu
{
    public BaseWindow Window => this;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;
    private readonly SharedContainerSystem _container;
    private readonly SharedSolutionContainerSystem _solution;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;
    public event Action<bool>? OnLoopCheckboxPressed;
    public event Action<bool>? OnSkipCheckboxPressed;

    public List<ProtoId<LatheRecipePrototype>> Recipes { get; set; } = new();

    public EntityUid Entity;

    private List<ProtoId<LatheCategoryPrototype>> _categories = new();
    private ProtoId<LatheCategoryPrototype>? _currentCategory;
    private string? _currentDiscipline;
    private List<string>? _disciplines;
    private Dictionary<string, string>? _recipeDisciplineMap;

    private TimeSpan? _productionStartedAt;
    private TimeSpan? _productionLength;

    public LunaLatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<LatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();
        _container = _entityManager.System<SharedContainerSystem>();
        _solution = _entityManager.System<SharedSolutionContainerSystem>();

        ApplyLunaInterior();

        SearchBar.OnTextChanged += _ => PopulateRecipes();
        AmountLineEdit.OnTextChanged += _ => PopulateRecipes();
        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();
        DeleteFabricating.AddStyleClass("OpenLeft");
        LoopCheckbox.OnPressed += _ => OnLoopCheckboxPressed?.Invoke(LoopCheckbox.Pressed);
        SkipCheckbox.OnPressed += _ => OnSkipCheckboxPressed?.Invoke(SkipCheckbox.Pressed);
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        CategoryPanel.PanelOverride = LunaWindowStyle.Panel();
        RecipePanel.PanelOverride = LunaWindowStyle.Box(LunaWindowStyle.ContentBg, LunaWindowStyle.PanelBorder);
        QueuePanel.PanelOverride = LunaWindowStyle.Panel();
        MaterialsPanel.PanelOverride = LunaWindowStyle.Panel();
        FabricatingContainer.PanelOverride = LunaWindowStyle.Box(
            Color.FromHex("#122018"),
            LunaWindowStyle.AccentGood);

        LunaWindowStyle.StyleDivider(HeaderDivider);
        LunaWindowStyle.StyleDivider(BodyDivider);
        LunaWindowStyle.StyleHeading(HeaderTitle);
        LunaWindowStyle.StyleSecondary(CategoryHeader);
        LunaWindowStyle.StyleSecondary(QueueHeader);
        LunaWindowStyle.StyleSecondary(MaterialsHeader);
        LunaWindowStyle.StyleSecondary(AmountLabel);
        LunaWindowStyle.StyleSecondary(NameLabel);
        LunaWindowStyle.StyleMuted(RecipeCount);
        LunaWindowStyle.StyleProgressGood(ProductionProgress, 8f);

        LunaWindowStyle.ApplyCompactStyle(Shell);
        LunaWindowStyle.StyleHeading(HeaderTitle);

        if (LoopCheckbox.Label != null)
            LoopCheckbox.Label.FontOverride = LunaWindowStyle.FontSmall;
        if (SkipCheckbox.Label != null)
            SkipCheckbox.Label.FontOverride = LunaWindowStyle.FontSmall;
        ResearchServerStatusDot.StyleSelectButton(ServerListButton);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProductionProgress();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        ServerListButton.Visible = _entityManager.HasComponent<ResearchClientComponent>(Entity);
        ResearchServerStatusDot.Set(ServerStatusDot, false);

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComponent))
            AmountLineEdit.SetText(latheComponent.DefaultProductionAmount.ToString());

        MaterialsList.SetOwner(Entity);
    }

    public void SetResearchServerConnected(bool connected)
    {
        ResearchServerStatusDot.Set(ServerStatusDot, connected);
    }

    public void Refresh()
    {
        UpdateCategories();
        UpdateDisciplines();
    }

    public void PopulateRecipes()
    {
        EnsureDisciplineMap();
        var recipesToShow = new List<LatheRecipePrototype>();
        var search = SearchBar.Text.Trim();

        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipe, out var proto))
                continue;

            if (_currentDiscipline != null && _recipeDisciplineMap != null)
            {
                var disc = LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, proto.ID);
                if (disc != _currentDiscipline)
                    continue;
            }

            if (_currentCategory is { } category)
            {
                if (proto.Categories.Count <= 0)
                    continue;

                if (!proto.Categories.Any(c => c == category))
                    continue;
            }

            if (search.Length > 0 &&
                !_lathe.GetRecipeName(recipe).Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            recipesToShow.Add(proto);
        }

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeCount.Text = Loc.GetString("lathe-menu-recipe-count", ("count", recipesToShow.Count));
        RecipeList.Children.Clear();
        _entityManager.TryGetComponent(Entity, out LatheComponent? lathe);

        foreach (var prototype in recipesToShow.OrderBy(_lathe.GetRecipeName))
        {
            var canProduce = _lathe.CanProduce(Entity, prototype, quantity, component: lathe);
            var control = new RecipeControl(_lathe, prototype, () => GenerateTooltipText(prototype), canProduce,
                GetRecipeDisplayControl(prototype));
            control.OnButtonPressed += id =>
            {
                if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
                    amount = 1;
                RecipeQueueAction?.Invoke(id, amount);
            };
            RecipeList.AddChild(control);
        }

        LunaWindowStyle.ApplyCompactStyle(RecipeList);
    }

    private void UpdateCategories()
    {
        var currentCategories = new List<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipeId in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipeId, out var recipe) || recipe.Categories.Count <= 0)
                continue;

            foreach (var category in recipe.Categories)
            {
                if (!currentCategories.Contains(category))
                    currentCategories.Add(category);
            }
        }

        var sorted = currentCategories
            .OrderBy(p => _prototypeManager.TryIndex(p, out LatheCategoryPrototype? proto)
                ? Loc.GetString(proto.Name)
                : p.Id)
            .ToList();

        var same = _categories.Count == sorted.Count && _categories.SequenceEqual(sorted);
        if (!same)
        {
            _categories = sorted;
            CategoryList.RemoveAllChildren();

            AddCategoryButton(null, Loc.GetString("lathe-menu-category-all"));
            foreach (var category in _categories)
            {
                var label = _prototypeManager.TryIndex(category, out LatheCategoryPrototype? proto)
                    ? Loc.GetString(proto.Name)
                    : category.Id;
                AddCategoryButton(category, label);
            }

            LunaWindowStyle.ApplyCompactStyle(CategoryList);
        }

        if (_currentCategory is { } selected && !_categories.Contains(selected))
            _currentCategory = null;

        RefreshCategoryPressed();
    }

    private void AddCategoryButton(ProtoId<LatheCategoryPrototype>? category, string text)
    {
        var button = new Button
        {
            Text = text,
            ToggleMode = true,
            HorizontalExpand = true,
            MinHeight = 28,
            StyleClasses = { "ButtonSquare" },
            Name = category?.Id ?? string.Empty,
        };
        var captured = category;
        button.OnPressed += _ =>
        {
            _currentCategory = captured;
            RefreshCategoryPressed();
            PopulateRecipes();
        };
        CategoryList.AddChild(button);
    }

    private void RefreshCategoryPressed()
    {
        var selected = _currentCategory?.Id ?? string.Empty;
        foreach (var child in CategoryList.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == selected;
        }
    }

    private void UpdateDisciplines()
    {
        EnsureDisciplineMap();
        if (_recipeDisciplineMap == null)
        {
            PopulateRecipes();
            return;
        }

        var present = new HashSet<string>();
        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipe, out var proto))
                continue;
            present.Add(LatheRecipeDiscipline.GetDiscipline(_recipeDisciplineMap, proto.ID));
        }

        var sorted = present
            .OrderBy(id => id == LatheRecipeDiscipline.Basic ? 0 : 1)
            .ThenBy(GetDisciplineDisplayName)
            .ToList();

        var sameTabs = _disciplines != null
            && _disciplines.Count == sorted.Count
            && _disciplines.SequenceEqual(sorted);

        if (!sameTabs)
        {
            _disciplines = sorted;
            RebuildDisciplineTabs();
        }

        if (sorted.Count == 0)
        {
            _currentDiscipline = null;
            PopulateRecipes();
            return;
        }

        if (_currentDiscipline == null || !_disciplines!.Contains(_currentDiscipline))
        {
            _currentDiscipline = _disciplines!.Contains(LatheRecipeDiscipline.Basic)
                ? LatheRecipeDiscipline.Basic
                : _disciplines[0];
        }

        RefreshDisciplineTabPressed();
        PopulateRecipes();
    }

    private void RebuildDisciplineTabs()
    {
        DisciplineTabs.RemoveAllChildren();
        DisciplineTabs.Visible = _disciplines is { Count: > 0 };
        if (_disciplines == null)
            return;

        foreach (var id in _disciplines)
        {
            var button = new Button
            {
                Name = id,
                ToggleMode = true,
                MinSize = new Vector2(28, 28),
                MaxSize = new Vector2(28, 28),
                ToolTip = GetDisciplineDisplayName(id),
                StyleClasses = { "ButtonSquare" },
            };

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2f, 2f),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepCentered,
                SetSize = new Vector2(16, 16),
            };

            if (TryGetDisciplineIcon(id, out var icon))
                texture.Texture = _spriteSystem.Frame0(icon);

            button.AddChild(texture);
            var captured = id;
            button.OnPressed += _ =>
            {
                _currentDiscipline = captured;
                RefreshDisciplineTabPressed();
                PopulateRecipes();
            };
            DisciplineTabs.AddChild(button);
        }

        LunaWindowStyle.ApplyCompactStyle(DisciplineTabs);
    }

    private void RefreshDisciplineTabPressed()
    {
        foreach (var child in DisciplineTabs.Children)
        {
            if (child is not Button button)
                continue;
            button.Pressed = button.Name == _currentDiscipline;
        }
    }

    private bool TryGetDisciplineIcon(string id, out SpriteSpecifier icon)
    {
        if (id != LatheRecipeDiscipline.Basic &&
            _prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
        {
            icon = proto.Icon;
            return true;
        }

        icon = new SpriteSpecifier.Rsi(new ResPath("_Lua/Interface/Misc/research_disciplines.rsi"), "all");
        return true;
    }

    private void EnsureDisciplineMap()
    {
        _recipeDisciplineMap ??= LatheRecipeDiscipline.BuildMap(_prototypeManager);
    }

    private string GetDisciplineDisplayName(string id)
    {
        if (id == LatheRecipeDiscipline.Basic)
            return Loc.GetString("lathe-menu-discipline-basic");

        if (_prototypeManager.TryIndex<TechDisciplinePrototype>(id, out var proto))
            return Loc.GetString(proto.Name);

        return id;
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype)
    {
        var sb = new StringBuilder();
        var multiplier = _entityManager.GetComponent<LatheComponent>(Entity).FinalMaterialUseMultiplier;

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        foreach (var (id, amount) in prototype.Materials)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.MaterialDiscountScale, multiplier) * quantity;
            var sheetVolume = _materialStorage.GetSheetVolume(proto);
            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float) sheetVolume;
            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;
            var name = Loc.GetString(proto.Name);

            if (missingSheets > 0)
            {
                sb.AppendLine(Loc.GetString("lathe-menu-material-amount-missing",
                    ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name)));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                sb.AppendLine(Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText)));
            }
        }

        foreach (var (id, amount) in prototype.Entities)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var name = Loc.GetString(proto.Name);
            var needed = amount * quantity;
            var currentAmount = GetEntityCount(id);
            var missingAmount = needed - currentAmount;

            if (missingAmount > 0)
            {
                sb.AppendLine(Loc.GetString("lathe-menu-entity-amount-missing",
                    ("amount", needed), ("missingAmount", missingAmount), ("unit", ""), ("material", name)));
            }
            else
            {
                sb.AppendLine(Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", needed)));
            }
        }

        foreach (var (id, amount) in prototype.Reagents)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var name = Loc.GetString(proto.LocalizedName);
            var needed = amount * quantity;
            var currentAmount = GetReagentAmount(id);
            var missingAmount = needed - currentAmount;

            if (missingAmount > 0)
            {
                sb.AppendLine(Loc.GetString("lathe-menu-reagent-amount-missing",
                    ("amount", needed), ("missingAmount", missingAmount), ("unit", "u"), ("material", name)));
            }
            else
            {
                sb.AppendLine(Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", needed)));
            }
        }

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void PopulateQueueList(List<LatheRecipeBatch> queue)
    {
        QueueList.DisposeAllChildren();

        var idx = 1;
        foreach (var batch in queue)
        {
            string displayText;
            if (batch.ItemsRequested > 1)
                displayText = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)} ({batch.ItemsPrinted}/{batch.ItemsRequested})";
            else
                displayText = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)}";

            var queued = new QueuedRecipeControl(displayText, idx - 1,
                GetRecipeDisplayControl(_prototypeManager.Index(batch.Recipe)));
            queued.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
            queued.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
            queued.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);
            QueueList.AddChild(queued);
            idx++;
        }

        LunaWindowStyle.ApplyCompactStyle(QueueList);
    }

    public void SetQueueInfo(
        ProtoId<LatheRecipePrototype>? recipeProto,
        TimeSpan? productionStartedAt = null,
        TimeSpan? productionLength = null)
    {
        _productionStartedAt = productionStartedAt;
        _productionLength = productionLength;

        if (recipeProto is not { } recipeId)
        {
            FabricatingContainer.Visible = false;
            ProductionProgress.Value = 0;
            return;
        }

        FabricatingContainer.Visible = true;
        var recipe = _prototypeManager.Index(recipeId);
        FabricatingDisplayContainer.Children.Clear();
        FabricatingDisplayContainer.AddChild(GetRecipeDisplayControl(recipe));
        NameLabel.Text = _lathe.GetRecipeName(recipe);
        UpdateProductionProgress();
    }

    private void UpdateProductionProgress()
    {
        if (_productionStartedAt is not { } started ||
            _productionLength is not { } length ||
            length <= TimeSpan.Zero)
        {
            ProductionProgress.Value = 0f;
            return;
        }

        var elapsed = _timing.CurTime - started;
        ProductionProgress.Value = Math.Clamp((float) (elapsed / length), 0f, 1f);
    }

    public void SetLooping(bool loop) => LoopCheckbox.Pressed = loop;
    public void SetSkipping(bool skip) => SkipCheckbox.Pressed = skip;

    private Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
            return new TextureRect { Texture = _spriteSystem.Frame0(recipe.Icon) };

        if (recipe.Result is { } result)
        {
            var view = new EntityPrototypeView();
            view.SetPrototype(result);
            return view;
        }

        return new Control();
    }

    private int GetEntityCount(EntProtoId recipeEnt)
    {
        var count = 0;
        if (!_entityManager.TryGetComponent<EntityStorageComponent>(Entity, out var storage))
            return count;

        foreach (var containedEnt in storage.Contents.ContainedEntities)
        {
            if (_entityManager.GetComponent<MetaDataComponent>(containedEnt).EntityPrototype is not { } proto
                || proto.ID != recipeEnt)
                continue;

            if (_entityManager.TryGetComponent<StackComponent>(containedEnt, out var stack))
                count += stack.Count;
            else
                count += 1;
        }

        return count;
    }

    private FixedPoint2 GetReagentAmount(ProtoId<ReagentPrototype> recipeReag)
    {
        if (!_entityManager.TryGetComponent<LatheComponent>(Entity, out var lathe) ||
            lathe.ReagentOutputSlotId is not { } slotId)
            return 0;

        if (!_container.TryGetContainer(Entity, slotId, out var container) ||
            container.ContainedEntities.Count == 0)
            return 0;

        if (!_solution.TryGetDrainableSolution(container.ContainedEntities[0], out _, out var solution))
            return 0;

        return solution.GetReagentQuantity(new ReagentId(recipeReag, []));
    }
}
