using Content.Client.UserInterface.Controls;
using Content.Shared.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DiskConsoleMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action<int>? OnPrintButtonPressed;

    public DiskConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
    }

    public void Update(DiskConsoleBoundUserInterfaceState state)
    {
        TotalLabel.Text = Loc.GetString("tech-disk-ui-total-label", ("amount", state.ServerPoints));
        HintLabel.Text = state.Printing
            ? Loc.GetString("tech-disk-ui-printing")
            : Loc.GetString("tech-disk-ui-select-amount");

        OptionsContainer.RemoveAllChildren();
        foreach (var option in state.Options)
        {
            var button = new Button
            {
                Text = Loc.GetString("tech-disk-ui-print-points-button", ("amount", option.Points)),
                Disabled = !option.CanPrint,
                HorizontalExpand = true,
                MinHeight = 32,
            };
            var points = option.Points;
            button.OnPressed += _ => OnPrintButtonPressed?.Invoke(points);
            OptionsContainer.AddChild(button);
        }
    }
}
