using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Research.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ResearchClientServerSelectionMenu : DefaultWindow
    {
        private static readonly Color OnlineColor = Color.FromHex("#3DDC3D");
        private static readonly Color OfflineColor = Color.FromHex("#666666");
        private static readonly Color RowSelectedBg = Color.FromHex("#3A3A3E");
        private static readonly Color RowNormalBg = Color.FromHex("#1B1B1E");

        private readonly StyleBoxFlat _statusDotStyle = new();

        private int _serverCount;
        private string[] _serverNames = Array.Empty<string>();
        private int[] _serverIds = Array.Empty<int>();
        private int _selectedServerId = -1;

        public event Action<int>? OnServerSelected;
        public event Action? OnServerDeselected;

        public ResearchClientServerSelectionMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StatusDot.PanelOverride = _statusDotStyle;
        }

        public void Populate(int serverCount, string[] serverNames, int[] serverIds, int selectedServerId)
        {
            _serverCount = serverCount;
            _serverNames = serverNames;
            _serverIds = serverIds;
            _selectedServerId = selectedServerId;

            ServerList.RemoveAllChildren();

            var selectedName = string.Empty;
            var hasSelection = false;

            for (var i = 0; i < _serverCount; i++)
            {
                var id = _serverIds[i];
                var name = _serverNames[i];
                var selected = id == _selectedServerId;

                if (selected)
                {
                    hasSelection = true;
                    selectedName = name;
                }

                ServerList.AddChild(MakeServerRow(id, name, selected));
            }

            UpdateStatusBar(hasSelection, selectedName);
        }

        private Control MakeServerRow(int id, string serverName, bool selected)
        {
            var rowBg = new StyleBoxFlat
            {
                BackgroundColor = selected ? RowSelectedBg : RowNormalBg,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };
            var button = new ContainerButton
            {
                ToggleMode = false,
                Mode = BaseButton.ActionMode.Press,
                HorizontalExpand = true,
                MinHeight = 28,
                StyleBoxOverride = rowBg,
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                MouseFilter = MouseFilterMode.Ignore,
            };

            var dotStyle = new StyleBoxFlat
            {
                BackgroundColor = selected ? OnlineColor : OfflineColor,
            };
            var dot = new PanelContainer
            {
                PanelOverride = dotStyle,
                SetSize = new Vector2(10, 10),
                MinSize = new Vector2(10, 10),
                MaxSize = new Vector2(10, 10),
                Margin = new Thickness(0, 1, 0, 0),
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore,
            };

            var label = new Label
            {
                Text = selected
                    ? Loc.GetString("research-client-server-selection-menu-server-entry-online",
                        ("id", id), ("serverName", serverName))
                    : Loc.GetString("research-client-server-selection-menu-server-entry-text",
                        ("id", id), ("serverName", serverName)),
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                ClipText = true,
                MouseFilter = MouseFilterMode.Ignore,
            };
            if (selected)
                label.FontColorOverride = OnlineColor;

            row.AddChild(dot);
            row.AddChild(label);
            button.AddChild(row);

            var capturedId = id;
            var wasSelected = selected;
            button.OnPressed += _ =>
            {
                if (wasSelected)
                {
                    OnServerDeselected?.Invoke();
                    return;
                }

                OnServerSelected?.Invoke(capturedId);
            };

            return button;
        }

        private void UpdateStatusBar(bool online, string serverName)
        {
            _statusDotStyle.BackgroundColor = online ? OnlineColor : OfflineColor;
            StatusLabel.Text = online
                ? Loc.GetString("research-client-server-selection-menu-status-online", ("serverName", serverName))
                : Loc.GetString("research-client-server-selection-menu-status-offline");
            StatusLabel.FontColorOverride = online ? OnlineColor : Color.FromHex("#AAAAAA");
        }
    }
}
