<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\Content.Lua.Server\</OutputPath>
    <LuaModuleHostOutputPath>..\bin\Content.Server\</LuaModuleHostOutputPath>
    <WarningsAsErrors>RA0032;nullable</WarningsAsErrors>
    <NoWarn>1998</NoWarn>
  </PropertyGroup>
  <Import Project="../MSBuild/Content.props" />
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
    <PackageReference Include="SharpZstd.Interop" PrivateAssets="compile" ExcludeAssets="native" />
  </ItemGroup>

  <Import Project="..\RobustToolbox\Imports\Lidgren.props" />
  <Import Project="..\RobustToolbox\Imports\Server.props" />
  <Import Project="..\RobustToolbox\Imports\Shared.props" />

  <ItemGroup>
    <ProjectReference Include="..\Content.Server\Content.Server.csproj" />
    <ProjectReference Include="..\Content.Lua.Shared\Content.Lua.Shared.csproj" />
  </ItemGroup>

  <Import Project="..\RobustToolbox\MSBuild\Robust.Properties.targets" />
  <Import Project="..\MSBuild\LuaModule.targets" />
</Project>
