// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using System.Linq;
using Content.Lua.UIKit.Machines;
using Content.Lua.UIKit.Styles;
using Content.Client.Lua.VendingMachines.UI;
using Content.Shared._NF.Bank;
using Content.Shared.Cargo.Components;
using Content.Shared.Chemistry.Components.SolutionManager;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.IdentityManagement;
using Content.Shared.Stacks;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;
using static System.StringComparison;

namespace Content.Client.Lua.VendingMachines;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingMachineWindow : LunaWindow, ILuaVendingMachineWindow
{
    public BaseWindow Window => this;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;

    private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];
    private readonly Dictionary<EntProtoId, LuaVendingEntry> _entries = new();
    private bool _enabled;

    public event Action<InventoryType, string>? OnItemSelected;

    public LuaVendingMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();
        ApplyLunaInterior();
        Search.OnTextChanged += OnSearchChanged;
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        LunaWindowStyle.StyleDivider(HeaderDivider);
        LunaWindowStyle.StyleDivider(FooterDivider);
        LunaWindowStyle.StyleMuted(BalanceCaption);
        LunaWindowStyle.StyleValue(BalanceLabel);
        LunaWindowStyle.StyleMuted(CashSlotCaption);
        LunaWindowStyle.StyleValue(CashSlotLabel);
        LunaWindowStyle.StyleSecondary(SearchLabel);
        LunaWindowStyle.StyleMuted(EmptyLabel);
        LunaWindowStyle.StyleFooter(FlavorLeft);
        LunaWindowStyle.StyleFooter(FlavorRight);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;
        foreach (var entity in _dummies.Values)
            _entityManager.QueueDeleteEntity(entity);
        _dummies.Clear();
    }

    public void Populate(List<VendingMachineInventoryEntry> inventory, bool enabled, float priceModifier, int balance, int? cashSlotBalance)
    {
        _enabled = enabled;
        _entries.Clear();
        Sections.DisposeAllChildren();
        UpdateBalance(balance);
        UpdateCashSlotBalance(cashSlotBalance);
        if (inventory.Count == 0)
        {
            Search.Visible = false;
            SearchLabel.Visible = false;
            CatalogScroll.Visible = false;
            EmptyLabel.Visible = true;
            return;
        }
        Search.Visible = true;
        SearchLabel.Visible = true;
        CatalogScroll.Visible = true;
        EmptyLabel.Visible = false;
        var section = new LuaVendingSection();
        section.SetHeaderVisible(false);
        foreach (var entry in inventory)
            TryAddEntry(section, entry, priceModifier);
        if (section.Entries.ChildCount > 0)
            Sections.AddChild(section);
        ApplySearchFilter(Search.Text);
    }

    public void UpdateBalance(int balance)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(balance);
    }

    public void UpdateCashSlotBalance(int? balance)
    {
        CashSlotControls.Visible = balance != null;
        if (balance != null)
            CashSlotLabel.Text = BankSystemExtensions.ToSpesoString(balance.Value);
    }

    public void UpdateAmounts(List<VendingMachineInventoryEntry> cachedInventory, float priceModifier, bool enabled)
    {
        _enabled = enabled;
        foreach (var proto in _dummies.Keys)
        {
            if (!_entries.TryGetValue(proto, out var uiEntry))
                continue;
            if (!cachedInventory.TryFirstOrDefault(item => item.ID == proto, out var entry))
                continue;
            var dummy = _dummies[proto];
            var cost = 20;
            if (_entityManager.TryGetComponent(dummy, out MetaDataComponent? meta) && meta.EntityPrototype != null)
                cost = GetPrototypePrice(meta.EntityPrototype, priceModifier);
            ApplyEntryState(uiEntry, entry.Amount, cost);
        }
    }

    private LuaVendingEntry CreateEntry(EntityPrototype prototype, string itemName, int cost, VendingMachineInventoryEntry entry)
    {
        var uiEntry = new LuaVendingEntry();
        uiEntry.Texture.Textures = _entityManager.System<SpriteSystem>().GetPrototypeTextures(prototype)
            .Select(texture => texture.Default)
            .ToList();
        if (prototype.TryGetComponent("Sprite", out SpriteComponent? sprite) && sprite.AllLayers.FirstOrDefault() is { } layer)
            uiEntry.Texture.Modulate = layer.Color;
        uiEntry.Panel.Title.Text = itemName;
        ApplySectionColors(uiEntry, entry.Type);
        ApplyEntryState(uiEntry, entry.Amount, cost);
        var msg = new FormattedMessage();
        msg.AddText(itemName);
        msg.PushNewline();
        if (!string.IsNullOrWhiteSpace(prototype.Description))
            msg.AddText(prototype.Description);
        var tooltip = new Tooltip();
        tooltip.SetMessage(msg);
        uiEntry.TooltipDelay = 0;
        uiEntry.TooltipSupplier = _ => tooltip;
        var type = entry.Type;
        var id = entry.ID;
        uiEntry.Panel.Button.OnPressed += _ => OnItemSelected?.Invoke(type, id);
        return uiEntry;
    }

    private void ApplyEntryState(LuaVendingEntry uiEntry, uint amount, int cost)
    {
        uiEntry.Price.Text = BankSystemExtensions.ToSpesoString(cost);
        uiEntry.Amount.Text = amount == uint.MaxValue ? string.Empty : amount.ToString();
        uiEntry.SetDisabled(!_enabled || amount == 0);
    }

    private static void ApplySectionColors(LuaVendingEntry uiEntry, InventoryType type)
    {
        switch (type)
        {
            case InventoryType.Emagged:
                uiEntry.Panel.BorderColor = LunaWindowStyle.AccentBad;
                uiEntry.Panel.HoveredColor = LunaWindowStyle.AccentBad;
                break;
            case InventoryType.Contraband:
                uiEntry.Panel.BorderColor = LunaWindowStyle.AccentWarn;
                uiEntry.Panel.HoveredColor = LunaWindowStyle.AccentWarn;
                break;
            default:
                uiEntry.Panel.BorderColor = LuaVendingPanel.DefaultBorderColor;
                uiEntry.Panel.HoveredColor = LuaVendingPanel.DefaultHoveredColor;
                break;
        }
        uiEntry.Panel.Color = LuaVendingPanel.DefaultColor;
        uiEntry.Panel.UpdateColor();
    }

    private void TryAddEntry(LuaVendingSection section, VendingMachineInventoryEntry entry, float priceModifier)
    {
        if (!_prototypeManager.TryIndex(entry.ID, out var prototype))
            return;
        if (!_dummies.TryGetValue(entry.ID, out var dummy))
        {
            dummy = _entityManager.Spawn(entry.ID);
            _dummies.Add(entry.ID, dummy);
        }
        var cost = GetPrototypePrice(prototype, priceModifier);
        var itemName = Identity.Name(dummy, _entityManager);
        var uiEntry = CreateEntry(prototype, itemName, cost, entry);
        _entries[entry.ID] = uiEntry;
        section.Entries.AddChild(uiEntry);
    }

    private void OnSearchChanged(LineEditEventArgs args)
    {
        ApplySearchFilter(args.Text);
    }

    private void ApplySearchFilter(string? text)
    {
        foreach (var sectionControl in Sections.Children)
        {
            if (sectionControl is not LuaVendingSection section)
                continue;
            var any = false;
            foreach (var entryControl in section.Entries.Children)
            {
                if (entryControl is not LuaVendingEntry entry)
                    continue;
                entry.Visible = string.IsNullOrWhiteSpace(text) ||
                    (entry.Panel.Title.Text?.Contains(text, OrdinalIgnoreCase) ?? false);
                if (entry.Visible)
                    any = true;
            }
            section.Visible = any;
        }
    }

    private int GetPrototypePrice(EntityPrototype prototype, float priceModifier)
    {
        double vendPrice = 0;
        if (prototype.TryGetComponent<StaticPriceComponent>(out var staticComp, _componentFactory) && staticComp.VendPrice > 0.0)
            vendPrice += staticComp.VendPrice;
        else if (prototype.TryGetComponent<StackPriceComponent>(out var stackComp, _componentFactory) && stackComp.VendPrice > 0.0)
            vendPrice += stackComp.VendPrice;
        if (vendPrice > 0.0)
            return (int) vendPrice;
        double cost = 20;
        if (prototype.TryGetComponent<StaticPriceComponent>(out var priceComponent, _componentFactory))
        {
            if (priceComponent.Price != 0)
                cost = priceComponent.Price;
            else if (prototype.TryGetComponent<StackPriceComponent>(out var stackPrice, _componentFactory)
                     && prototype.TryGetComponent<StackComponent>(out var stack, _componentFactory))
                cost = stackPrice.Price * stack.Count;
        }
        cost *= priceModifier;
        if (prototype.TryGetComponent<SolutionContainerManagerComponent>(out var priceSolutions, _componentFactory)
            && priceSolutions.Solutions != null)
        {
            foreach (var solution in priceSolutions.Solutions.Values)
            {
                foreach (var (reagent, quantity) in solution.Contents)
                {
                    if (!_prototypeManager.TryIndex<ReagentPrototype>(reagent.Prototype, out var reagentProto))
                        continue;
                    cost += quantity.Float() * reagentProto.PricePerUnit * priceModifier;
                }
            }
        }
        return (int) cost;
    }
}
