using System.Globalization;
using System.Linq;
using System.Text;
using Content.Lua.Shared.Administration.FactionWar;
using Content.Lua.Shared.Company;
using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lua.Administration.UI.AdminFactionWar;

[GenerateTypedNameReferences]
public sealed partial class AdminFactionWarWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action? RefreshPressed;
    public event Action<string, string, string>? DeclareWarPressed;
    public event Action<int>? EndWarPressed;

    private readonly List<CompanyPrototype> _companies = new();
    private readonly List<CompanyWarOverview> _wars = new();
    private string? _selectedAggressorId;
    private string? _selectedDefenderId;
    private int? _selectedWarId;
    private bool _suppressDropdownEvents;

    public AdminFactionWarWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateCompanies();
        ActiveWarsList.OnItemSelected += OnWarSelected;
        AggressorDropdown.OnItemSelected += args => OnCompanySelected(args, true);
        DefenderDropdown.OnItemSelected += args => OnCompanySelected(args, false);
        DeclareButton.OnPressed += _ =>
        {
            if (_selectedAggressorId == null || _selectedDefenderId == null)
                return;

            DeclareWarPressed?.Invoke(_selectedAggressorId, _selectedDefenderId, AnnouncementInput.Text);
        };
        RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();
        EndWarButton.OnPressed += _ =>
        {
            if (_selectedWarId == null)
                return;

            EndWarPressed?.Invoke(_selectedWarId.Value);
        };

        SetStatusText(Loc.GetString("admin-faction-war-status-idle"));
        SelectedWarLabel.Text = Loc.GetString("admin-faction-war-select-war");
        UpdateButtons();
    }

    public void UpdateState(AdminFactionWarEuiState state)
    {
        var previousSelectedWarId = _selectedWarId;
        _wars.Clear();
        _wars.AddRange(state.ActiveWars);

        ActiveWarsList.Clear();
        _selectedWarId = null;

        for (var i = 0; i < _wars.Count; i++)
        {
            var war = _wars[i];
            var title = $"{war.AggressorName} -> {war.DefenderName}";
            ActiveWarsList.AddItem(title, metadata: war.WarId);

            if (previousSelectedWarId != war.WarId)
                continue;

            ActiveWarsList[i].Selected = true;
            _selectedWarId = war.WarId;
        }

        if (_selectedWarId != null)
            UpdateSelectedWarDetails();
        else
            ClearSelectedWarDetails();

        SetStatusText(string.IsNullOrWhiteSpace(state.StatusText)
            ? Loc.GetString("admin-faction-war-status-idle")
            : state.StatusText);
        UpdateButtons();
    }

    private void PopulateCompanies()
    {
        _companies.Clear();
        foreach (var company in _prototypes.EnumeratePrototypes<CompanyPrototype>())
        {
            if (company.ID == "None")
                continue;

            _companies.Add(company);
        }

        _companies.Sort((left, right) =>
            StringComparer.OrdinalIgnoreCase.Compare(left.Name, right.Name));

        _suppressDropdownEvents = true;
        AggressorDropdown.Clear();
        DefenderDropdown.Clear();

        for (var index = 0; index < _companies.Count; index++)
        {
            var company = _companies[index];
            var label = $"{company.Name} ({company.ID})";
            AggressorDropdown.AddItem(label, index);
            DefenderDropdown.AddItem(label, index);
        }

        if (_companies.Count > 0)
        {
            AggressorDropdown.SelectId(0);
            _selectedAggressorId = _companies[0].ID;
        }

        if (_companies.Count > 1)
        {
            DefenderDropdown.SelectId(1);
            _selectedDefenderId = _companies[1].ID;
        }
        else if (_companies.Count == 1)
        {
            DefenderDropdown.SelectId(0);
            _selectedDefenderId = _companies[0].ID;
        }

        _suppressDropdownEvents = false;
        UpdateButtons();
    }

    private void OnCompanySelected(OptionButton.ItemSelectedEventArgs args, bool aggressor)
    {
        if (_suppressDropdownEvents)
            return;

        if (args.Id < 0 || args.Id >= _companies.Count)
            return;

        args.Button.SelectId(args.Id);

        if (aggressor)
            _selectedAggressorId = _companies[args.Id].ID;
        else
            _selectedDefenderId = _companies[args.Id].ID;

        UpdateButtons();
    }

    private void OnWarSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (ActiveWarsList[args.ItemIndex].Metadata is not int warId)
            return;

        _selectedWarId = warId;
        UpdateSelectedWarDetails();
        UpdateButtons();
    }

    private void UpdateSelectedWarDetails()
    {
        CompanyWarOverview? war = null;
        foreach (var candidate in _wars)
        {
            if (candidate.WarId != _selectedWarId)
                continue;

            war = candidate;
            break;
        }

        if (war == null)
        {
            ClearSelectedWarDetails();
            return;
        }

        SyncCompanySelectors(war);

        var builder = new StringBuilder();
        builder.AppendLine(Loc.GetString("admin-faction-war-details-id", ("warId", war.WarId)));
        builder.AppendLine(Loc.GetString("admin-faction-war-details-aggressor", ("company", $"{war.AggressorName} ({war.AggressorCompanyId})")));
        builder.AppendLine(Loc.GetString("admin-faction-war-details-defender", ("company", $"{war.DefenderName} ({war.DefenderCompanyId})")));
        builder.AppendLine(Loc.GetString("admin-faction-war-details-declared-by", ("name", war.DeclaredBy)));
        builder.AppendLine(Loc.GetString("admin-faction-war-details-remaining", ("time", FormatRemaining(war.RemainingSeconds))));
        builder.AppendLine(Loc.GetString("admin-faction-war-details-peace",
            ("aggressor", war.AggressorRequestedPeace ? Loc.GetString("admin-faction-war-yes") : Loc.GetString("admin-faction-war-no")),
            ("defender", war.DefenderRequestedPeace ? Loc.GetString("admin-faction-war-yes") : Loc.GetString("admin-faction-war-no"))));
        builder.AppendLine(string.Empty);
        builder.Append(Loc.GetString("admin-faction-war-details-announcement", ("text", war.AnnouncementText)));
        SelectedWarLabel.Text = builder.ToString();
    }

    private void SyncCompanySelectors(CompanyWarOverview war)
    {
        var aggressorIndex = FindCompanyIndex(war.AggressorCompanyId);
        var defenderIndex = FindCompanyIndex(war.DefenderCompanyId);

        _selectedAggressorId = war.AggressorCompanyId;
        _selectedDefenderId = war.DefenderCompanyId;

        _suppressDropdownEvents = true;

        if (aggressorIndex >= 0)
            AggressorDropdown.SelectId(aggressorIndex);

        if (defenderIndex >= 0)
            DefenderDropdown.SelectId(defenderIndex);

        _suppressDropdownEvents = false;
    }

    private int FindCompanyIndex(string companyId)
    {
        for (var index = 0; index < _companies.Count; index++)
        {
            if (string.Equals(_companies[index].ID, companyId, StringComparison.OrdinalIgnoreCase))
                return index;
        }

        return -1;
    }

    private void ClearSelectedWarDetails()
    {
        _selectedWarId = null;
        SelectedWarLabel.Text = _wars.Count == 0
            ? Loc.GetString("admin-faction-war-no-active")
            : Loc.GetString("admin-faction-war-select-war");
        UpdateButtons();
    }

    private void SetStatusText(string text)
    {
        StatusLabel.Text = text;
    }

    private void UpdateButtons()
    {
        DeclareButton.Disabled = string.IsNullOrWhiteSpace(_selectedAggressorId)
            || string.IsNullOrWhiteSpace(_selectedDefenderId)
            || string.Equals(_selectedAggressorId, _selectedDefenderId, StringComparison.OrdinalIgnoreCase);
        EndWarButton.Disabled = _selectedWarId == null;
    }

    private static string FormatRemaining(float remainingSeconds)
    {
        var remaining = TimeSpan.FromSeconds(Math.Max(0f, remainingSeconds));
        return remaining.ToString(@"hh\:mm\:ss", CultureInfo.InvariantCulture);
    }
}
