// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Content.Lua.Shared.Administration.AlertLevel;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Administration.UI.AlertLevel;

[GenerateTypedNameReferences]
public sealed partial class AlertLevelAdminWindow : LunaWindow
{
    public event Action? RefreshPressed;
    public event Action<string, string, bool>? ApplySectorPressed;
    public event Action<string, bool>? ApplyGlobalPressed;

    private readonly List<AlertLevelAdminSectorInfo> _sectors = new();
    private readonly List<AlertLevelAdminLevelInfo> _levels = new();
    private string? _selectedSectorId;
    private string? _selectedLevelId;

    public AlertLevelAdminWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyLunaChrome();

        Shell.PanelOverride = LunaWindowStyle.Shell();
        SectorsPanel.PanelOverride = LunaWindowStyle.Panel();
        ControlsPanel.PanelOverride = LunaWindowStyle.Panel();
        StatusPanel.PanelOverride = LunaWindowStyle.Panel();

        LunaWindowStyle.StyleSecondary(SectorsSubtitle);
        LunaWindowStyle.StyleSecondary(SelectedSectorLabel);
        LunaWindowStyle.StyleSecondary(StatusLabel);
        SectorsTitle.FontOverride = LunaWindowStyle.FontTitle;
        SectorsTitle.FontColorOverride = LunaWindowStyle.TextPrimary;
        ControlsTitle.FontOverride = LunaWindowStyle.FontTitle;
        ControlsTitle.FontColorOverride = LunaWindowStyle.TextPrimary;

        SectorsList.OnItemSelected += OnSectorSelected;
        LevelDropdown.OnItemSelected += args =>
        {
            LevelDropdown.SelectId(args.Id);
            _selectedLevelId = LevelDropdown.SelectedMetadata as string;
            UpdateButtons();
        };
        ApplySectorButton.OnPressed += _ =>
        {
            if (_selectedSectorId == null || _selectedLevelId == null)
                return;
            ApplySectorPressed?.Invoke(_selectedSectorId, _selectedLevelId, LockedCheck.Pressed);
        };
        ApplyGlobalButton.OnPressed += _ =>
        {
            if (_selectedLevelId == null)
                return;
            ApplyGlobalPressed?.Invoke(_selectedLevelId, LockedCheck.Pressed);
        };
        RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();

        UpdateButtons();
    }

    public void UpdateState(AlertLevelAdminEuiState state)
    {
        var previousSector = _selectedSectorId;
        var previousLevel = _selectedLevelId;

        _sectors.Clear();
        _sectors.AddRange(state.Sectors);
        _levels.Clear();
        _levels.AddRange(state.Levels);

        SectorsList.Clear();
        _selectedSectorId = null;

        for (var i = 0; i < _sectors.Count; i++)
        {
            var sector = _sectors[i];
            var levelName = Loc.TryGetString($"alert-level-{sector.CurrentLevel}", out var loc)
                ? loc
                : sector.CurrentLevel;
            var locked = sector.Locked
                ? Loc.GetString("admin-alert-level-locked-tag")
                : string.Empty;
            var title = Loc.GetString("admin-alert-level-sector-row",
                ("sector", sector.SectorName),
                ("level", levelName),
                ("locked", locked));

            SectorsList.AddItem(title, metadata: sector.SectorId);
            if (previousSector != sector.SectorId)
                continue;

            SectorsList[i].Selected = true;
            _selectedSectorId = sector.SectorId;
        }

        LevelDropdown.Clear();
        _selectedLevelId = null;
        var levelSelected = false;
        for (var i = 0; i < _levels.Count; i++)
        {
            var level = _levels[i];
            LevelDropdown.AddItem(level.Name, i);
            LevelDropdown.SetItemMetadata(i, level.Id);
            if (level.Id != previousLevel)
                continue;

            LevelDropdown.SelectId(i);
            _selectedLevelId = level.Id;
            levelSelected = true;
        }

        if (!levelSelected && LevelDropdown.ItemCount > 0)
        {
            LevelDropdown.SelectId(0);
            _selectedLevelId = LevelDropdown.GetItemMetadata(0) as string;
        }

        StatusLabel.Text = string.IsNullOrWhiteSpace(state.StatusText)
            ? Loc.GetString("admin-alert-level-status-idle")
            : state.StatusText;

        UpdateSelectedSectorLabel();
        UpdateButtons();
    }

    private void OnSectorSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0 || args.ItemIndex >= _sectors.Count)
            return;

        _selectedSectorId = _sectors[args.ItemIndex].SectorId;
        UpdateSelectedSectorLabel();
        UpdateButtons();
    }

    private void UpdateSelectedSectorLabel()
    {
        if (_selectedSectorId == null)
        {
            SelectedSectorLabel.Text = Loc.GetString("admin-alert-level-no-sector");
            return;
        }

        var sector = _sectors.Find(s => s.SectorId == _selectedSectorId);
        if (sector == null)
        {
            SelectedSectorLabel.Text = Loc.GetString("admin-alert-level-no-sector");
            return;
        }

        var levelName = Loc.TryGetString($"alert-level-{sector.CurrentLevel}", out var loc)
            ? loc
            : sector.CurrentLevel;
        SelectedSectorLabel.Text = Loc.GetString("admin-alert-level-selected-sector",
            ("sector", sector.SectorName),
            ("level", levelName));
        SelectedSectorLabel.FontColorOverride = Color.TryFromHex(sector.LevelColorHex, out var color)
            ? color
            : LunaWindowStyle.TextSecondary;
    }

    private void UpdateButtons()
    {
        ApplySectorButton.Disabled = _selectedSectorId == null || string.IsNullOrEmpty(_selectedLevelId);
        ApplyGlobalButton.Disabled = string.IsNullOrEmpty(_selectedLevelId);
    }
}
