- type: job
  id: UsspBrigmedic
  name: job-name-ussp-brigmedic
  description: job-description-ussp-brigmedic
  playTimeTracker: JobUsspBrigmedic
  requiredCompany: Ussp
  salary: 30000
  startingGear: UsspBrigmedicGear
  icon: JobIconUsspBrigmedic
  supervisors: job-supervisors-ussp-hos
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 28800
  - !type:DepartmentTimeRequirement
    department: OutpostUssp
    time: 28800
  access:
  - USSPMedical
  - USSPSecurity
  - USSPBrigmedic
  - USSPBrig
  - USSPMaintenance
  - USSPExternal
  accessGroups:
  - GeneralAccess #lua
  - USSPGeneral
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: MailDisabled
    - type: NpcFactionMember
      factions:
      - Ussp

- type: startingGear
  id: UsspBrigmedicGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp


- type: chameleonOutfit
  id: UsspBrigmedicChameleonOutfit
  job: UsspBrigmedic
