- type: job
  id: UsspHeadOfSecurity
  name: job-name-ussp-hos
  description: job-description-ussp-hos
  playTimeTracker: JobUsspHeadOfSecurity
  requiredCompany: Ussp
  salary: 40000
  startingGear: UsspHeadOfSecurityGear
  icon: JobIconUsspHeadOfSecurity
  supervisors: job-supervisors-ussp-captain
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: OutpostUssp
    time: 54000
  - !type:RoleTimeRequirement
    role: JobUsspSecurityOfficer
    time: 36000
  access:
  - USSPHeadOfSecurity
  - USSPCommand
  - USSPSecurity
  - USSPBrig
  - USSPArmory
  - USSPMaintenance
  - USSPExternal
  accessGroups:
  - GeneralAccess #lua
  - USSPGeneral
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: MailDisabled
    - type: NpcFactionMember
      factions:
      - Ussp

- type: startingGear
  id: UsspHeadOfSecurityGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp


- type: chameleonOutfit
  id: UsspHeadOfSecurityChameleonOutfit
  job: UsspHeadOfSecurity
