- type: job
  id: UsspSecurityOfficer
  name: job-name-ussp-security
  description: job-description-ussp-security
  playTimeTracker: JobUsspSecurityOfficer
  requiredCompany: Ussp
  salary: 22000
  startingGear: UsspSecurityOfficerGear
  icon: JobIconUsspSecurityOfficer
  supervisors: job-supervisors-ussp-hos
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: OutpostUssp
    time: 36000
  access:
  - USSPSecurity
  - USSPBrig
  - USSPMaintenance
  - USSPExternal
  accessGroups:
  - GeneralAccess #lua
  - USSPGeneral
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: MailDisabled
    - type: NpcFactionMember
      factions:
      - Ussp

- type: startingGear
  id: UsspSecurityOfficerGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp


- type: chameleonOutfit
  id: UsspSecurityOfficerChameleonOutfit
  job: UsspSecurityOfficer
