- type: job
  id: UsspSecurityCadet
  name: job-name-ussp-security-cadet
  description: job-description-ussp-security-cadet
  playTimeTracker: JobUsspSecurityCadet
  requiredCompany: Ussp
  salary: 15000
  startingGear: UsspSecurityCadetGear
  icon: JobIconUsspSecurityCadet
  supervisors: job-supervisors-ussp-hos
  canBeAntag: false
  hideConsoleVisibility: true
  access:
  - USSPSecurity
  - USSPBrig
  - USSPMaintenance
  accessGroups:
  - GeneralAccess #lua
  - USSPGeneral
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: MailDisabled
    - type: NpcFactionMember
      factions:
      - Ussp

- type: startingGear
  id: UsspSecurityCadetGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp


- type: chameleonOutfit
  id: UsspSecurityCadetChameleonOutfit
  job: UsspSecurityCadet
