// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Linq;
using Content.Lua.UIKit.Styles;
using Content.Lua.Shared.LunaPlan;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Lua.LunaPlan;

[GenerateTypedNameReferences]
public sealed partial class LunaPlanWindow : LunaWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public LunaPlanWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();
        StyleChrome();
        PopulateBoard();
    }

    private void StyleChrome()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        DoneColumn.PanelOverride = LunaWindowStyle.Panel();
        ActiveColumn.PanelOverride = LunaWindowStyle.Panel();
        QueuedColumn.PanelOverride = LunaWindowStyle.Panel();

        LunaWindowStyle.StyleSecondary(Caption);

        DoneTitle.FontOverride = LunaWindowStyle.FontTitle;
        DoneTitle.FontColorOverride = LunaWindowStyle.AccentGood;
        ActiveTitle.FontOverride = LunaWindowStyle.FontTitle;
        ActiveTitle.FontColorOverride = LunaWindowStyle.AccentWarn;
        QueuedTitle.FontOverride = LunaWindowStyle.FontTitle;
        QueuedTitle.FontColorOverride = LunaWindowStyle.TextMuted;
    }

    private void PopulateBoard()
    {
        var buckets = _prototypes.EnumeratePrototypes<LunaPlanPrototype>()
            .GroupBy(plan => plan.Status)
            .ToDictionary(group => group.Key, group => group.OrderBy(plan => plan.Sort).ToArray());

        Fill(DoneList, buckets.GetValueOrDefault(LunaPlanStatus.Done));
        Fill(ActiveList, buckets.GetValueOrDefault(LunaPlanStatus.Active));
        Fill(QueuedList, buckets.GetValueOrDefault(LunaPlanStatus.Queued));
    }

    private static void Fill(BoxContainer list, LunaPlanPrototype[]? plans)
    {
        list.RemoveAllChildren();

        if (plans == null || plans.Length == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("luna-plan-empty"),
                Margin = new Thickness(8),
                HorizontalAlignment = HAlignment.Center,
            };
            LunaWindowStyle.StyleMuted(empty);
            list.AddChild(empty);
            return;
        }

        foreach (var plan in plans)
            list.AddChild(new LunaPlanTile(plan));
    }
}
