#region Base
- type: latheRecipe
  id: BaseEmptyMagazineRecipe
  abstract: true
  categories:
  - NFMagazines
  completetime: 1

- type: latheRecipe
  id: BaseFilledMagazineRecipe
  parent: BaseEmptyMagazineRecipe
  abstract: true
  completetime: 2.5

#region Xbow Bolts
- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25



#region Shotgun Ammo Box
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeBuckshot
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeBuckshot
  materials:
    Steel: 400 # box - free, 20 [bullets] * 20 [Steel per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeOverpressure
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeOverpressure
  materials:
    Steel: 600 # box - free, 20 [bullets] * 30 [Steel per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeIncendiary
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeIncendiary
  materials:
    Plastic: 400 # box - free, 20 [bullets] * 20 [Plastic per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugePractice
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugePractice
  materials:
    Steel: 260 # box - free, 20 [bullets] * 13 [Steel per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeUranium
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeUranium
  materials:
    Plastic: 250 # box - free, 20 [bullets] * 12.5 [Plastic per bullet]
    Uranium: 250 # box - free, 20 [bullets] * 12.5 [Uranium per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeSlug
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeSlug
  materials:
    Steel: 400 # box - free, 20 [bullets] * 20 [Steel per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeBeanbag
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeBeanbag
  materials:
    Steel: 200 # box - free, 20 [bullets] * 20 [Steel per bullet]
    Plastic: 200 # box - free, 20 [bullets] * 20 [Plastic per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeFlare
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeFlare
  materials:
    Plastic: 300 # box - free, 20 [bullets] * 20 [Plastic per bullet]
    Steel: 100 # box - free, 20 [bullets] * 20 [Steel per bullet]

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeTranquilizer
  categories:
  - AmmoCaliber12Gauge
  - AmmoKindBox
  result: AmmoBox12_gaugeTranquilizer
  materials:
    Plastic: 300
    Steel: 200
    Glass: 100
    Plasma: 200
    Silver: 100

#region Empty Mags
- type: latheRecipe
  parent: BaseEmptyMagazineRecipe
  id: NFSpeedLoaderPistol35Empty
  result: SpeedLoader9x19mmEmpty
  materials:
    Steel: 20

- type: latheRecipe
  parent: BaseEmptyMagazineRecipe
  id: NFSpeedLoaderPistol45Empty
  result: NFSpeedLoaderPistol45Empty
  materials:
    Steel: 20

- type: latheRecipe
  parent: BaseEmptyMagazineRecipe
  id: NFMagazinePistol45Empty
  categories:
  - AmmoCaliber357
  - AmmoKindMagazine
  result: Magazine45_ACPPistolEmpty
  materials:
    Steel: 20

- type: latheRecipe
  parent: BaseEmptyMagazineRecipe
  id: MagazineAsmgtUniversalEmpty
  result: MagazineAsmgtUniversalEmpty
  materials:
    Steel: 40

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

# - type: latheRecipe
#   parent: BaseWeaponRecipeLong
#   id: NFWeaponEnergyRifleCarbinePractice
#   result: NFWeaponEnergyRifleCarbinePractice
#   completetime: 6
#   materials:
#     Steel: 1800
#     Glass: 400
#     Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleCarbine
  result: WeaponLaserCarbine
  completetime: 6
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: NFWeaponEnergyPistolDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: NFWeaponEnergyPistolDisabler
  result: WeaponDisabler
  completetime: 6
  materials:
    Steel: 500
    Glass: 200
    Plastic: 400

- type: latheRecipe
  parent: NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
  id: NFWeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<NFWeaponEnergySubMachineGunDisabler
  result: WeaponDisablerSMG # Frontier: WeaponDisablerSMG<NFWeaponEnergySubMachineGunDisabler
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyPistolLaserAdvanced
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleSniperCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyPistolLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

# region Grenades
- type: latheRecipe
  id: NFGrenadeEMP # Frontier: add NF prefix
  result: NFGrenadeEMP # Frontier: add NF prefix
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: NFGrenadeBlast # Frontier: add NF prefix
  result: NFGrenadeBlast # Frontier: add NF prefix
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: NFGrenadeFlash
  result: NFGrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

#region Shields
- type: latheRecipe
  parent: BaseShieldRecipe
  id: NFMetalShield
  result: NFMetalShield
  materials:
    Steel: 600
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: NFShieldBallistic
  result: NFShieldBallistic
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: NFShieldReflective
  result: NFShieldReflective
  materials:
    Steel: 400
    Glass: 400

# region Misc
- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty

# region Upstream Removed
- type: latheRecipe
  parent: Handcuffs
  id: NFHandcuffs

- type: latheRecipe
  parent: Zipties
  id: NFZipties

- type: latheRecipe
  parent: Stunbaton
  id: NFStunbaton

- type: latheRecipe
  parent: Truncheon
  id: NFTruncheon

- type: latheRecipe
  parent: CombatKnife
  id: NFCombatKnife

- type: latheRecipe
  parent: ClothingBackpackElectropack
  id: NFClothingBackpackElectropack

- type: latheRecipe
  parent: ForensicPad
  id: NFForensicPad

- type: latheRecipe
  parent: ClothingEyesHudSecurity
  id: NFClothingEyesHudSecurity

- type: latheRecipe
  parent: HoloprojectorSecurity
  id: NFHoloprojectorSecurityEmpty

- type: latheRecipe
  parent: RiotShield
  id: NFRiotShield

- type: latheRecipe
  parent: TelescopicShield
  id: NFTelescopicShield

- type: latheRecipe
  parent: Flash
  id: NFFlash

- type: latheRecipe
  parent: TargetHuman
  id: NFTargetHuman

- type: latheRecipe
  parent: TargetClown
  id: NFTargetClown

- type: latheRecipe
  parent: TargetSyndicate
  id: NFTargetSyndicate

- type: latheRecipe
  parent: PortableRecharger
  id: NFPortableRecharger

- type: latheRecipe
  parent: ClothingBackpackHarmpack
  id: NFClothingBackpackHarmpack
