using System.Numerics;
using System.Linq;
using Content.Lua.UIKit.Styles;
using Content.Client.Interaction;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.Autodoc;
using Content.Shared.Atmos;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Mobs;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Key = Robust.Client.Input.Keyboard.Key;

namespace Content.Client.Lua.Autodoc;

[GenerateTypedNameReferences]
public sealed partial class AutodocWindow : FancyWindow
{
    private enum DragSource : byte { None, BodyPart, Organ, Storage }

    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IInputManager _input = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IResourceCache _resources = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private static readonly Color DropBorder = LunaWindowStyle.AccentDrop;

    private static readonly Dictionary<string, string> PartHoverTextures = new()
    {
        ["Head"] = "/Textures/_Shitmed/Interface/Targeting/Doll/head_hover.png",
        ["Torso"] = "/Textures/_Shitmed/Interface/Targeting/Doll/torso_hover.png",
        ["LeftArm"] = "/Textures/_Shitmed/Interface/Targeting/Doll/leftarm_hover.png",
        ["LeftHand"] = "/Textures/_Shitmed/Interface/Targeting/Doll/lefthand_hover.png",
        ["RightArm"] = "/Textures/_Shitmed/Interface/Targeting/Doll/rightarm_hover.png",
        ["RightHand"] = "/Textures/_Shitmed/Interface/Targeting/Doll/righthand_hover.png",
        ["LeftLeg"] = "/Textures/_Shitmed/Interface/Targeting/Doll/leftleg_hover.png",
        ["LeftFoot"] = "/Textures/_Shitmed/Interface/Targeting/Doll/leftfoot_hover.png",
        ["RightLeg"] = "/Textures/_Shitmed/Interface/Targeting/Doll/rightleg_hover.png",
        ["RightFoot"] = "/Textures/_Shitmed/Interface/Targeting/Doll/rightfoot_hover.png",
    };

    private const string GroinHoverTexture = "/Textures/_Shitmed/Interface/Targeting/Doll/groin_hover.png";

    private readonly Dictionary<string, TextureButton> _partButtons;
    private readonly DragDropHelper<NetEntity> _dragHelper;
    private readonly SpriteView _dragShadow;
    private readonly SpriteSystem _sprites;
    private readonly StyleBoxFlat _panelHighlight;
    private readonly EntProtoId _bodyView = "AlertSpriteView";
    private AutodocBoundUserInterfaceState? _state;
    private EntityUid _bodyViewEntity;
    private NetEntity? _selectedPart;
    private DragSource _dragSource;
    private TextureButton? _highlightedPart;
    private bool _highlightGroin;
    private bool _dragMouseHeld;

    public event Action<NetEntity>? OnSelectPart;
    public event Action<NetEntity>? OnHealPart;
    public event Action<NetEntity>? OnRemovePart;
    public event Action<AutodocTransferMessage>? OnTransfer;
    public event Action? OnStop;

    public AutodocWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();
        _panelHighlight = LunaWindowStyle.DropHighlight();

        ApplyLunaInterior();

        LayoutContainer.SetAnchorPreset(Shell, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(BusyOverlay, LayoutContainer.LayoutPreset.Wide);

        _partButtons = new Dictionary<string, TextureButton>
        {
            ["Head"] = HeadButton, ["Torso"] = TorsoButton,
            ["LeftArm"] = LeftArmButton, ["LeftHand"] = LeftHandButton,
            ["RightArm"] = RightArmButton, ["RightHand"] = RightHandButton,
            ["LeftLeg"] = LeftLegButton, ["LeftFoot"] = LeftFootButton,
            ["RightLeg"] = RightLegButton, ["RightFoot"] = RightFootButton
        };

        foreach (var (slot, button) in _partButtons)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.OnPressed += _ => SelectSlot(slot);
            button.OnKeyBindDown += args => BeginPartDrag(slot, args);
        }

        GroinButton.MouseFilter = MouseFilterMode.Stop;
        GroinButton.OnPressed += _ => SelectSlot("Torso");
        GroinButton.OnKeyBindDown += args => BeginPartDrag("Torso", args);

        HealButton.OnPressed += _ => SendSelected(OnHealPart);
        RemoveButton.OnPressed += _ => SendSelected(OnRemovePart);
        AbortButton.OnPressed += _ => OnStop?.Invoke();
        _dragHelper = new DragDropHelper<NetEntity>(OnBeginDrag, OnContinueDrag, OnEndDrag);
        _dragShadow = new SpriteView
        {
            SetSize = new Vector2(64, 64),
            Visible = false,
            MouseFilter = MouseFilterMode.Ignore
        };
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        BusyOverlay.PanelOverride = LunaWindowStyle.DimOverlay();
        BusyOverlay.MouseFilter = MouseFilterMode.Stop;
        LunaWindowStyle.StyleVerticalDivider(LeftColumnDivider);
        LunaWindowStyle.StyleVerticalDivider(RightColumnDivider);
        LunaWindowStyle.StyleDivider(VitalsDivider);
        LunaWindowStyle.StyleDivider(DiagnosticsDivider);
        LunaWindowStyle.StyleDivider(OrganDivider);
        LunaWindowStyle.StyleDivider(FooterDivider);
        LunaWindowStyle.ApplyCompactStyle(Shell);
        LunaWindowStyle.ApplyCompactStyle(BusyOverlay);
        LunaWindowStyle.StyleHeading(PatientHeadingLabel);
        LunaWindowStyle.StyleMuted(NoPatientLabel);
        LunaWindowStyle.StyleHeading(NameLabel);
        LunaWindowStyle.StyleSecondary(SpeciesLabel);
        LunaWindowStyle.StyleMuted(StatusKeyLabel);
        LunaWindowStyle.StyleMuted(TemperatureKeyLabel);
        LunaWindowStyle.StyleMuted(BloodKeyLabel);
        LunaWindowStyle.StyleMuted(DamageKeyLabel);
        LunaWindowStyle.StyleValue(StatusLabel);
        LunaWindowStyle.StyleValue(TemperatureLabel);
        LunaWindowStyle.StyleValue(BloodLabel);
        LunaWindowStyle.StyleValue(DamageLabel);
        LunaWindowStyle.StyleDanger(BleedingLabel);
        LunaWindowStyle.StyleMuted(DiagnosticsTitle);
        LunaWindowStyle.StyleHeading(SelectedPartLabel);
        LunaWindowStyle.StyleHeading(OrgansHeadingLabel);
        LunaWindowStyle.StyleHeading(StorageHeadingLabel);
        LunaWindowStyle.StyleHeading(BusyLabel);
        LunaWindowStyle.StyleFooter(FlavorLeftLabel);
        LunaWindowStyle.StyleFooter(FlavorRightLabel);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        if (_dragShadow.Parent == null)
            UserInterfaceManager.PopupRoot.AddChild(_dragShadow);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _dragMouseHeld = false;
        _dragHelper.EndDrag();
        _dragShadow.Orphan();
        if (!_entities.Deleted(_bodyViewEntity))
            _entities.QueueDeleteEntity(_bodyViewEntity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgress();
        _dragHelper.Update(args.DeltaSeconds);
        if (!_dragMouseHeld || _input.IsKeyDown(Key.MouseLeft))
            return;

        _dragMouseHeld = false;
        var dragged = _dragHelper.Dragged;
        var mouse = UserInterfaceManager.MousePositionScaled.Position;
        if (_dragHelper.IsDragging && dragged is { } item)
        {
            if (_dragSource is DragSource.BodyPart or DragSource.Organ && StoragePanel.GlobalRect.Contains(mouse))
            {
                var source = _dragSource == DragSource.BodyPart ? AutodocTransferTarget.BodyPart : AutodocTransferTarget.OrganSlot;
                OnTransfer?.Invoke(new AutodocTransferMessage(item, source, AutodocTransferTarget.Storage, _selectedPart));
            }
            else if (_dragSource == DragSource.Storage && BodyDoll.GlobalRect.Contains(mouse))
            {
                OnTransfer?.Invoke(new AutodocTransferMessage(item, AutodocTransferTarget.Storage, AutodocTransferTarget.BodyPart, _selectedPart));
            }
            else if (_dragSource == DragSource.Storage && OrganPanel.GlobalRect.Contains(mouse) &&
                     _state?.Storage.FirstOrDefault(value => value.Entity == item)?.OrganSlot is { } organSlot)
            {
                OnTransfer?.Invoke(new AutodocTransferMessage(item, AutodocTransferTarget.Storage,
                    AutodocTransferTarget.OrganSlot, _selectedPart, organSlot));
            }
        }

        _dragSource = DragSource.None;
        _dragHelper.EndDrag();
    }

    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _state = state;
        _selectedPart = state.SelectedPart;
        NoPatientLabel.Visible = !state.PatientPresent;
        PatientContent.Visible = state.PatientPresent;
        BusyOverlay.Visible = state.Busy;
        BusyLabel.Text = state.Status;
        UpdateProgress();

        foreach (var (slot, button) in _partButtons)
        {
            button.Visible = state.PatientPresent;
            button.Disabled = state.Busy || state.Parts.All(part => part.Slot != slot);
        }

        GroinButton.Visible = state.PatientPresent;
        GroinButton.Disabled = state.Busy || state.Parts.All(part => part.Slot != "Torso");

        RebuildBody(state);
        UpdateVitals(state);

        var selected = state.Parts.FirstOrDefault(part => part.Entity == state.SelectedPart);
        SelectedPartLabel.Text = selected != null
            ? Loc.GetString("autodoc-selected-part", ("part", GetPartLabel(selected.Slot)))
            : Loc.GetString("autodoc-select-part");
        HealButton.Disabled = selected == null || state.Busy;
        RemoveButton.Disabled = selected == null || state.Busy;
        RebuildOrgans(state);
        RebuildStorage(state);
    }

    private static string GetPartLabel(string slot)
    {
        var key = slot switch
        {
            "Head" => "health-analyzer-window-body-part-head",
            "Torso" => "health-analyzer-window-body-part-torso",
            "Groin" => "health-analyzer-window-body-part-groin",
            "LeftArm" => "health-analyzer-window-body-part-left-arm",
            "LeftHand" => "health-analyzer-window-body-part-left-hand",
            "RightArm" => "health-analyzer-window-body-part-right-arm",
            "RightHand" => "health-analyzer-window-body-part-right-hand",
            "LeftLeg" => "health-analyzer-window-body-part-left-leg",
            "LeftFoot" => "health-analyzer-window-body-part-left-foot",
            "RightLeg" => "health-analyzer-window-body-part-right-leg",
            "RightFoot" => "health-analyzer-window-body-part-right-foot",
            _ => null
        };

        return key != null ? Loc.GetString(key) : slot;
    }

    private void SelectSlot(string slot)
    {
        var part = _state?.Parts.FirstOrDefault(value => value.Slot == slot);
        if (part == null)
            return;
        _selectedPart = part.Entity;
        OnSelectPart?.Invoke(part.Entity);
    }

    private void SendSelected(Action<NetEntity>? action)
    {
        if (_selectedPart is { } part)
            action?.Invoke(part);
    }

    private void BeginPartDrag(string slot, GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick || _state?.Busy == true)
            return;
        var part = _state?.Parts.FirstOrDefault(value => value.Slot == slot);
        if (part == null)
            return;
        BeginDrag(part.Entity, DragSource.BodyPart);
        args.Handle();
    }

    private void RebuildOrgans(AutodocBoundUserInterfaceState state)
    {
        OrganList.DisposeAllChildren();
        foreach (var organ in state.Organs)
        {
            var row = CreateListRow(
                organ.Name ?? Loc.GetString("autodoc-organ-empty"),
                organ.Entity is { } iconEntity && _entities.TryGetEntity(iconEntity, out var organUid)
                    ? organUid
                    : null);

            if (organ.Entity is { } entity)
                row.OnKeyBindDown += args => BeginEntityDrag(entity, DragSource.Organ, args);

            OrganList.AddChild(row);
        }
    }

    private void RebuildStorage(AutodocBoundUserInterfaceState state)
    {
        StorageList.DisposeAllChildren();
        foreach (var item in state.Storage)
        {
            var label = item.BodyPartSlot != null
                ? GetPartLabel(item.BodyPartSlot)
                : item.Name;

            var row = CreateListRow(
                label,
                _entities.TryGetEntity(item.Entity, out var entity) ? entity : null);

            row.OnKeyBindDown += args => BeginEntityDrag(item.Entity, DragSource.Storage, args);
            StorageList.AddChild(row);
        }
    }

    private Control CreateListRow(string text, EntityUid? iconEntity)
    {
        var row = new PanelContainer
        {
            MinHeight = 32,
            MouseFilter = MouseFilterMode.Stop,
            HorizontalExpand = true
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(2, 1),
            SeparationOverride = 6
        };

        if (iconEntity is { } uid)
        {
            var icon = new SpriteView
            {
                SetSize = new Vector2(28, 28),
                MouseFilter = MouseFilterMode.Ignore
            };
            icon.SetEntity(uid);
            content.AddChild(icon);
        }
        else
        {
            content.AddChild(new Control { MinSize = new Vector2(28, 28) });
        }

        var nameLabel = new Label
        {
            Text = text,
            HorizontalExpand = true,
            ClipText = true,
            VerticalAlignment = VAlignment.Center,
        };
        LunaWindowStyle.StyleValue(nameLabel);
        content.AddChild(nameLabel);
        row.AddChild(content);
        return row;
    }

    private void UpdateVitals(AutodocBoundUserInterfaceState state)
    {
        DiagnosticsContainer.DisposeAllChildren();
        if (!state.PatientPresent || state.Vitals is not { } vitals)
        {
            NameLabel.Text = string.Empty;
            SpeciesLabel.Text = string.Empty;
            StatusLabel.Text = string.Empty;
            TemperatureLabel.Text = string.Empty;
            BloodLabel.Text = string.Empty;
            DamageLabel.Text = string.Empty;
            BleedingLabel.Visible = false;
            return;
        }

        NameLabel.Text = vitals.Name;
        SpeciesLabel.Text = vitals.SpeciesId is { } speciesId && _prototypes.TryIndex<SpeciesPrototype>(speciesId, out var species)
            ? Loc.GetString(species.Name)
            : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        StatusLabel.Text = vitals.MobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };

        TemperatureLabel.Text = !float.IsNaN(vitals.Temperature)
            ? $"{vitals.Temperature - Atmospherics.T0C:F1} °C"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(vitals.BloodLevel)
            ? $"{vitals.BloodLevel * 100:F0} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        DamageLabel.Text = vitals.TotalDamage.ToString("0.#");
        BleedingLabel.Visible = vitals.Bleeding;

        DrawDiagnostics(state, vitals);
    }

    private void DrawDiagnostics(AutodocBoundUserInterfaceState state, AutodocPatientVitals vitals)
    {
        var selected = state.Parts.FirstOrDefault(part => part.Entity == state.SelectedPart);
        if (selected != null && vitals.SelectedPartDamage is { Count: > 0 } partDamage)
        {
            var partHeading = new Label
            {
                Text = Loc.GetString("autodoc-selected-part-damage", ("part", GetPartLabel(selected.Slot))),
            };
            LunaWindowStyle.StyleHeading(partHeading);
            DiagnosticsContainer.AddChild(partHeading);
            foreach (var (type, amount) in partDamage.OrderByDescending(entry => entry.Value))
            {
                var typeName = _prototypes.TryIndex<DamageTypePrototype>(type, out var proto)
                    ? proto.LocalizedName
                    : type;
                var typeLabel = new Label { Text = $" · {typeName}: {amount}" };
                LunaWindowStyle.StyleValue(typeLabel);
                DiagnosticsContainer.AddChild(typeLabel);
            }
        }

        foreach (var (groupId, amount) in vitals.DamagePerGroup.OrderByDescending(entry => entry.Value))
        {
            if (!_prototypes.TryIndex<DamageGroupPrototype>(groupId, out var group))
                continue;

            var groupLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-damage-group-text",
                    ("damageGroup", group.LocalizedName),
                    ("amount", amount)),
                Margin = new Thickness(0, 4, 0, 0)
            };
            LunaWindowStyle.StyleHeading(groupLabel);
            DiagnosticsContainer.AddChild(groupLabel);

            foreach (var type in group.DamageTypes)
            {
                if (!vitals.DamagePerType.TryGetValue(type, out var typeAmount) || typeAmount <= FixedPoint2.Zero)
                    continue;

                var typeName = _prototypes.Index<DamageTypePrototype>(type).LocalizedName;
                var typeLabel = new Label
                {
                    Text = Loc.GetString("health-analyzer-window-damage-type-text",
                        ("damageType", typeName),
                        ("amount", typeAmount)).Insert(0, " · "),
                };
                LunaWindowStyle.StyleMuted(typeLabel);
                DiagnosticsContainer.AddChild(typeLabel);
            }
        }

        var damaged = vitals.DamagedParts
            .Select(part => new
            {
                Part = part,
                Total = part.Damage.Values.Aggregate(FixedPoint2.Zero, (sum, value) => sum + value)
            })
            .Where(part => part.Total > FixedPoint2.Zero)
            .OrderByDescending(part => part.Total)
            .Take(6)
            .ToList();

        if (damaged.Count == 0)
            return;

        var damagedTitle = new Label
        {
            Text = Loc.GetString("health-analyzer-window-damaged-parts-title"),
            Margin = new Thickness(0, 6, 0, 0)
        };
        LunaWindowStyle.StyleHeading(damagedTitle);
        DiagnosticsContainer.AddChild(damagedTitle);

        foreach (var entry in damaged)
        {
            var partLabel = new Label { Text = $"{GetPartLabel(entry.Part.Slot)}: {entry.Total}" };
            LunaWindowStyle.StyleValue(partLabel);
            DiagnosticsContainer.AddChild(partLabel);
            foreach (var (type, amount) in entry.Part.Damage.OrderByDescending(value => value.Value).Take(3))
            {
                var typeName = _prototypes.TryIndex<DamageTypePrototype>(type, out var proto)
                    ? proto.LocalizedName
                    : type;
                var typeLabel = new Label { Text = $" · {typeName}: {amount}" };
                LunaWindowStyle.StyleMuted(typeLabel);
                DiagnosticsContainer.AddChild(typeLabel);
            }
        }
    }

    private void BeginEntityDrag(NetEntity entity, DragSource source, GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick || _state?.Busy == true)
            return;
        BeginDrag(entity, source);
        args.Handle();
    }

    private void BeginDrag(NetEntity entity, DragSource source)
    {
        _dragSource = source;
        _dragMouseHeld = true;
        _dragHelper.MouseDown(entity);
    }

    private bool OnBeginDrag()
    {
        var entity = _dragHelper.Dragged;
        if (!_entities.TryGetEntity(entity, out var uid))
            return false;

        _dragShadow.SetEntity(uid);
        _dragShadow.Visible = true;
        UpdateDropTarget(entity);
        return true;
    }

    private bool OnContinueDrag(float frameTime)
    {
        LayoutContainer.SetPosition(_dragShadow, UserInterfaceManager.MousePositionScaled.Position - _dragShadow.Size / 2f);
        UpdateDropHover();
        return true;
    }

    private void OnEndDrag()
    {
        _dragShadow.Visible = false;
        _dragShadow.SetEntity(null);
        ClearDropTarget();
    }

    private void UpdateProgress()
    {
        if (_state is not { Busy: true } state)
            return;

        var progress = state.Progress;
        if (state.ProgressStart is { } start && state.ProgressEnd is { } end && end > start)
        {
            var elapsed = (_timing.CurTime - start).TotalSeconds;
            var duration = (end - start).TotalSeconds;
            progress = MathHelper.Lerp(state.Progress, state.ProgressTarget, (float) Math.Clamp(elapsed / duration, 0d, 1d));
        }

        ProgressBar.SetProgress(progress);
    }

    private void RebuildBody(AutodocBoundUserInterfaceState state)
    {
        if (!_entities.Deleted(_bodyViewEntity))
            _entities.QueueDeleteEntity(_bodyViewEntity);

        if (!state.PatientPresent)
        {
            PatientSprite.SetEntity(null);
            return;
        }

        _bodyViewEntity = _entities.Spawn(_bodyView);
        if (!_entities.TryGetComponent<SpriteComponent>(_bodyViewEntity, out var sprite))
            return;

        var status = new Dictionary<TargetBodyPart, TargetIntegrity>();
        foreach (var bodyPart in SharedTargetingSystem.GetValidParts())
        {
            var part = state.Parts.FirstOrDefault(value => value.Slot == bodyPart.ToString());
            status[bodyPart] = part == null
                ? TargetIntegrity.Severed
                : (TargetIntegrity) Math.Clamp((int) MathF.Ceiling((1f - part.Integrity) * 5f), 0, 5);
        }

        status[TargetBodyPart.Groin] = status.GetValueOrDefault(TargetBodyPart.Torso, TargetIntegrity.Severed);

        var layer = 0;
        foreach (var (bodyPart, integrity) in status)
        {
            var name = bodyPart.ToString().ToLowerInvariant();
            var rsi = new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{name}.rsi"),
                $"{name}_{(int) integrity}");
            var texture = _sprites.Frame0(rsi);
            if (!sprite.TryGetLayer(layer, out _))
                sprite.AddLayer(texture);
            else
                sprite.LayerSetTexture(layer, texture);
            sprite.LayerSetScale(layer, new Vector2(6f, 6f));
            layer++;
        }

        PatientSprite.SetEntity(_bodyViewEntity);
    }

    private void UpdateDropTarget(NetEntity entity)
    {
        ClearDropTarget();

        switch (_dragSource)
        {
            case DragSource.BodyPart:
            case DragSource.Organ:
                SetPanelHighlight(StoragePanel, true);
                break;

            case DragSource.Storage:
            {
                var info = _state?.Storage.FirstOrDefault(value => value.Entity == entity);
                if (info == null)
                    return;

                if (info.BodyPartSlot != null)
                {
                    SetPanelHighlight(DollPanel, true);
                    HighlightAttachSlot(info.BodyPartSlot);
                }
                else if (info.OrganSlot != null)
                {
                    SetPanelHighlight(OrganPanel, true);
                    if (_selectedPart != null)
                    {
                        var selected = _state?.Parts.FirstOrDefault(part => part.Entity == _selectedPart);
                        if (selected != null && _partButtons.TryGetValue(selected.Slot, out var partButton))
                            SetPartHighlight(selected.Slot, partButton);
                    }
                }

                break;
            }
        }

        UpdateDropHover();
    }

    private void UpdateDropHover()
    {
        if (!_dragHelper.IsDragging)
            return;

        var mouse = UserInterfaceManager.MousePositionScaled.Position;
        switch (_dragSource)
        {
            case DragSource.BodyPart:
            case DragSource.Organ:
                StoragePanel.ModulateSelfOverride = StoragePanel.GlobalRect.Contains(mouse)
                    ? DropBorder
                    : null;
                break;
            case DragSource.Storage:
                var info = _state?.Storage.FirstOrDefault(value => value.Entity == _dragHelper.Dragged);
                if (info?.BodyPartSlot != null)
                {
                    DollPanel.ModulateSelfOverride = BodyDoll.GlobalRect.Contains(mouse)
                        ? DropBorder
                        : null;
                }
                else if (info?.OrganSlot != null)
                {
                    OrganPanel.ModulateSelfOverride = OrganPanel.GlobalRect.Contains(mouse)
                        ? DropBorder
                        : null;
                }

                break;
        }
    }

    private void HighlightAttachSlot(string? partSlot)
    {
        var targetSlot = partSlot switch
        {
            "Head" or "LeftArm" or "RightArm" or "LeftLeg" or "RightLeg" => "Torso",
            "LeftHand" => "LeftArm",
            "RightHand" => "RightArm",
            "LeftFoot" => "LeftLeg",
            "RightFoot" => "RightLeg",
            _ => null
        };

        if (targetSlot != null && _partButtons.TryGetValue(targetSlot, out var target))
            SetPartHighlight(targetSlot, target);

        if (targetSlot is "Torso")
        {
            _highlightGroin = true;
            GroinButton.TextureNormal = _resources.GetTexture(GroinHoverTexture);
            GroinButton.ModulateSelfOverride = DropBorder;
        }
    }

    private void SetPartHighlight(string slot, TextureButton button)
    {
        _highlightedPart = button;
        if (PartHoverTextures.TryGetValue(slot, out var path))
            button.TextureNormal = _resources.GetTexture(path);
        button.ModulateSelfOverride = DropBorder;
    }

    private void SetPanelHighlight(PanelContainer panel, bool highlight)
    {
        panel.PanelOverride = highlight ? _panelHighlight : null;
    }

    private void ClearDropTarget()
    {
        SetPanelHighlight(DollPanel, false);
        SetPanelHighlight(OrganPanel, false);
        SetPanelHighlight(StoragePanel, false);
        DollPanel.ModulateSelfOverride = null;
        OrganPanel.ModulateSelfOverride = null;
        StoragePanel.ModulateSelfOverride = null;

        if (_highlightedPart != null)
        {
            _highlightedPart.TextureNormal = null;
            _highlightedPart.ModulateSelfOverride = null;
            _highlightedPart = null;
        }

        if (_highlightGroin)
        {
            GroinButton.TextureNormal = null;
            GroinButton.ModulateSelfOverride = null;
            _highlightGroin = false;
        }

        foreach (var button in _partButtons.Values)
        {
            button.TextureNormal = null;
            button.ModulateSelfOverride = null;
        }
    }
}
