// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Client.Lua.Starmap.UI;
using Content.Lua.UIKit.Styles;
using Content.Client.Shuttles.UI;
using Content.Client.Stylesheets;
using Content.Lua.Shared.Starmap;
using Content.Lua.UIKit.Shuttles;
using Content.Lua.Shared.Achievements;
using Content.Lua.Common.CLVar;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Timing;
using Robust.Shared.Network;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class StarMapScreen : BoxContainer, IStarMapConsoleScreen
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly INetManager _net = default!;

    private EntityUid? _console;
    private EntityUid? _shuttleEntity;
    private Star? _selectedStar;
    private float _warpRemaining;
    private float _warpTotal;
    private StartEndTime _ftlTime;
    private FTLState _ftlState;
    private string? _loreFullKey;
    private string _loreTitle = string.Empty;
    private StarmapLoreWindow? _loreWindow;

    public StarMapScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyMapStyle();
        StarMapCanvas.OnStarSelect += OnStarSelected;
        StarMapCanvas.OnZoneSelect += OnZoneSelected;
        WarpButton.OnPressed += _ =>
        {
            if (_selectedStar.HasValue)
                RequestWarpToStar?.Invoke(_selectedStar.Value);
        };
        LoreDetailsButton.OnPressed += _ => OpenLoreDetails();
        ClearLorePanel();
    }

    private void ApplyMapStyle()
    {
        ApplyCompactMapStyle(RightDisplayStarMap);
        WarpButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        LoreDetailsButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        LunaWindowStyle.StyleMuted(LorePanelHeading);
        LunaWindowStyle.StyleSecondary(LoreTitleLabel);
        LunaWindowStyle.StyleSecondary(CurrentStarLabel);
        LunaWindowStyle.StyleMuted(SelectedStarLabel);
        LoreSummaryScroll.OnResized += RefreshLoreSummaryStyle;
        SetLoreSummary(Loc.GetString("starmap-lore-empty"));
    }

    private string _loreSummaryRaw = string.Empty;

    private void RefreshLoreSummaryStyle()
    {
        var width = LoreSummaryScroll.Width > 1f ? LoreSummaryScroll.Width - 4f : 260f;
        LunaWindowStyle.StyleLoreBody(LoreSummaryLabel, _loreSummaryRaw, MathF.Max(120f, width));
    }

    private void SetLoreSummary(string text)
    {
        _loreSummaryRaw = text;
        RefreshLoreSummaryStyle();
    }

    private static void ApplyCompactMapStyle(Control root)
    {
        foreach (var child in root.Children)
        {
            switch (child)
            {
                case Label label:
                    label.AddStyleClass(StyleNano.StyleClassLabelSmall);
                    break;
                case Button button:
                    button.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
                    break;
            }

            ApplyCompactMapStyle(child);
        }
    }

    public Control Control => this;

    public event Action<Star>? RequestWarpToStar;

    public void SetConsole(EntityUid? console)
    {
        _console = console;
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
    }

    public void UpdateState(StarmapConsoleBoundUserInterfaceState state)
    {
        StarMapCanvas.Range = state.Range;
        StarMapCanvas.SetStars(state.Stars);
        StarMapCanvas.SetEdges(state.Edges);
        StarMapCanvas.SetCapturingMaps(new HashSet<MapId>(state.CapturingMaps ?? new List<MapId>()));
        StarMapCanvas.SetVisibleSectorMaps(state.VisibleSectorMaps);
        StarMapCanvas.SetSectorIdByMap(state.SectorIdByMap);
        StarMapCanvas.SetOwnerByMap(state.OwnerByMap);
        StarMapCanvas.SetSectorColorOverridesHex(state.SectorColorOverrideHexByMap);
        StarMapCanvas.SetSectorsGloballyUnlocked(state.SectorsGloballyUnlocked);
        var current = state.Stars.Find(s => s.Position == System.Numerics.Vector2.Zero);
        CurrentStarLabel.Text = Loc.GetString("starmap-current-star", ("name", current.Name ?? "???"));
        if (!_selectedStar.HasValue)
        {
            SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-empty");
            WarpButton.Disabled = true;
        }

        var incomingRemaining = MathF.Max(0, state.WarpCooldownRemainingSeconds);
        if (_warpRemaining > 0 && incomingRemaining > 0)
            _warpRemaining = MathF.Min(_warpRemaining, incomingRemaining);
        else
            _warpRemaining = incomingRemaining;
        _warpTotal = MathF.Max(0, state.WarpCooldownTotalSeconds);
        _ftlTime = state.FTLTime;
        ApplyFtlState(state.FTLState);
        UpdateWarpUI(state);
        if (_selectedStar.HasValue)
        {
            var map = _selectedStar.Value.Map;
            var found = state.Stars.Find(s => s.Map == map);
            if (found.Map != default)
                OnStarSelected(found);
            else
            {
                _selectedStar = null;
                SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-empty");
                WarpButton.Disabled = true;
            }
        }
    }

    private void ApplyFtlState(FTLState state)
    {
        _ftlState = state;
        WarpStatusLabel.Text = Loc.GetString($"shuttle-console-ftl-state-{state}");

        switch (state)
        {
            case FTLState.Available:
                FTLBar.SetColor(Color.FromHex("#80C71F"));
                break;
            case FTLState.Starting:
                FTLBar.SetColor(Color.FromHex("#169C9C"));
                break;
            case FTLState.Travelling:
                FTLBar.SetColor(Color.FromHex("#8932B8"));
                break;
            case FTLState.Arriving:
                FTLBar.SetColor(Color.FromHex("#F9801D"));
                break;
            default:
                FTLBar.SetColor(Color.FromHex("#B02E26"));
                break;
        }
    }

    private void OnZoneSelected(string zoneId)
    {
        _selectedStar = null;
        WarpButton.Disabled = true;
        SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-empty");

        if (!TryGetStarmapData(out var data))
        {
            ClearLorePanel();
            return;
        }

        foreach (var zone in data.FactionZones)
        {
            if (!string.Equals(zone.Id, zoneId, StringComparison.OrdinalIgnoreCase))
                continue;

            var title = ResolveLoc(zone.Name);
            ShowLore(title, zone.Description, zone.DescriptionFull);
            return;
        }

        ClearLorePanel();
    }

    private void OnStarSelected(Star star)
    {
        StarMapCanvas.ClearSelectedZone();
        _selectedStar = star;
        var name = star.Name;
        if (string.Equals(name, "Sol", System.StringComparison.OrdinalIgnoreCase)) _net.ClientSendMessage(new TryUnlockAchievementMessage(AchievementIds.SolStarClicked));
        if (!star.CanWarp)
        {
            SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-decorative", ("name", name));
            WarpButton.Disabled = true;
            TryShowStarLore(star);
            return;
        }

        var capturingNow = StarMapCanvas.IsCapturing(star.Map);
        if (StarMapCanvas.IsSector(star.Map))
        {
            var capturingText = capturingNow ? "\nВ процессе захвата" : string.Empty;
            SelectedStarLabel.Text = $"{Loc.GetString("starmap-selected-star", ("name", name))}{capturingText}";
        }
        else
        {
            var ownerText = Loc.GetString("starmap-owner-neutral");
            if (StarMapCanvas.TryGetOwner(star.Map, out var owner))
            {
                ownerText = owner switch
                {
                    "Syndicate" => Loc.GetString("starmap-owner-syndicate"),
                    "Security" or "Nfsd" => Loc.GetString("starmap-owner-security"),
                    "Pirates" => Loc.GetString("starmap-owner-pirates"),
                    "Nanotrasen" => Loc.GetString("starmap-owner-nanotrasen"),
                    "Ussp" => Loc.GetString("starmap-owner-ussp"),
                    "StormCreed" => Loc.GetString("starmap-owner-stormcreed"),
                    _ => Loc.GetString("starmap-owner-neutral")
                };
            }

            var header = Loc.GetString("starmap-selected-star", ("name", name));
            var own = Loc.GetString("starmap-ownership", ("owner", ownerText));
            var capturingText = capturingNow ? "\nВ процессе захвата" : string.Empty;
            SelectedStarLabel.Text = $"{header}\n{own}{capturingText}";
        }

        var isCurrent = star.Position == System.Numerics.Vector2.Zero;
        var isAdjacent = StarMapCanvas.IsAdjacentToCurrent(star);
        WarpButton.Disabled = isCurrent || !isAdjacent || _ftlState != FTLState.Available;
        TryShowStarLore(star);
    }

    private void TryShowStarLore(Star star)
    {
        if (!TryResolveStarDefinition(star, out var def))
        {
            ClearLorePanel();
            return;
        }

        ShowLore(def.Name, def.Description, def.DescriptionFull);
    }

    private bool TryResolveStarDefinition(Star star, out StarDefinition def)
    {
        def = default!;
        if (!TryGetStarmapData(out var data))
            return false;

        if (StarMapCanvas.TryGetSectorId(star.Map, out var sectorId))
        {
            foreach (var candidate in data.Stars)
            {
                if (!string.Equals(candidate.Id, sectorId, StringComparison.OrdinalIgnoreCase))
                    continue;
                def = candidate;
                return true;
            }
        }

        var name = FormatStarName(star.Name);
        foreach (var candidate in data.Stars)
        {
            if (!string.Equals(candidate.Name, name, StringComparison.Ordinal)
                && !string.Equals(candidate.Name, star.Name, StringComparison.Ordinal))
                continue;
            def = candidate;
            return true;
        }

        return false;
    }

    private void ShowLore(string title, string? shortKey, string? fullKey)
    {
        _loreTitle = ResolveLoc(title);
        LoreTitleLabel.Text = _loreTitle;
        LunaWindowStyle.StyleSecondary(LoreTitleLabel);

        if (!string.IsNullOrWhiteSpace(shortKey) && Loc.TryGetString(shortKey, out var summary))
        {
            SetLoreSummary(summary);
            _loreFullKey = string.IsNullOrWhiteSpace(fullKey) ? shortKey : fullKey;
            LoreDetailsButton.Disabled = false;
            return;
        }

        if (!string.IsNullOrWhiteSpace(fullKey) && Loc.TryGetString(fullKey, out var full))
        {
            SetLoreSummary(full);
            _loreFullKey = fullKey;
            LoreDetailsButton.Disabled = false;
            return;
        }

        ClearLorePanel(keepTitle: true);
    }

    private void ClearLorePanel(bool keepTitle = false)
    {
        if (!keepTitle)
            LoreTitleLabel.Text = string.Empty;
        SetLoreSummary(Loc.GetString("starmap-lore-empty"));
        _loreFullKey = null;
        LoreDetailsButton.Disabled = true;
    }

    private void OpenLoreDetails()
    {
        if (string.IsNullOrWhiteSpace(_loreFullKey) || !Loc.TryGetString(_loreFullKey, out var body))
            return;

        _loreWindow ??= new StarmapLoreWindow();
        _loreWindow.SetLore(string.IsNullOrWhiteSpace(_loreTitle) ? Loc.GetString("starmap-lore-panel-title") : _loreTitle, body);
        _loreWindow.OpenCentered();
        _net.ClientSendMessage(new TryUnlockAchievementMessage(AchievementIds.TutorialStarmapLore));
    }

    private bool TryGetStarmapData(out ComposedStarmapData data)
    {
        data = default!;
        try
        {
            var dataId = _cfg.GetCVar(CLVars.StarmapDataId);
            return StarmapDataComposer.TryCompose(_prototypes, dataId, out data!);
        }
        catch
        {
            return false;
        }
    }

    private static string ResolveLoc(string? keyOrText)
    {
        if (string.IsNullOrWhiteSpace(keyOrText))
            return string.Empty;
        return Loc.TryGetString(keyOrText, out var localized) ? localized : keyOrText;
    }

    private static string FormatStarName(string? name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "???";
        const string starPrefix = "[STAR] ";
        return name.StartsWith(starPrefix, StringComparison.Ordinal)
            ? name[starPrefix.Length..]
            : name;
    }

    public void Startup()
    {
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _warpRemaining = MathF.Max(0, _warpRemaining - args.DeltaSeconds);
        UpdateWarpUI();
    }

    private void UpdateWarpUI(StarmapConsoleBoundUserInterfaceState? stateOpt = null)
    {
        var shownState = stateOpt?.FTLState ?? _ftlState;
        var progress = _ftlTime.ProgressAt(_timing.CurTime);
        if (float.IsFinite(progress))
            FTLBar.SetProgress(progress);
        else if (_warpTotal > 0)
            FTLBar.SetProgress(1f - MathF.Min(1f, _warpRemaining / _warpTotal));
        else
            FTLBar.SetProgress(_warpRemaining <= 0 ? 1f : 0f);

        if (shownState != FTLState.Available)
            return;

        var seconds = (int) MathF.Ceiling(_warpRemaining);
        if (seconds <= 0)
        {
            WarpStatusLabel.Text = Loc.GetString("shuttle-console-ftl-state-Available");
            return;
        }

        var mins = seconds / 60;
        var secs = seconds % 60;
        WarpStatusLabel.Text = mins > 0 ? $"{mins}м {secs:00}с" : $"{secs}s";
    }
}
