// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.Shared.Starmap;
using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.Lua.Starmap.UI;

[GenerateTypedNameReferences]
public sealed partial class ShareSectorWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<string>? OnShareSector;

    public ShareSectorWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    protected override Vector2 ContentsMinimumSize => new(360, 420);

    public void UpdateState(ShareSectorBoundUserInterfaceState state)
    {
        StatusLabel.Text = Loc.GetString("share-sector-window-count", ("count", state.Sectors.Count));
        SectorList.RemoveAllChildren();

        foreach (var sector in state.Sectors)
        {
            var button = new ContainerButton
            {
                HorizontalExpand = true,
                ToolTip = GetSectorName(sector),
            };
            button.AddStyleClass(ContainerButton.StyleClassButton);

            var layout = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 6,
                RectClipContent = true,
            };

            AddCompanyFlag(layout, sector.CompanyIds);

            var textLayout = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                MinWidth = 0,
                SeparationOverride = 1,
            };
            textLayout.AddChild(new Label
            {
                Text = GetSectorName(sector),
                MinWidth = 0,
                HorizontalExpand = true,
                FontColorOverride = GetPrimaryCompanyColor(sector.CompanyIds),
                ClipText = true,
            });
            textLayout.AddChild(new Label
            {
                Text = Loc.GetString("share-sector-window-entry", ("x", sector.X), ("y", sector.Y)),
                MinWidth = 0,
                HorizontalExpand = true,
                ClipText = true,
                StyleClasses = { "LabelSubText" },
            });
            layout.AddChild(textLayout);

            button.AddChild(layout);
            button.OnPressed += _ => OnShareSector?.Invoke(sector.SectorId);

            SectorList.AddChild(button);
        }
    }

    private void AddCompanyFlag(BoxContainer layout, IReadOnlyList<string> companyIds)
    {
        foreach (var companyId in companyIds)
        {
            if (!TryGetCompanyIcon(companyId, out var texture))
                continue;

            layout.AddChild(new TextureRect
            {
                Texture = texture,
                MinSize = new Vector2(32, 32),
                MaxSize = new Vector2(32, 32),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center,
            });
            return;
        }

        layout.AddChild(new Label
        {
            Text = "*",
            MinWidth = 32,
            Align = Label.AlignMode.Center,
            VerticalAlignment = VAlignment.Center,
            StyleClasses = { "LabelSubText" },
        });
    }

    private Color? GetPrimaryCompanyColor(IReadOnlyList<string> companyIds)
    {
        foreach (var companyId in companyIds)
        {
            if (_prototypeManager.TryIndex<CompanyPrototype>(companyId, out var company))
                return company.Color;
        }

        return null;
    }

    private bool TryGetCompanyIcon(string companyId, out Texture? texture)
    {
        texture = null;
        if (!_prototypeManager.TryIndex<CompanyPrototype>(companyId, out var company) || string.IsNullOrWhiteSpace(company.IconPath))
            return false;

        texture = _resourceCache.GetResource<TextureResource>(company.IconPath!).Texture;
        return true;
    }

    private static string GetSectorName(ShareSectorEntry sector)
    {
        return Loc.TryGetString(sector.NameLocKey, out var localized)
            ? localized
            : sector.SectorId;
    }
}
