// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.Starmap.UI;

[GenerateTypedNameReferences]
public sealed partial class StarmapLoreWindow : LunaWindow
{
    private const float FallbackBodyWidth = 420f;
    private string _bodyRaw = string.Empty;

    public StarmapLoreWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyLunaChrome();
        ApplyLunaInterior();
        BodyScroll.OnResized += RefreshBodyStyle;
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        BodyPanel.PanelOverride = LunaWindowStyle.Panel();
        LunaWindowStyle.StyleDivider(Divider);
        LunaWindowStyle.StyleSecondary(LoreTitle);
        RefreshBodyStyle();
    }

    private void RefreshBodyStyle()
    {
        var width = BodyScroll.Width > 1f ? BodyScroll.Width - 16f : FallbackBodyWidth;
        LunaWindowStyle.StyleLoreBody(LoreBody, _bodyRaw, MathF.Max(160f, width), LunaWindowStyle.TextPrimary);
    }

    public void SetLore(string title, string body)
    {
        Title = title;
        LoreTitle.Text = title;
        LunaWindowStyle.StyleSecondary(LoreTitle);
        _bodyRaw = body;
        RefreshBodyStyle();
    }
}
