- type: job
  id: USSPCommissar
  name: job-name-ussp-commissar
  description: job-description-ussp-commissar
  playTimeTracker: JobUSSPCommissar
  requiredCompany: Ussp
  salary: 35000
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 144000 # 40 hrs
  startingGear: USSPCommissarGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: JobIconUSSPCommissar
  supervisors: job-supervisors-ussp-politruk
  canBeAntag: false
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddImplantSpecial
    implants: [ UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - Ussp
  accessGroups:
  - GeneralAccess
  - USSPAA

- type: startingGear
  id: USSPCommissarGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp

- type: chameleonOutfit
  id: USSPCommissarChameleonOutfit
  job: USSPCommissar

