- type: job
  id: USSPSergeant
  name: job-name-ussp-sergeant
  description: job-description-ussp-sergeant
  playTimeTracker: JobUSSPSergeant
  requiredCompany: Ussp
  salary: 25000
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hrs
  startingGear: USSPSergeantGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: JobIconUSSPSergeant
  supervisors: job-supervisors-ussp-commissar
  canBeAntag: false
  weight: 30
  displayWeight: 30
  setPreference: true
  special:
  - !type:AddImplantSpecial
    implants: [ UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Company
      companyName: Ussp
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - Ussp
  accessGroups:
  - GeneralAccess
  - USSPHigh

- type: startingGear
  id: USSPSergeantGear
  equipment: {}
  encryptionKeys:
  - USSPSFEncryptionKeyUssp

- type: chameleonOutfit
  id: USSPSergeantChameleonOutfit
  job: USSPSergeant

