// LuaCorp - This file is licensed under AGPLv3
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.RCD;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Lua.EmergencyRockCutter.UI;

[GenerateTypedNameReferences]
public sealed partial class EmergencyLabMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<ProtoId<RCDPrototype>>? OnPrototypeSelected;

    public EmergencyLabMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Title = Loc.GetString("emergency-lab-menu-title");
        HintLabel.Text = Loc.GetString("emergency-lab-menu-hint");
    }

    public void Populate(HashSet<ProtoId<RCDPrototype>> available, ProtoId<RCDPrototype> selected)
    {
        ItemList.RemoveAllChildren();

        var sprites = _entMan.System<SpriteSystem>();
        var ordered = available
            .Select(id => _prototypes.Index(id))
            .OrderBy(GetDisplayName)
            .ToList();

        foreach (var proto in ordered)
        {
            ItemList.AddChild(BuildRow(proto, sprites, proto.ID == selected));
        }
    }

    private Control BuildRow(RCDPrototype proto, SpriteSystem sprites, bool selected)
    {
        var button = new ContainerButton
        {
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = selected,
            MinHeight = 52,
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 10,
            Margin = new Thickness(6, 4),
        };

        if (proto.Prototype is { } entId)
        {
            var view = new EntityPrototypeView
            {
                Scale = new Vector2(1.5f, 1.5f),
                SetSize = new Vector2(40, 40),
                VerticalAlignment = VAlignment.Center,
            };
            view.SetPrototype(entId);
            content.AddChild(view);
        }
        else if (proto.Sprite != null)
        {
            content.AddChild(new TextureRect
            {
                Texture = sprites.Frame0(proto.Sprite),
                MinSize = new Vector2(40, 40),
                MaxSize = new Vector2(40, 40),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center,
            });
        }

        content.AddChild(new Label
        {
            Text = GetDisplayName(proto),
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
            ClipText = true,
        });

        button.AddChild(content);
        button.OnPressed += _ =>
        {
            OnPrototypeSelected?.Invoke(proto.ID);
            Close();
        };

        return button;
    }

    private string GetDisplayName(RCDPrototype proto)
    {
        if ((proto.Mode is RcdMode.ConstructTile or RcdMode.ConstructObject) &&
            proto.Prototype is { } entId)
        {
            var entKey = $"ent-{entId}";
            if (Loc.TryGetString(entKey, out var entName))
                return entName;

            if (_prototypes.TryIndex(entId, out EntityPrototype? entProto) &&
                entProto != null &&
                !string.Equals(entProto.Name, entId, StringComparison.Ordinal))
                return entProto.Name;
        }

        return Loc.GetString(proto.SetName);
    }
}
