- type: technology
  id: NFDartTracking
  name: research-technology-nfdarttracking
  entityIcon: NFDartTracking
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Nanotrasen
  - Syndicate
  - Pirates
  - Ussp
  - Security
  - Neutral
  cost: 5000
  recipeUnlocks:
  - NFDartTracking
- type: technology
  id: WeaponLauncherNfsdDartLake
  name: research-technology-weaponlaunchernfsddartlake
  entityIcon: WeaponLauncherNfsdDartLake
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 8000
  recipeUnlocks:
  - WeaponLauncherNfsdDartLake
- type: technology
  id: BreachingCharge
  name: research-technology-breachingcharge
  entityIcon: BreachingCharge
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Syndicate
  - Pirates
  - Ussp
  - Security
  cost: 12000
  recipeUnlocks:
  - BreachingCharge
- type: technology
  id: ClothingOuterHardsuitM82c
  name: research-technology-clothingouterhardsuitm82c
  entityIcon: ClothingOuterHardsuitM82c
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 15000
  recipeUnlocks:
  - ClothingOuterHardsuitM82c
- type: technology
  id: ClothingOuterHardsuitM82b
  name: research-technology-clothingouterhardsuitm82b
  entityIcon: ClothingOuterHardsuitM82b
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 15000
  recipeUnlocks:
  - ClothingOuterHardsuitM82b
- type: technology
  id: ClothingOuterHardsuitM86
  name: research-technology-clothingouterhardsuitm86
  entityIcon: ClothingOuterHardsuitM86
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 15000
  recipeUnlocks:
  - ClothingOuterHardsuitM86
- type: technology
  id: ClothingOuterHardsuitNfsdExperimental
  name: research-technology-clothingouterhardsuitnfsdexperimental
  entityIcon: ClothingOuterHardsuitNfsdExperimental
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 15000
  recipeUnlocks:
  - ClothingOuterHardsuitNfsdExperimental
- type: technology
  id: ClothingOuterHardsuitNfsdSheriff
  name: research-technology-clothingouterhardsuitnfsdsheriff
  entityIcon: ClothingOuterHardsuitNfsdSheriff
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 15000
  recipeUnlocks:
  - ClothingOuterHardsuitNfsdSheriff
- type: technology
  id: ContrabandForensicsModule
  name: research-technology-contrabandforensicsmodule
  entityIcon: ContrabandForensicsModule
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 14000
  recipeUnlocks:
  - ContrabandForensicsModule
- type: technology
  id: HoverbikeNfsdPacked
  name: research-technology-hoverbikenfsdpacked
  entityIcon: HoverbikeNfsdPacked
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 14000
  recipeUnlocks:
  - HoverbikeNfsdPacked
- type: technology
  id: CyborgStunbaton
  name: research-technology-cyborgstunbaton
  entityIcon: CyborgStunbaton
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Nanotrasen
  - Syndicate
  - Security
  cost: 14000
  recipeUnlocks:
  - CyborgStunbaton
- type: technology
  id: WeaponCyborgEnergyGun
  name: research-technology-weaponcyborgenergygun
  entityIcon: WeaponCyborgEnergyGun
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Nanotrasen
  - Syndicate
  - Pirates
  - Ussp
  - Security
  - Neutral
  cost: 14000
  recipeUnlocks:
  - WeaponCyborgEnergyGun
- type: technology
  id: ClothingShoesBootsMagNfsdFilled
  name: research-technology-clothingshoesbootsmagnfsdfilled
  entityIcon: ClothingShoesBootsMagNfsdFilled
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 16000
  recipeUnlocks:
  - ClothingShoesBootsMagNfsdFilled
- type: technology
  id: HoloprojectorNfsd
  name: research-technology-holoprojectornfsd
  entityIcon: HoloprojectorNfsd
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 16000
  recipeUnlocks:
  - HoloprojectorNfsd
- type: technology
  id: ClothingMaskGasSheriff
  name: research-technology-clothingmaskgassheriff
  entityIcon: ClothingMaskGasSheriff
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 16000
  recipeUnlocks:
  - ClothingMaskGasSheriff
- type: technology
  id: JetpackNfsd
  name: research-technology-jetpacknfsd
  entityIcon: JetpackNfsd
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 5000
  recipeUnlocks:
  - JetpackNfsd
- type: technology
  id: EncryptionKeyNfsd
  name: research-technology-encryptionkeynfsd
  entityIcon: EncryptionKeyNfsd
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 16000
  recipeUnlocks:
  - EncryptionKeyNfsd
- type: technology
  id: EnergyShieldNfsd
  name: research-technology-energyshieldnfsd
  entityIcon: EnergyShieldNfsd
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Security
  cost: 16000
  recipeUnlocks:
  - EnergyShieldNfsd
- type: technology
  id: StickyGrenade
  name: research-technology-stickygrenade
  entityIcon: StickyGrenade
  discipline: NFArsenal
  tags:
  - ballistics
  signatureFor: Security
  discoveryWeight: 1.35
  factions:
  - Syndicate
  - Ussp
  - Neutral
  cost: 15000
  recipeUnlocks:
  - StickyGrenade
