// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Linq;
using System.Numerics;
using Content.Lua.UIKit.Styles;
using Content.Client.Stylesheets;
using Content.Lua.Shared.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lua.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementsWindow : LunaWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystems = default!;
    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly INetManager _net = default!;

    private SpriteSystem? _sprite;
    private string? _selectedId;
    private List<AchievementEntry> _entries = new();

    public AchievementsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();
        ApplyLunaInterior();
        LayoutDetailOverlay();
        TreeView.OnNodeSelected += id =>
        {
            _selectedId = id;
            RefreshDetail();
        };
        ClaimRewardButton.OnPressed += _ =>
        {
            if (_selectedId != null)
                _net.ClientSendMessage(new ClaimAchievementRewardMessage(_selectedId));
        };
        ClearDetail();
    }
    public void FitNearFullscreen()
    {
        var root = UserInterfaceManager.WindowRoot.Size;
        if (root.X < 100f || root.Y < 100f)
            return;

        var target = new Vector2(root.X * 0.92f, root.Y * 0.90f);
        MinSize = new Vector2(MathF.Min(900f, target.X), MathF.Min(560f, target.Y));
        SetSize = target;
    }

    private SpriteSystem Sprite => _sprite ??= _entitySystems.GetEntitySystem<SpriteSystem>();

    private void LayoutDetailOverlay()
    {
        LayoutContainer.SetAnchorPreset(TreeScroll, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(
            ProgressCounter,
            LayoutContainer.LayoutPreset.TopLeft,
            margin: 12);
        LayoutContainer.SetAnchorAndMarginPreset(
            DetailPanel,
            LayoutContainer.LayoutPreset.TopRight,
            margin: 12);
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        DetailPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = LunaWindowStyle.PanelBg.WithAlpha(0.99f),
            BorderColor = LunaWindowStyle.PanelBorder.WithAlpha(0.85f),
            BorderThickness = new Thickness(1),
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
        };

        LunaWindowStyle.StyleHeading(DetailTitle);
        LunaWindowStyle.StyleMuted(DetailStatus);
        LunaWindowStyle.StyleMuted(DetailUnlockedAt);
        LunaWindowStyle.StyleMuted(ProgressCounter);
        LunaWindowStyle.StyleMuted(RewardTitle);
        LunaWindowStyle.StyleMuted(RewardClaimedLabel);
        RewardTitle.FontOverride = LunaWindowStyle.FontSmall;
        RewardTitle.FontColorOverride = LunaWindowStyle.Accent;
        RewardClaimedLabel.FontOverride = LunaWindowStyle.FontSmall;
        RewardClaimedLabel.FontColorOverride = LunaWindowStyle.AccentGood;
        ClaimRewardButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        DetailTitle.FontOverride = LunaWindowStyle.FontTitle;
        DetailTitle.FontColorOverride = LunaWindowStyle.TextPrimary;
        ProgressCounter.FontOverride = LunaWindowStyle.FontSmall;
        RefreshProgressCounter();
    }

    public void UpdateState(List<AchievementEntry> entries)
    {
        _entries = entries.ToList();
        RefreshProgressCounter();
        RebuildTree();

        if (_selectedId == null || !IsSelectable(_selectedId))
            _selectedId = PickDefaultSelection();

        RebuildTree();
        RefreshDetail();
    }

    public void ApplyUnlock(string achievementId, long unlockedAtTicks)
    {
        var existing = _entries.FirstOrDefault(e => e.AchievementId == achievementId);
        if (existing != null)
        {
            existing.Unlocked = true;
            existing.UnlockedAtTicks = unlockedAtTicks;
            if (existing.ProgressMax > 0)
                existing.Progress = existing.ProgressMax;
        }
        else
        {
            _entries.Add(new AchievementEntry
            {
                AchievementId = achievementId,
                Unlocked = true,
                UnlockedAtTicks = unlockedAtTicks,
            });
        }

        _selectedId = achievementId;
        UpdateState(_entries);
    }

    public void ApplyProgress(string achievementId, int progress, int progressMax)
    {
        var existing = _entries.FirstOrDefault(e => e.AchievementId == achievementId);
        if (existing != null)
        {
            existing.Progress = progress;
            existing.ProgressMax = progressMax;
        }
        else
        {
            _entries.Add(new AchievementEntry
            {
                AchievementId = achievementId,
                Progress = progress,
                ProgressMax = progressMax,
            });
        }

        if (_selectedId == achievementId)
            RefreshDetail();

        RebuildTree();
    }

    public void ApplyRewardClaimed(string achievementId)
    {
        var existing = _entries.FirstOrDefault(e => e.AchievementId == achievementId);
        if (existing != null)
            existing.RewardClaimed = true;

        if (_selectedId == achievementId)
            RefreshDetail();
    }

    private void RebuildTree()
    {
        ProgressCounter.Measure(Vector2Helpers.Infinity);
        TreeView.TopInset = 12 + ProgressCounter.DesiredSize.Y + 6;

        TreeView.Rebuild(_entries, _prototypes, Sprite, _selectedId);
        TreeScroll.SetScrollValue(Vector2.Zero);
        TreeScroll.InvalidateMeasure();
        TreeScroll.InvalidateArrange();
    }

    private bool IsSelectable(string id)
    {
        if (!_prototypes.TryIndex<AchievementPrototype>(id, out var proto))
            return false;

        var unlocked = _entries.Where(e => e.Unlocked).Select(e => e.AchievementId).ToHashSet();
        return AchievementTreeLogic.GetState(proto, unlocked) != AchievementNodeState.Hidden;
    }

    private string? PickDefaultSelection()
    {
        var unlocked = _entries.Where(e => e.Unlocked).Select(e => e.AchievementId).ToHashSet();

        AchievementPrototype? available = null;
        AchievementPrototype? unlockedProto = null;

        foreach (var proto in _prototypes.EnumeratePrototypes<AchievementPrototype>().OrderBy(p => p.ID))
        {
            var state = AchievementTreeLogic.GetState(proto, unlocked);
            if (state == AchievementNodeState.Available)
                available ??= proto;
            else if (state == AchievementNodeState.Unlocked)
                unlockedProto ??= proto;
        }

        return available?.ID ?? unlockedProto?.ID;
    }

    private void RefreshDetail()
    {
        if (_selectedId == null ||
            !_prototypes.TryIndex<AchievementPrototype>(_selectedId, out var proto))
        {
            ClearDetail();
            return;
        }

        var unlockedSet = _entries.Where(e => e.Unlocked).Select(e => e.AchievementId).ToHashSet();
        var state = AchievementTreeLogic.GetState(proto, unlockedSet);
        var entry = _entries.FirstOrDefault(e => e.AchievementId == _selectedId);

        DetailIcon.SetLayers(AchievementJobText.GetIconLayers(proto, _prototypes), Sprite);
        DetailIcon.SetModulate(state is AchievementNodeState.Unlocked or AchievementNodeState.Available
            ? Color.White
            : Color.FromHex("#555555"));

        var title = AchievementJobText.GetName(proto, _prototypes);
        DetailTitle.Text = title;
        if (title.Length > 28)
            DetailTitle.FontOverride = LunaWindowStyle.FontSmall;
        else
            DetailTitle.FontOverride = LunaWindowStyle.FontTitle;

        DetailStatus.Text = state switch
        {
            AchievementNodeState.Unlocked => Loc.GetString("ui-achievements-unlocked"),
            AchievementNodeState.Available when entry is { ProgressMax: > 1, Unlocked: false } =>
                Loc.GetString("ui-achievements-progress", ("current", entry.Progress), ("max", entry.ProgressMax)),
            AchievementNodeState.Available => Loc.GetString("ui-achievements-available"),
            _ => Loc.GetString("ui-achievements-locked"),
        };
        DetailStatus.FontColorOverride = state switch
        {
            AchievementNodeState.Unlocked => LunaWindowStyle.AccentGood,
            AchievementNodeState.Available => LunaWindowStyle.Accent,
            _ => LunaWindowStyle.TextMuted,
        };

        var desc = proto.IsKillAchievement
            ? AchievementKillText.GetDescription(proto, _prototypes)
            : AchievementJobText.GetDescription(proto, _entities, _prototypes);
        if (state == AchievementNodeState.Locked)
            desc += "\n\n" + Loc.GetString("ui-achievements-hidden-prereq");

        DetailDescription.SetMessage(FormattedMessage.FromUnformatted(desc));

        if (state == AchievementNodeState.Unlocked && entry?.UnlockedAtTicks is { } ticks)
        {
            var time = new DateTime(ticks, DateTimeKind.Utc).ToLocalTime();
            DetailUnlockedAt.Text = Loc.GetString("ui-achievements-unlocked-at", ("time", time.ToString("g")));
            DetailUnlockedAt.Visible = true;
        }
        else
        {
            DetailUnlockedAt.Visible = false;
        }

        RefreshRewardPanel(proto, state, entry);
    }

    private void RefreshRewardPanel(AchievementPrototype proto, AchievementNodeState state, AchievementEntry? entry)
    {
        RewardItems.RemoveAllChildren();

        if (!proto.HasRewards || state != AchievementNodeState.Unlocked)
        {
            RewardPanel.Visible = false;
            return;
        }

        RewardPanel.Visible = true;
        var claimed = entry?.RewardClaimed == true;

        foreach (var reward in proto.Rewards)
        {
            if (reward.Count <= 0 || !_prototypes.HasIndex(reward.Prototype))
                continue;

            var entProto = _prototypes.Index(reward.Prototype);
            var name = Loc.GetString(entProto.Name);
            var tooltip = reward.Count > 1 ? $"{name} ×{reward.Count}" : name;

            var item = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = Control.HAlignment.Center,
                SeparationOverride = 2,
                ToolTip = tooltip,
            };

            var icon = new TextureRect
            {
                SetSize = new Vector2(32, 32),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = Control.HAlignment.Center,
                ModulateSelfOverride = claimed ? Color.FromHex("#888888") : Color.White,
                MouseFilter = Control.MouseFilterMode.Ignore,
            };
            icon.Texture = Sprite.GetPrototypeIcon(reward.Prototype).Default;
            item.AddChild(icon);

            if (reward.Count > 1)
            {
                var count = new Label
                {
                    Text = $"×{reward.Count}",
                    HorizontalAlignment = Control.HAlignment.Center,
                    Align = Label.AlignMode.Center,
                    MouseFilter = Control.MouseFilterMode.Ignore,
                };
                LunaWindowStyle.StyleMuted(count);
                count.FontOverride = LunaWindowStyle.FontSmall;
                count.ModulateSelfOverride = claimed ? Color.FromHex("#888888") : LunaWindowStyle.TextPrimary;
                item.AddChild(count);
            }

            RewardItems.AddChild(item);
        }

        ClaimRewardButton.Visible = !claimed;
        ClaimRewardButton.Disabled = claimed;
        RewardClaimedLabel.Visible = claimed;
    }

    private void ClearDetail()
    {
        DetailIcon.SetLayers([], Sprite);
        DetailIcon.SetModulate(null);
        DetailTitle.Text = Loc.GetString("ui-achievements-select");
        DetailStatus.Text = string.Empty;
        DetailDescription.SetMessage(FormattedMessage.Empty);
        DetailUnlockedAt.Visible = false;
        RewardPanel.Visible = false;
        RewardItems.RemoveAllChildren();
    }

    private void RefreshProgressCounter()
    {
        var unlocked = _entries.Count(e => e.Unlocked);
        var total = _prototypes.EnumeratePrototypes<AchievementPrototype>().Count(p => !p.Disabled);
        ProgressCounter.Text = $"{unlocked}/{total}";
    }
}
