// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingEntry : Control
{
    public LuaVendingEntry()
    {
        RobustXamlLoader.Load(this);
        Price.FontOverride = LunaWindowStyle.FontSmall;
        Price.FontColorOverride = LunaWindowStyle.Accent;
        Amount.FontOverride = LunaWindowStyle.FontSmall;
        Amount.FontColorOverride = LunaWindowStyle.TextSecondary;
        Panel.Title.FontOverride = LunaWindowStyle.FontBody;
        Panel.Title.FontColorOverride = LunaWindowStyle.TextPrimary;
    }

    public void SetDisabled(bool disabled)
    {
        Panel.Button.Disabled = disabled;
        Amount.FontColorOverride = disabled ? LunaWindowStyle.AccentBad : LunaWindowStyle.TextSecondary;
        Price.FontColorOverride = disabled ? LunaWindowStyle.TextMuted : LunaWindowStyle.Accent;
        Panel.Title.FontColorOverride = disabled ? LunaWindowStyle.TextMuted : LunaWindowStyle.TextPrimary;
        Panel.UpdateColor();
    }
}
