// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingButton : Button
{
    public event Action? OnDrawModeChanged;

    public LuaVendingButton()
    {
        RobustXamlLoader.Load(this);
        Label.Visible = false;
        ClipText = true;
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
