// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingPanel : Control
{
    public static readonly Color DefaultColor = LunaWindowStyle.PanelBg;
    public static readonly Color DefaultBorderColor = LunaWindowStyle.PanelBorder;
    public static readonly Color DefaultHoveredColor = LunaWindowStyle.Accent;
    private static readonly Color HoveredBg = Color.FromHex("#163040");
    private static readonly Color DisabledBg = Color.FromHex("#1C2433");

    public Color Color = DefaultColor;
    public Color BorderColor = DefaultBorderColor;
    public Color HoveredColor = DefaultHoveredColor;

    public LuaVendingPanel()
    {
        RobustXamlLoader.Load(this);
        Button.OnDrawModeChanged += UpdateColor;
        UpdateColor();
    }

    public void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        if (Button.Disabled)
            panel.BackgroundColor = DisabledBg;
        else
            panel.BackgroundColor = Button.IsHovered ? HoveredBg : Color;
        panel.BorderColor = Button.Disabled
            ? LunaWindowStyle.TextMuted
            : Button.IsHovered ? HoveredColor : BorderColor;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }
}
