// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Lua.UIKit.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingSection : Control
{
    public LuaVendingSection()
    {
        RobustXamlLoader.Load(this);
        Label.FontOverride = LunaWindowStyle.FontTitle;
        Label.FontColorOverride = LunaWindowStyle.TextPrimary;
        LunaWindowStyle.StyleDivider(Divider);
    }

    public void SetHeaderVisible(bool visible)
    {
        Label.Visible = visible;
        Divider.Visible = visible;
        Margin = visible ? new Thickness(0, 10, 0, 0) : new Thickness(0);
    }
}
