using System.Linq;
using System.Numerics;
using Content.Lua.UIKit.Styles;
using Content.Client.Lathe;
using Content.Shared._NF.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._NF.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    private const float BaseCardSize = 64f;
    private const float BaseIconSize = 56f;
    private const float BaseIconScale = 1.75f;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    // Public fields
    public TechnologyPrototype Prototype;
    public IReadOnlyList<ProtoId<TechnologyPrototype>> EffectivePrerequisites;
    public Action<TechnologyPrototype, ResearchAvailability, bool>? SelectAction; // Lua
    public ResearchAvailability Availability;

    private float _scale = 1f;

    // Some visuals - now using centralized color scheme
    public static readonly Color DefaultColor = ResearchColorScheme.UIColors.DefaultTechBackground;
    public static readonly Color DefaultBorderColor = ResearchColorScheme.UIColors.DefaultTechBorder;
    public static readonly Color DefaultHoveredColor = ResearchColorScheme.UIColors.DefaultTechHover;

    public Color BackgroundColor = DefaultColor;
    public Color BorderColor = DefaultBorderColor;
    public Color HoveredColor = DefaultHoveredColor;
    public Color SelectedColor = DefaultHoveredColor;

    // Selection state
    private bool _isSelected = false;
    public bool IsSelected
    {
        get => _isSelected;
        set
        {
            if (_isSelected == value)
                return;
            _isSelected = value;
            UpdateColor();
        }
    }

    public FancyResearchConsoleItem(
        TechnologyPrototype proto,
        IReadOnlyList<ProtoId<TechnologyPrototype>> effectivePrerequisites,
        SpriteSystem sprite,
        ResearchAvailability availability)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Availability = availability;
        Prototype = proto;
        EffectivePrerequisites = effectivePrerequisites;

        // Get the primary discipline for background color
        var primaryDiscipline = _prototype.Index<TechDisciplinePrototype>(proto.Discipline);
        var primaryColor = primaryDiscipline.Color;

        // Handle technology icon - prioritize EntityIcon for full sprite layers
        if (ResolveEntityIcon(proto) is { } iconId)
        {
            // Use EntityPrototypeView to show all sprite layers
            ResearchDisplay.SetPrototype(iconId);
        }
        else if (proto.Icon != null)
        {
            // For legacy Icon support, we need to handle this differently since EntityPrototypeView
            // expects entity prototypes. For now, we'll need a fallback approach.
            // TODO: Consider deprecating the Icon field in favor of EntityIcon

            // We cannot directly set a SpriteSpecifier on EntityPrototypeView
            // This is a limitation of the new approach - EntityIcon should be preferred
            // For now, this will show no icon for legacy Icon-only technologies
            ResearchDisplay.SetPrototype(null);
        }
        else
        {
            // No icon specified
            ResearchDisplay.SetPrototype(null);
        }

        Button.OnPressed += Selected;
        Button.OnKeyBindDown += RightSelected; // Lua
        Button.OnDrawModeChanged += UpdateColor;

        ApplyRecipePreview(proto);
        LunaWindowStyle.StyleTiny(RecipePreview);
        RecipePreview.FontColorOverride = LunaWindowStyle.TextSecondary;
        LunaWindowStyle.StyleProgressGood(ProjectProgress, 4f);

        // Set colors - border & background color varies by availability state
        BorderColor = ResearchColorScheme.GetTechBorderColor(availability);

        // Calculate background colors based on availability using centralized factors
        var darkenFactor = ResearchColorScheme.GetBackgroundInterpolationFactor(availability);

        BackgroundColor = Color.InterpolateBetween(primaryColor, Color.Black, darkenFactor);

        // Create brighter versions of the discipline colors for hover by interpolating with white
        var hoverFactor = ResearchColorScheme.GetHoverMixingFactor();
        HoveredColor = Color.InterpolateBetween(primaryColor, Color.White, hoverFactor);

        // Create even brighter versions for selection (persistent bright highlight)
        var selectionFactor = ResearchColorScheme.GetSelectionMixingFactor();
        SelectedColor = Color.InterpolateBetween(primaryColor, Color.White, selectionFactor);

        Panel.PanelOverride = new RoundedStyleBoxFlat
        {
            BackgroundColor = BackgroundColor,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(2.5f),
            CornerRadius = 8f
        };

        UpdateColor();
    }

    public void SetProjectProgress(float? progress)
    {
        if (progress == null)
        {
            ProjectProgress.Visible = false;
            return;
        }

        ProjectProgress.Visible = true;
        ProjectProgress.Value = Math.Clamp(progress.Value, 0f, 1f);
    }

    private void ApplyRecipePreview(TechnologyPrototype proto)
    {
        if (proto.RecipeUnlocks.Count == 0)
        {
            RecipePreview.Text = Loc.GetString("research-console-placeholder-hub");
            return;
        }

        var lathe = IoCManager.Resolve<IEntityManager>().System<LatheSystem>();
        var names = new List<string>();
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            if (names.Count >= 2)
                break;
            names.Add(lathe.GetRecipeName(recipeId));
        }

        var preview = string.Join(" - ", names);
        if (proto.RecipeUnlocks.Count > 2)
            preview += " +";
        RecipePreview.Text = preview;
        RecipePreview.ToolTip = string.Join("\n", proto.RecipeUnlocks.Select(id => lathe.GetRecipeName(id)));
    }

    public void SetGraphCaptionVisible(bool visible)
    {
        RecipePreview.Visible = visible;
        ApplyScale(_scale);
    }

    public void ShowGraphBox(string caption)
    {
        RecipePreview.Visible = true;
        RecipePreview.Text = caption;
        RecipePreview.ToolTip = caption;
        ApplyScale(_scale);
    }

    /// Must resize <see cref="Panel"/> MinSize — XAML locks it at 64 and otherwise the plate stays huge.
    public void SetScale(float scale)
    {
        _scale = MathF.Max(0.1f, scale);
        ApplyScale(_scale);
    }

    private void ApplyScale(float scale)
    {
        var caption = RecipePreview.Visible ? 16f * scale : 0f;
        var card = BaseCardSize * scale;
        var icon = BaseIconSize * scale;
        SetSize = new Vector2(card + 8f, card + caption + 8f);
        RootContainer.SetSize = new Vector2(card, card + caption);

        Panel.SetSize = new Vector2(card, card);
        Panel.MinSize = new Vector2(card, card);
        ResearchDisplay.SetSize = new Vector2(icon, icon);
        ResearchDisplay.Scale = new Vector2(BaseIconScale * scale, BaseIconScale * scale);

        RecipePreview.MaxWidth = card;
    }

    private void UpdateColor()
    {
        if (Panel.PanelOverride is not RoundedStyleBoxFlat singleColorPanel)
            return;

        // Priority: Selected > Hovered > Normal
        if (IsSelected)
            singleColorPanel.BackgroundColor = SelectedColor;
        else if (Button.IsHovered)
            singleColorPanel.BackgroundColor = HoveredColor;
        else
            singleColorPanel.BackgroundColor = BackgroundColor;

        singleColorPanel.BorderColor = BorderColor;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Button.OnPressed -= Selected;
        Button.OnKeyBindDown -= RightSelected; // Lua
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, Availability, false); // Lua
    }

    // Lua start
    private void RightSelected(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.UIRightClick
            && !Button.Disabled)
        {
            SelectAction?.Invoke(Prototype, Availability, true);
        }
    }
    // Lua end

    private EntProtoId? ResolveEntityIcon(TechnologyPrototype proto)
    {
        if (proto.EntityIcon is { } icon)
        {
            if (_prototype.HasIndex(icon))
                return icon;

            if (_prototype.TryIndex<LatheRecipePrototype>(icon.Id, out var asRecipe) &&
                asRecipe.Result is { } recipeResult &&
                _prototype.HasIndex(recipeResult))
            {
                return recipeResult;
            }
        }

        foreach (var unlock in proto.RecipeUnlocks)
        {
            if (!_prototype.TryIndex(unlock, out LatheRecipePrototype? unlockRecipe))
                continue;
            if (unlockRecipe.Result is not { } result)
                continue;
            if (_prototype.HasIndex(result))
                return result;
        }

        return null;
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    public DrawButton()
    {
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
