using System.Linq;
using Content.Lua.UIKit.Styles;
using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared._NF.Research;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility; // Added for SpriteSpecifier

namespace Content.Client._NF.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;
    private bool _hasAccess;
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;
    public Action<TechnologyPrototype>? CancelAction;
    public bool CanResearch;
    public bool IsCancel;

    public FancyTechnologyInfoPanel(TechnologyPrototype proto, ProtoId<RndFactionPrototype>? researchFaction, bool hasAccess, ResearchAvailability availability, SpriteSystem sprite, ResearchProjectUiState? project = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("research");

        var lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();
        Prototype = proto;
        _hasAccess = hasAccess;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index(proto.Discipline).Icon);

        // Handle technology icon - use EntityIcon if available, otherwise fall back to Icon
        if (ResolveEntityIcon(proto) is { } iconId)
        {
            TechnologyTexture.SetPrototype(iconId);
        }
        else if (proto.Icon != null)
        {
            // For backward compatibility, we need to handle SpriteSpecifier icons
            //_sawmill.Warning($"Technology {proto.ID} uses legacy Icon field instead of EntityIcon. Consider migrating to EntityIcon for better performance.");

            // For now, we'll need to handle this differently since EntityPrototypeView doesn't directly support SpriteSpecifier
            // We can try to extract the entity from SpriteSpecifier if it's an EntityPrototype type
            if (proto.Icon is SpriteSpecifier.EntityPrototype entityProtoSpec)
            {
                TechnologyTexture.SetPrototype(entityProtoSpec.EntityPrototypeId);
            }
            else
            {
                // For other SpriteSpecifier types, we'll need a different approach
                // Since this is a complex conversion, we'll log this case for now
                //_sawmill.Error($"Technology {proto.ID} uses unsupported Icon type. Please use EntityIcon field instead.");
            }
        }
        else
        {
            //_sawmill.Warning($"Technology {proto.ID} has no icon specified. Consider adding an EntityIcon field.");
        }

        InitializePrerequisites(researchFaction, proto, research, sprite);

        InitializeRecipeUnlocks(proto, lathe, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ApplyProjectState(project, availability);

        LunaWindowStyle.StyleHeading(TechnologyNameLabel);
        LunaWindowStyle.StyleSecondary(TechnologyCostLabel);
        var color = ResearchColorScheme.GetInfoPanelColor(availability);
        if (color is { } restoredCostColor)
            TechnologyCostLabel.FontColorOverride = restoredCostColor;

        ResearchButton.OnPressed += args =>
        {
            _sawmill.Debug($"Research button pressed for {proto.ID}");
            if (IsCancel)
            {
                CancelAction?.Invoke(proto);
                return;
            }
            if (BuyAction != null)
            {
                _sawmill.Debug($"Triggering BuyAction for {proto.ID}");
                BuyAction.Invoke(proto);
            }
            else
            {
                _sawmill.Error($"BuyAction is null for {proto.ID}");
            }
        };

        _sawmill.Debug($"Created tech panel: {proto.ID}, availability: {availability}, button disabled: {ResearchButton.Disabled}");
    }

    public void SyncProject(ResearchProjectUiState? project, ResearchAvailability availability)
    {
        ApplyProjectState(project, availability);
        var color = ResearchColorScheme.GetInfoPanelColor(availability);
        if (color is { } costColor)
            TechnologyCostLabel.FontColorOverride = costColor;
    }

    private void ApplyProjectState(ResearchProjectUiState? project, ResearchAvailability availability)
    {
        if (project != null && availability != ResearchAvailability.Researched)
        {
            TechnologyCostLabel.Text = Loc.GetString(
                "research-console-tech-cost-label",
                ("cost", $"{project.Progress}/{project.Cost}"));
        }
        else
        {
            TechnologyCostLabel.Text = Loc.GetString(
                "research-console-tech-cost-label",
                ("cost", Prototype.Cost));
        }

        ResearchButton.Visible = true;

        if (availability == ResearchAvailability.Researched)
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-researched-button");
            IsCancel = false;
            CanResearch = false;
        }
        else if (project != null && project.CanCancel)
        {
            IsCancel = true;
            ResearchButton.Text = Loc.GetString("research-console-menu-server-cancel-project-button");
            CanResearch = _hasAccess;
        }
        else
        {
            IsCancel = false;
            ResearchButton.Text = Loc.GetString("research-console-menu-server-start-project-button");
            CanResearch = _hasAccess && availability != ResearchAvailability.Researched;
        }

        ToggleResearchButton(CanResearch);
    }

    // Lua start
    public void ToggleResearchButton(bool enable)
    {
        ResearchButton.Disabled = !enable;
    }
    // Lua end

    private void InitializePrerequisites(ProtoId<RndFactionPrototype>? researchFaction, TechnologyPrototype proto, ResearchSystem research, SpriteSystem sprite)
    {
        // required techs always visible, label in required techs
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }

        var prerequisites = research.GetTechnologyPrerequisites(researchFaction, proto);
        NoPrereqLabel.Visible = prerequisites.Count == 0;
        foreach (var techId in prerequisites)
        {
            var tech = _proto.Index(techId);
            var description = research.GetTechnologyDescription(tech, true, false, true);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
        }
    }

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(recipeId);
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, recipe, _proto, sprite, lathe));
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        // No need to explicitly remove handlers as the control is being destroyed
    }

    private EntProtoId? ResolveEntityIcon(TechnologyPrototype proto)
    {
        if (proto.EntityIcon is { } icon)
        {
            if (_proto.HasIndex(icon))
                return icon;

            if (_proto.TryIndex<LatheRecipePrototype>(icon.Id, out var asRecipe) &&
                asRecipe.Result is { } recipeResult &&
                _proto.HasIndex(recipeResult))
            {
                return recipeResult;
            }
        }

        foreach (var unlock in proto.RecipeUnlocks)
        {
            if (!_proto.TryIndex(unlock, out LatheRecipePrototype? unlockRecipe))
                continue;
            if (unlockRecipe.Result is not { } result)
                continue;
            if (_proto.HasIndex(result))
                return result;
        }

        return null;
    }
}
