// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Linq;
using Content.Lua.UIKit.Styles;
using Content.Client.Guidebook.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookWindow : LunaWindow, ILinkClickHandler, IAnchorClickHandler
{
    private const int MinFontStep = -2;
    private const int MaxFontStep = 4;
    private const string WikiLunaUrl = "https://wiki.deadspace14.net/Луна:Заглавная_страница";
    private const string LuaCorpSiteUrl = "https://luacorp.ru";

    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;
    [Dependency] private readonly IClipboardManager _clipboard = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = new();
    private readonly ISawmill _sawmill;

    private readonly List<ProtoId<GuideEntryPrototype>> _history = new();
    private readonly List<ProtoId<GuideEntryPrototype>> _pins = new();
    private int _historyIndex = -1;
    private bool _suppressHistory;
    private GuideEntry? _rulesHomeEntry;
    private ProtoId<GuideEntryPrototype>? _rootHomeId;
    private int _fontStep;
    private string? _pendingWebUrl;

    public ProtoId<GuideEntryPrototype> LastEntry;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("guidebook");

        ApplyLunaChrome();
        ApplyLunaInterior();
        foreach (var child in Tree.Children)
        {
            if (child is ScrollContainer scroll)
                scroll.ReturnMeasure = false;
        }
        Tree.AutoExpand = false;

        Tree.OnSelectedItemChanged += OnSelectionChanged;

        Split.OnKeyBindDown += ToggleTree;
        OnKeyBindDown += ToggleTree;

        SearchBar.OnTextChanged += _ => HandleFilter();
        TreeSearchBar.OnTextChanged += _ => ApplyTreeFilter();

        BackButton.OnPressed += _ => NavigateHistory(-1);
        ForwardButton.OnPressed += _ => NavigateHistory(1);
        HomeRootButton.OnPressed += _ => GoHome();
        ToggleTreeButton.OnPressed += _ => SetTreeVisible(!TreePanel.Visible);
        ExpandAllButton.OnPressed += _ => Tree.SetAllExpanded(true);
        CollapseAllButton.OnPressed += _ => Tree.SetAllExpanded(false);
        ScrollTopButton.OnPressed += _ => Scroll.SetScrollValue(default);
        FontMinusButton.OnPressed += _ => AdjustFont(-1);
        FontPlusButton.OnPressed += _ => AdjustFont(1);
        PinButton.OnPressed += _ => PinCurrent(true);
        UnpinButton.OnPressed += _ => PinCurrent(false);

        WebLinkOpenButton.OnPressed += _ =>
        {
            if (_pendingWebUrl != null)
                _uriOpener.OpenUri(_pendingWebUrl);
        };
        WebLinkCopyButton.OnPressed += _ =>
        {
            if (_pendingWebUrl != null)
                _clipboard.SetText(_pendingWebUrl);
        };
        WebLinkCloseButton.OnPressed += _ => HideWebLinkBar();

        // Embedded CEF disabled: Robust.Client.WebView is not available for engine 290 via wizards CDN.
        BrowserNavBar.Visible = false;
        BrowserHost.Visible = false;
        BrowserBackButton.OnPressed += _ => { };
        BrowserForwardButton.OnPressed += _ => { };
        BrowserReloadButton.OnPressed += _ => { };
        BrowserGoButton.OnPressed += _ => NavigateFromUrlBar();
        BrowserUrlEdit.OnTextEntered += _ => NavigateFromUrlBar();
        BrowserCloseButton.OnPressed += _ => CloseBrowser();

        HomeButton.OnPressed += _ =>
        {
            if (_rulesHomeEntry != null)
                ShowGuide(_rulesHomeEntry, pushHistory: true);
        };
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        ContentPanel.PanelOverride = LunaWindowStyle.Panel();
        LunaWindowStyle.StyleDivider(ToolbarDivider);
        LunaWindowStyle.StyleDivider(PinsDivider);
        LunaWindowStyle.StyleVerticalDivider(SplitDivider);
        LunaWindowStyle.StyleMuted(PlaceholderLabel);
        LunaWindowStyle.StyleMuted(PlaceholderLabel2);
        LunaWindowStyle.StyleSecondary(BreadcrumbLabel);
        LunaWindowStyle.StyleMuted(PinsHeader);
        LunaWindowStyle.StyleSecondary(WebLinkTitleLabel);
        LunaWindowStyle.ApplyCompactStyle(Toolbar);
        LunaWindowStyle.ApplyCompactStyle(ToolsRow);
        LunaWindowStyle.ApplyCompactStyle(WebLinkBar);
        LunaWindowStyle.ApplyCompactStyle(BrowserNavBar);
        BrowserUrlEdit.AddStyleClass(StyleNano.StyleClassLineEditSliderThin);
        LunaWindowStyle.ApplyCompactStyle(SearchContainer);
        LunaWindowStyle.ApplyCompactStyle(ReturnContainer);
        UpdateHistoryButtons();
        RefreshPins();
    }

    public void HandleClick(string link)
    {
        if (TryOpenWebLink(link))
            return;

        if (!_entries.TryGetValue(link, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry, pushHistory: true);
    }

    private bool TryOpenWebLink(string link)
    {
        if (!IsHttpUrl(link))
            return false;

        _pendingWebUrl = link;
        WebLinkBar.Visible = true;
        WebLinkTitleLabel.Text = Loc.GetString("guidebook-weblink-fallback");
        WebLinkUrlEdit.Text = link;
        LunaWindowStyle.StyleSecondary(WebLinkTitleLabel);
        return true;
    }

    private void OpenExternalSite(string url)
    {
        _pendingWebUrl = url;
        WebLinkBar.Visible = true;
        WebLinkTitleLabel.Text = Loc.GetString("guidebook-weblink-fallback");
        WebLinkUrlEdit.Text = url;
        LunaWindowStyle.StyleSecondary(WebLinkTitleLabel);
        _uriOpener.OpenUri(url);
    }

    private void NavigateFromUrlBar()
    {
        var url = BrowserUrlEdit.Text.Trim();
        if (!IsHttpUrl(url))
            return;

        OpenExternalSite(url);
    }

    private void CloseBrowser()
    {
        BrowserNavBar.Visible = false;
        BrowserHost.Visible = false;
        Scroll.Visible = true;
    }

    private void HideWebLinkBar()
    {
        WebLinkBar.Visible = false;
        WebLinkUrlEdit.Text = string.Empty;
    }

    private static bool IsHttpUrl(string link)
    {
        return link.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
               || link.StartsWith("https://", StringComparison.OrdinalIgnoreCase);
    }

    public void HandleAnchor(IPrototypeLinkControl prototypeLinkControl)
    {
        var prototype = prototypeLinkControl.LinkedPrototype;
        if (prototype == null)
            return;

        var (linkableControls, _) = GetLinkableControlsAndLinks(EntryContainer);
        foreach (var linkableControl in linkableControls)
        {
            if (linkableControl.RepresentedPrototype != prototype)
                continue;

            if (linkableControl is not Control control)
                return;

            if (!control.Visible)
                control.Visible = true;

            UserInterfaceManager.DeferAction(() =>
            {
                if (control.GetControlScrollPosition() is not { } position)
                    return;

                Scroll.HScrollTarget = position.X;
                Scroll.VScrollTarget = position.Y;
            });

            break;
        }
    }

    private void OnSelectionChanged(TreeItem? item)
    {
        if (item != null && item.Metadata is GuideEntry entry)
        {
            ShowGuide(entry, pushHistory: true);
            ReturnContainer.Visible = entry.RuleEntry;
            _rulesHomeEntry = entry.RuleEntry ? entry : _rulesHomeEntry;
        }
        else
            ClearSelectedGuide();
    }

    public void ClearSelectedGuide()
    {
        CloseBrowser();
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        SearchContainer.Visible = false;
        EntryContainer.RemoveAllChildren();
        BreadcrumbLabel.Text = string.Empty;
    }

    private void ToggleTree(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.UIRightClick && _entries.Count != 1)
            SetTreeVisible(!TreePanel.Visible);
    }

    private void SetTreeVisible(bool visible)
    {
        if (_entries.Count == 1)
            return;

        TreePanel.Visible = visible;
        Split.State = SplitContainer.SplitState.Auto;
        Split.ResizeMode = visible
            ? SplitContainer.SplitResizeMode.RespectChildrenMinSize
            : SplitContainer.SplitResizeMode.NotResizable;
    }

    private void GoHome()
    {
        if (_rootHomeId == null || !_entries.TryGetValue(_rootHomeId.Value, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry, pushHistory: true);
    }

    private void ShowGuide(GuideEntry entry, bool pushHistory)
    {
        CloseBrowser();
        Scroll.SetScrollValue(default);
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        SearchBar.Text = string.Empty;
        EntryContainer.RemoveAllChildren();
        using var file = _resourceManager.ContentFileReadText(entry.Text);

        SearchContainer.Visible = entry.FilterEnabled;

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");

        StyleGuideContent(EntryContainer);
        ApplyFontStep();
        LastEntry = entry.Id;
        UpdateBreadcrumb(entry);

        if (pushHistory)
            PushHistory(entry.Id);

        var (linkableControls, linkControls) = GetLinkableControlsAndLinks(EntryContainer);

        HashSet<IPrototype> availablePrototypeLinks = new();
        foreach (var linkableControl in linkableControls)
        {
            var prototype = linkableControl.RepresentedPrototype;
            if (prototype != null)
                availablePrototypeLinks.Add(prototype);
        }

        foreach (var linkControl in linkControls)
        {
            var prototype = linkControl.LinkedPrototype;
            if (prototype != null && availablePrototypeLinks.Contains(prototype))
                linkControl.EnablePrototypeLink();
        }
        if (entry.Id == "WikiLuna")
            OpenExternalSite(WikiLunaUrl);
        else if (entry.Id == "LuaCorpSite")
            OpenExternalSite(LuaCorpSiteUrl);
    }

    private void PinCurrent(bool pin)
    {
        if (string.IsNullOrEmpty(LastEntry))
            return;

        if (pin)
        {
            if (!_pins.Contains(LastEntry))
                _pins.Insert(0, LastEntry);
        }
        else
            _pins.Remove(LastEntry);

        RefreshPins();
    }

    private void RefreshPins()
    {
        PinsContainer.RemoveAllChildren();
        foreach (var id in _pins)
        {
            if (!_entries.TryGetValue(id, out var entry))
                continue;

            var button = new Button
            {
                Text = Loc.GetString(entry.Name),
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = id
            };
            LunaWindowStyle.ApplyCompactStyle(button);
            var capture = id;
            button.OnPressed += _ => JumpToEntry(capture);
            PinsContainer.AddChild(button);
        }
    }

    private void JumpToEntry(ProtoId<GuideEntryPrototype> id)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry, pushHistory: true);
    }

    private void AdjustFont(int delta)
    {
        _fontStep = Math.Clamp(_fontStep + delta, MinFontStep, MaxFontStep);
        ApplyFontStep();
    }

    private void ApplyFontStep()
    {
        var body = LunaWindowStyle.FontSizeBody + _fontStep;
        var title = LunaWindowStyle.FontSizeTitle + _fontStep;
        var map = LunaWindowStyle.FontSizeMapLabel + _fontStep;
        var cache = IoCManager.Resolve<IResourceCache>();

        foreach (var child in EnumerateDeep(EntryContainer))
        {
            switch (child)
            {
                case Label label when label.HasStyleClass("LabelHeadingBigger"):
                    label.FontOverride = cache.NotoStack(variation: "Bold", size: Math.Max(10, map));
                    break;
                case Label label when label.HasStyleClass("LabelHeading"):
                    label.FontOverride = cache.NotoStack(variation: "Bold", size: Math.Max(10, title));
                    break;
                case Label label:
                    label.FontOverride = cache.NotoStack(size: Math.Max(9, body));
                    break;
            }
        }
    }

    private static IEnumerable<Control> EnumerateDeep(Control root)
    {
        foreach (var child in root.Children)
        {
            yield return child;
            foreach (var nested in EnumerateDeep(child))
                yield return nested;
        }
    }

    private void PushHistory(ProtoId<GuideEntryPrototype> id)
    {
        if (_suppressHistory)
            return;

        if (_historyIndex >= 0 && _historyIndex < _history.Count && _history[_historyIndex] == id)
            return;

        if (_historyIndex < _history.Count - 1)
            _history.RemoveRange(_historyIndex + 1, _history.Count - _historyIndex - 1);

        _history.Add(id);
        _historyIndex = _history.Count - 1;
        UpdateHistoryButtons();
    }

    private void NavigateHistory(int delta)
    {
        var next = _historyIndex + delta;
        if (next < 0 || next >= _history.Count)
            return;

        _historyIndex = next;
        UpdateHistoryButtons();

        var id = _history[_historyIndex];
        if (!_entries.TryGetValue(id, out var entry))
            return;

        _suppressHistory = true;
        try
        {
            if (Tree.TryGetIndexFromMetadata(entry, out var index))
            {
                Tree.ExpandParentEntries(index.Value);
                Tree.SetSelectedIndex(index);
            }
            else
                ShowGuide(entry, pushHistory: false);
        }
        finally
        {
            _suppressHistory = false;
        }
    }

    private void UpdateHistoryButtons()
    {
        BackButton.Disabled = _historyIndex <= 0;
        ForwardButton.Disabled = _historyIndex < 0 || _historyIndex >= _history.Count - 1;
    }

    private void UpdateBreadcrumb(GuideEntry entry)
    {
        var parts = new List<string>();
        CollectBreadcrumb(entry.Id, parts);
        parts.Reverse();
        BreadcrumbLabel.Text = string.Join(" › ", parts);
        LunaWindowStyle.StyleSecondary(BreadcrumbLabel);
    }

    private void CollectBreadcrumb(ProtoId<GuideEntryPrototype> id, List<string> parts)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return;

        parts.Add(Loc.GetString(entry.Name));

        foreach (var (parentId, parent) in _entries)
        {
            if (!parent.Children.Contains(id))
                continue;

            CollectBreadcrumb(parentId, parts);
            return;
        }
    }

    private static void StyleGuideContent(Control root)
    {
        foreach (var child in root.Children)
        {
            switch (child)
            {
                case Label label:
                    if (label.HasStyleClass("LabelHeadingBigger"))
                    {
                        label.FontOverride = LunaWindowStyle.FontMapLabel;
                        label.FontColorOverride = LunaWindowStyle.Accent;
                        label.Margin = new Thickness(0, 4, 0, 10);
                    }
                    else if (label.HasStyleClass("LabelHeading"))
                    {
                        label.FontOverride = LunaWindowStyle.FontTitle;
                        label.FontColorOverride = LunaWindowStyle.TextPrimary;
                        label.Margin = new Thickness(0, 2, 0, 8);
                    }
                    else if (label.HasStyleClass("LabelKeyText"))
                    {
                        label.FontOverride = LunaWindowStyle.FontBody;
                        label.FontColorOverride = LunaWindowStyle.Accent;
                        label.Margin = new Thickness(0, 2, 0, 6);
                    }
                    else
                    {
                        label.FontOverride = LunaWindowStyle.FontBody;
                        label.FontColorOverride = LunaWindowStyle.TextSecondary;
                    }
                    break;
                case RichTextLabel rich:
                    LunaWindowStyle.StyleCompactRich(rich);
                    rich.ModulateSelfOverride = LunaWindowStyle.TextPrimary;
                    break;
            }

            StyleGuideContent(child);
        }
    }

    public void UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        _entries = entries;
        _history.Clear();
        _historyIndex = -1;
        UpdateHistoryButtons();
        TreeSearchBar.Text = string.Empty;
        HideWebLinkBar();

        var firstRoot = GetSortedEntries(rootEntries).FirstOrDefault();
        if (forceRoot != null)
            _rootHomeId = forceRoot;
        else if (rootEntries is { Count: > 0 })
            _rootHomeId = rootEntries[0];
        else if (firstRoot != null)
            _rootHomeId = firstRoot.Id;
        else
            _rootHomeId = null;

        RepopulateTree(rootEntries, forceRoot);
        ClearSelectedGuide();

        Split.State = SplitContainer.SplitState.Auto;
        if (entries.Count == 1)
        {
            SetTreeVisible(false);
            selected = entries.Keys.First();
        }
        else
        {
            SetTreeVisible(true);
        }

        RefreshPins();

        if (selected != null)
        {
            var item = Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry entry && entry.Id == selected);
            Tree.SetSelectedIndex(item?.Index);
        }
        else
        {
            var item = Tree.Items.First();
            Tree.SetSelectedIndex(item?.Index);
        }
    }

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = new(_entries.Keys);
            foreach (var entry in _entries.Values)
            {
                entries.ExceptWith(entry.Children);
            }
            rootEntries = entries.ToList();
        }

        return rootEntries
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(rootEntry => Loc.GetString(rootEntry.Name));
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = new();

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
        {
            AddEntry(entry.Id, parent, addedEntries);
        }

        Tree.SetAllExpanded(false);
        StyleTreeLabels();
        ApplyTreeFilter();
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            _sawmill.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        item.Label.Text = Loc.GetString(entry.Name);

        foreach (var child in entry.Children)
        {
            AddEntry(child, item, addedEntries);
        }

        return item;
    }

    private void StyleTreeLabels()
    {
        foreach (var item in Tree.Items)
        {
            item.Label.FontOverride = LunaWindowStyle.FontSmall;
            item.Label.FontColorOverride = LunaWindowStyle.TextPrimary;
        }
    }

    private void ApplyTreeFilter()
    {
        var query = TreeSearchBar.Text.Trim();
        var empty = query.Length == 0;

        foreach (var item in Tree.Items)
        {
            if (item.Metadata is not GuideEntry entry)
            {
                item.Visible = empty;
                continue;
            }

            var name = Loc.GetString(entry.Name);
            var match = empty || name.Contains(query, StringComparison.CurrentCultureIgnoreCase);
            if (match)
            {
                item.Visible = true;
                if (!empty)
                    ExpandAncestors(item);
            }
            else
            {
                item.Visible = HasVisibleDescendant(item, query);
            }
        }
    }

    private static void ExpandAncestors(TreeItem item)
    {
        var parent = item.Parent;
        while (parent != null)
        {
            if (parent is TreeItem parentItem)
            {
                parentItem.Visible = true;
                parentItem.SetExpanded(true);
            }

            parent = parent.Parent;
        }
    }

    private static bool HasVisibleDescendant(TreeItem item, string query)
    {
        foreach (var child in item.Body.Children)
        {
            if (child is not TreeItem childItem)
                continue;

            if (childItem.Metadata is GuideEntry entry)
            {
                var name = Loc.GetString(entry.Name);
                if (name.Contains(query, StringComparison.CurrentCultureIgnoreCase))
                    return true;
            }

            if (HasVisibleDescendant(childItem, query))
                return true;
        }

        return false;
    }

    private void HandleFilter()
    {
        if (Tree.SelectedItem != null && Tree.SelectedItem.Metadata is GuideEntry entry && entry.FilterEnabled)
        {
            var foundElements = EntryContainer.GetSearchableControls();

            foreach (var element in foundElements)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        }
    }

    private static (List<IPrototypeRepresentationControl>, List<IPrototypeLinkControl>) GetLinkableControlsAndLinks(Control parent)
    {
        List<IPrototypeRepresentationControl> linkableList = new();
        List<IPrototypeLinkControl> linkList = new();

        foreach (var child in parent.Children)
        {
            var hasChildren = child.ChildCount > 0;

            if (child is IPrototypeLinkControl linkChild)
                linkList.Add(linkChild);
            else if (child is IPrototypeRepresentationControl linkableChild)
                linkableList.Add(linkableChild);

            if (!hasChildren)
                continue;

            var (childLinkableList, childLinkList) = GetLinkableControlsAndLinks(child);

            linkableList.AddRange(childLinkableList);
            linkList.AddRange(childLinkList);
        }

        return (linkableList, linkList);
    }
}
