using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Inventory.Widgets;

[GenerateTypedNameReferences]
public sealed partial class InventoryGui : UIWidget
{
    public InventoryGui()
    {
        RobustXamlLoader.Load(this);

        InventoryHotbar.InvertY = true;
        InventoryHotbar.CellSize = SlotControl.DefaultButtonSize;
        InventoryHotbar.ButtonSpacing = 0;
        InventoryHotbar.MarginThickness = 0;

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);

        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }
}
