name: RSI Validator

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'
      - '.github/rsi-schema.json'
      - '.github/validate_rsis.py'
      - '.github/workflows/validate-rsis.yml'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 .github/validate_rsis.py Resources/
