// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Robust.Client.GameStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Content.Shared.CCVar;

namespace Content.Client.Lua.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class NetworkTab : Control
{
    [Dependency] private readonly IClientGameStateManager _state = default!;

    public NetworkTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(CVars.NetPredict, NetPredict);
        Control.AddOptionSlider(CVars.NetBufferSize, NetInterpRatio, _state.MinBufferSize, 8 - _state.MinBufferSize);
        Control.AddOptionSlider(CVars.NetPredictTickBias, NetPredictTickBias, 0, 6);
        Control.AddOptionSlider(CVars.NetPVSEntityBudget, NetPvsSpawn, 20, 150);
        Control.AddOptionSlider(CVars.NetPVSEntityEnterBudget, NetPvsEntry, 20, 500);
        Control.AddOptionSlider(CVars.NetPVSEntityExitBudget, NetPvsLeave, 20, 300);
        Control.AddOptionCheckBox(CCVars.ClientGCEnabled, GcCleanupEnabled);
        Control.AddOptionSlider(CCVars.ClientGCIntervalMinutes, GcCleanupInterval, 5, 60);

        NetInterpRatio.Slider.ToolTip = Loc.GetString("ui-options-net-interp-ratio-tooltip");
        NetPredictTickBias.Slider.ToolTip = Loc.GetString("ui-options-net-predict-tick-bias-tooltip");
        NetPvsSpawn.Slider.ToolTip = Loc.GetString("ui-options-net-pvs-spawn-tooltip");
        NetPvsEntry.Slider.ToolTip = Loc.GetString("ui-options-net-pvs-entry-tooltip");
        NetPvsLeave.Slider.ToolTip = Loc.GetString("ui-options-net-pvs-leave-tooltip");
        GcCleanupInterval.Slider.ToolTip = Loc.GetString("ui-options-gc-interval-tooltip");

        Control.Initialize();
    }
}
